export const englishLanguage = {
  "schedulerMaintenance": "Scheduler Maintenance",
  "phaseDefinition": "Phase Definition",
  "search phase": "Search Phase",
  "allStatus": "All Status",
  "all types": "All Types",
  "createNew": "Create New",
  "documentType": "Document Type",
  "requestType": "Request Type",
  "max": "Max",
  "min": "Min",
  "tolerance": "Tolerance",
  "actualValue": "Actual Value",
  "actionsOnFailure": "Actions on Failure",
  "monitoringFrequency": "Monitoring Frequency",
  "expectedValue": "Expected Value",
  "qcId": "QC ID",
  "expectedValueRange": "Expected Value Range",
  "dataPointID": "Data Point ID",
  "pressure": "Pressure",
  "duration": "Duration",
  "division": "Division",
  "docNumber":"Doc Number",
  "userId": "User ID",
  "createdAt": "Created At",
  "updatedAt": "Updated At",
  "rpm": "RPM",
  "workCenterId": "Work Center ID",
  "resourceId": "Resource ID",
  "adjustments": "Adjustments",
  "qualityControlParameters": "Quality Control Parameters",
  "resources": "Resources",
  "tools": "Tools",
  "safetyProcedures": "Safety Procedures",
  "yieldWasteTracking": "Yield & Waste Tracking",
  "triggerPoints": "Trigger Points",
  "packagingLabeling": "Packaging Labeling",
  "ccp": "CCP",
  "stepName": "Step Name",
  "instruction": "Instruction",
  "steps": "Steps",
  "id": "Id",
  "associatedStep": "Associated",
  "expectedCycleTime": "Expected Cycle Time",
  "ingredients": "Ingredients",
  "phases": "Phases",
  "phase": "Phase",
  "phaseId": "Phase ID",
  "phaseName": "Phase Name",
  "inactive": "Inactive",
  "unsavedChangesMessage": "Unsaved changes will be lost. Are you sure you want to leave this page?",
  "unsavedChangesMessages": "Unsaved changes will be lost. Are you sure you want to Clear the form?",
  "recipeId": "Recipe ID",
  "batchSize": "Batch Size",
  "batchUom": "Batch UOM",
  "totalExpectedCycleTime": "Total Expected Cycle Time",
  "totalActualCycleTime": "Total Actual Cycle Time",
  "active": "Active",
  "recipeStepDetails": "Recipe Step Details",
  "workInstructions": "Work Instructions",
  "dataCollections": "Data Collections",
  "parameterLists": "Parameter Lists",
  "classification": "Classification",
  "relaxedRecipeFlow": "Relaxed Flow Recipe",
  "scan": "Scan",
  "shipmentOrderNumber": "Shipment Order No",
  "dispatchDetails": "Dispatch Details",
  "dispatchDateTime": "Dispatch Date & Time",
  "recipientInfo": "Recipient Info",
  "dispatchInfo": "Dispatch Info",
  "recipeSteps": "Phase Steps",
  "recipeType": "Recipe Type",
  "recipe": "Recipe",
  "recipeName": "Recipe",
  "stageType": "Stage Type",
  stage: "Stage",
  "processOrderRelease": "Process Order Release",
  releaseProcessOrder: "Release Process Order",
  processOrder: "Process Order",
  appTitle: "Item Maintenance",
  count: "Count",
  shiftName: "Shift Name",
  description: "Description",
  entityType: "Entity Type",
  entityName: "Entity Name",
  item: "Item",
  searchActivities: "Search Activities",
  logout: "Logout",
  cancel: "Cancel",
  revision: "Revision",
  status: "Status",
  "qtyConsumed": "Qty Consumed",
  procurementType: "Procurement Type",
  lotSize: "Lot Size",
  createShift: "Create Shift",
  workCenter: "Work Center",
  resource: "Resource",
  add: "Add",
  save: "Save",
  main: "Main",
  alternateComponent: "Alternate Component",
  printDocument: "Print Document",
  customData: "Custom Data",
  itemGroup: "Item Group",
  qtyRestriction: "Qty Restriction",
  router: "Router",
  routing: "Routing",
  routingVersion: "Router Version",
  bom: "BOM",
  bomVersion: "BOM Version",
  assemblyDataType: "Asssembly Datatype",
  removalDataType: "Removal DataType",
  receiptDataType: "Receipt Datatype",
  currentVersion: "Current Version",
  itemType: "Item Type",
  create: "Create",
  "sequence": "Sequence",
  "version": "Version",
  "parentMaterial": "Parent Material",
  "validFrom": "Valid From",
  "validTo": "Valid To",
  versions: "Version: ",
  createdDate: "Created Date: ",
  modifiedTime: "Modified Date: ",
  availableDocuments: "Available Documents",
  assignedDocuments: "Assigned Documents",
  document: "Document",
  createItem: "Create Item",
  value: "Value",
  go: "GO",
  copy: "Copy",
  confirmCopy: "Confirm Copy",
  delete: "Delete",
  deleteMessage: "Are you sure you want to delete this item",
  insert: "Insert",
  removeSelected: "Remove Selected",
  removeAll: "Remove All",
  remove: "Remove",
  confirm: "Confirm",
  confirmDelete: "Confirm Delete",
  "boxNumber": "Box Number",
  "boxCapacity": "Box Capacity",
  "packetId": "Packet ID",
  "packetDescription": "Packet Description",
  "remainingCapacity": "Remaining Capacity",
  "totalPacketsInBox": "Total Packets in Box",
  "prelautid": "Material Id",
  "materialName": "Material Name",
  "uom": "UOM",
  "expectedQty": "Expected Qty",
  "unit": "Unit",
  "receivedQty": "Received Qty",
  "actions": "Actions",
  "phaseType": "Phase Type",

  // ========================================= REASON CODE ===================================
  reasonCodeAppTitle: "Reason Code Maintenance",
  reasonCode: "Reason Code",
  category: "Category",
  messageType: "Message Type",
  createReasonCode: "Create Reason Code",
  rowSelectionMsg: "Do you want to continue with the row selection?",
  selectReasonCode: "Select Reason Code",

  // ========================================= REASON CODE ===================================
  routingTitle: "Routing Maintenance",
  "routingType": "Routing Type",
  routingSteps: "Routing Steps",

  subType: "Sub Type",
  dispositionGroup: "Disposition Group",

  relaxedRoutingFlow: "Relaxed Flow Routing",
  replicationToErp: "Replication To ERP",
  details: "Details",
  nextStepId: "Next Step Id",
  "stepId": "Step Id",
  "stepType": "Step Type",
  "stepDescription": "Step Description",
  "previousStepId": "Previous Step Id",
  "maximumLoopCount": "Maximum Loop Count",
  "queueDecision": "Queue Decision",
  "erpControlKey": "ERP Control Key",
  "erpOperation": "ERP Operation",
  "erpWorkCenter": "ERP Work Center",
  "requiredTimeInProcess": "Required Time In Process",
  "specialInstruction": "Special Instruction",
  "erpSequence": "ERP Sequence",
  "blockPcusUntilInspectionFinished": "Block PCUs Until Inspection Finished",
  "entryStep": "Entry Step",
  "isLastReportingStep": "Is Last Reporting Step",
  "reworkStep": "Rework Step",
  routingStepDetails: "Routing Step Details",
  "routingDescription": "Router Description",

  "insertBefore": "Insert Before",
  "insertAfter": "Insert After",
  "createRouting": "Create Route",
  operation: "Operation",
  operationId: "Operation ID",
  "operationVersion": "Operation Version",
  selectMessageType: "Select Message Type",
  selectResource: "Select Resource",
  selectWorkCenter: "Select Work Center",

  // ========================================= BARCODE FORMAT ===================================
  // App Title
  barcodeFormatMaintenance: "Barcode Format Maintenance",

  // Actions & Buttons
  addFormat: "Add Format",
  refresh: "Refresh",
  clone: "Clone",
  testParse: "Test Parse",
  clearFilters: "Clear Filters",
  discardChanges: "Discard Changes",
  continueEditing: "Continue Editing",

  // Table & List
  formatCode: "Format Code",
  formatName: "Format Name",
  formatType: "Format Type",
  type: "Type",
  priority: "Priority",
  defaultFormat: "Default Format",
  noDescription: "No description",
  totalFormats: "Total {{total}} formats",

  // Search & Filters
  searchByCodeNameDesc: "Search by code, name, or description...",

  // Form Labels
  createBarcodeFormat: "Create Barcode Format",
  editFormat: "Edit: {{code}}",
  unsavedChanges: "(Unsaved changes)",
  formatCodeRequired: "Format Code is required",
  formatNameRequired: "Format Name is required",
  formatTypeRequired: "Format Type is required",
  formatCodeCannotChange: "Format Code cannot be changed after creation",
  formatCodePlaceholder: "e.g., GS1_PHARMA_01",
  formatNamePlaceholder: "e.g., GS1-128 Pharmaceutical Barcode",
  selectFormatType: "Select format type",
  descriptionPlaceholder: "Describe the purpose and usage of this format...",

  // Tooltips
  formatCodeTooltip: "Unique identifier for this barcode format. Use uppercase letters, numbers, hyphens, and underscores only.",
  formatNameTooltip: "Human-readable name for this format",
  formatTypeTooltip: "The parsing strategy for this barcode format",
  descriptionTooltip: "Optional description for this format",
  priorityTooltip: "Higher priority formats are checked first during parsing. Valid range: 1-999",
  activeTooltip: "Only active formats are used for parsing",
  defaultFormatTooltip: "This format will be used as the default for parsing when no specific format is selected",

  // Tabs
  basicInformation: "Basic Information",
  fieldConfiguration: "Field Configuration",
  validationInventory: "Validation & Inventory",
  testPreview: "Test & Preview",

  // Format Types
  gs1_128: "GS1-128",
  gs1_datamatrix: "GS1 DataMatrix",
  gs1_qr: "GS1 QR Code",
  delimiterBased: "Delimiter-Based",
  fixedLength: "Fixed-Length",
  prefixBased: "Prefix-Based",
  json: "JSON",
  xml: "XML",
  customRegex: "Custom/Regex",

  // Format Type Descriptions
  gs1_128Desc: "GS1-128 barcode with Application Identifiers",
  gs1_datamatrixDesc: "2D DataMatrix barcode with GS1 encoding",
  gs1_qrDesc: "QR Code with GS1 encoding",
  delimiterBasedDesc: "Custom delimiter-separated format (e.g., pipe, comma)",
  fixedLengthDesc: "Position-based fixed-length format",
  prefixBasedDesc: "SAP-style prefix-based format",
  jsonDesc: "JSON-encoded barcode data",
  xmlDesc: "XML-encoded barcode data",
  customRegexDesc: "Custom format with regex pattern matching",

  // Field Types
  string: "String",
  integer: "Integer",
  decimal: "Decimal",
  date: "Date",
  datetime: "Date/Time",
  boolean: "Boolean",

  // Success Messages
  formatCreatedSuccess: "Format created successfully",
  formatUpdatedSuccess: "Format updated successfully",
  formatDeletedSuccess: "Format deleted successfully",
  formatClonedSuccess: "Format cloned successfully",

  // Error Messages
  failedToCreateFormat: "Failed to create format",
  failedToUpdateFormat: "Failed to update format",
  failedToDeleteFormat: "Failed to delete format",
  failedToCloneFormat: "Failed to clone format",
  atLeastOneFieldRequired: "At least one field must be defined",

  // Delete Confirmation
  deleteFormatTitle: "Delete Format",
  deleteFormatMessage: "Are you sure you want to delete the format \"{{code}}\"? This action cannot be undone.",

  // Unsaved Changes
  unsavedChangesTitle: "Unsaved Changes",
  unsavedChangesContent: "You have unsaved changes. Are you sure you want to discard them?",

  // Clone Modal
  cloneBarcodeFormat: "Clone Barcode Format",
  cloneFormatDesc: "Create a copy of \"{{code}}\" with all its configuration, fields, and rules. You can modify the clone independently after creation.",
  newFormatCode: "New Format Code",
  newFormatName: "New Format Name",
  formatCodeValidation: "Use uppercase letters, numbers, hyphens, and underscores only",
  maximum50Characters: "Maximum 50 characters",
  maximum100Characters: "Maximum 100 characters",
  cloneNote: "Note",
  cloneNoteDesc: "The cloned format will have the same priority as the source. Consider adjusting the priority after creation to avoid conflicts.",
  newFormatCodePlaceholder: "e.g., GS1_PHARMA_02",
  newFormatNamePlaceholder: "e.g., GS1-128 Pharmaceutical Barcode v2",
  sourceFormatHandleMissing: "Source format handle is missing",

  // Status
  all: "All",

  // Saving
  saving: "Saving...",

  // View
  view: "View",

  // Additional missing keys
  siteNotFound: "Site not found. Please select a site.",
  deleteConfirmationComingSoon: "Delete confirmation - Coming soon in Sprint 6",
  testParseModalComingSoon: "Test parse modal - Coming soon in Sprint 5",

  // =========================================   ACTIVITY =============================================
  activityAppTitle: "Activity Maintenance",
  activity: "Activity",
  activityIds: "Activity Id",
  activityGroup: "Activity Group",
  enabled: "Enabled",
  visibleInActivityManager: "Visible In Activity Manager",
  classOrProgram: "Class / Program",
  listOfMethod: "List Of Method",
  createActivity: "Create Activity",
  activityRules: "Activity Rules",
  activityHooks: "Activity Hooks",
  userArgument: "User Argument",
  sites: "Sites",
  "hookableMethod": "Hookable Method",
  hookPoint: "Hook Point",
  rules: "Rules",
  setting: "Setting",
  addRules: "Add Rules",
  addRule: "Add Rule",
  restoreDefault: "Restore Default",
  selectActivity: "Selelct Activity",
  ok: "OK",

  // ===============================================  Work Center =========================

  workCenterAppTitle: "Work Center Maintenance",
  workCenterCategory: "Work Center Category",
  defaultParentWorkCenter: "Default Parent Work Center",
  defaultWorkCenter: "Default Work Center",
  createWorkCenter: "Create Work Center",
  association: "Association",
  associateId: "Associate Id",
  defaultResource: "Default Resource",
  deleteWCMessage: "Are you sure you want to delete this work center ",
  disabled: "Disabled",
  closeMsg: "Are you sure you want to leave the page?",
  yes: "Yes",
  no: "No",
  select: "Select",
  confirmation: "Confirmation",
  selectAssociateId: "Select Associate Id",
  closePageMsg: "Are you sure you want to exit?",
  leavePage: "Leave Page",

  "headerTitle": "Shift Maintenance",
  "siteMaintenance": "Site Maintenance",
  "batchNo": "Batch No",
  "pod": "Pod",
  "site": "Site",
  "shift": "Shift",
  "pcu": "PCU",
  "itemBO": "Item",
  "routerBO": "Router",
  "qty": "Quantity",
  "quantity": "Quantity",
  "shopOrderBO": "Shop Order",
  "timeZone": "Time Zone",
  "local": "Local",
  "shopOrder": "Shop Order",
  "userHeaderTitle": "User Maintenance",
  "underDeliveryTolerance": "Under Delivery ",
  "overDeliveryTolerance": "Over Delivery ",
  "maximumDeliveryQty": "Maximum Delivery Qty",
  "minimumDeliveryQty": "Minimum Delivery Qty",
  "user": "User",
  "noOfCount": "Cycle Time",
  "shiftType": "Shift Type",
  "material": "Product Code",
  "cycleTime": "Cycle Time",
  "manufacturedTime": "Production Time",
  "createCycleTime": "Create Cycle Time",
  "materialVersion": "Product Version",
  "update": "Update",
  "shiftInterval": "Shift Interval",
  "calendarRules": "Calendar Rules",
  "calendarOverride": "Calendar Override",
  "createdOn": "Created On",
  "modifiedOn": "Modified On",
  "erpShift": "ERP Shift",
  "alertRow": "Do you want to proceed with the selected row?",
  "areYouSure": "Are you sure you want to delete this",
  "addBreak": "Add Break",
  "Status": "Status",
  "comment": "Comment",
  "newStatus": "New Status",
  "selectBy": "Select By",
  "validityShiftInfo": "Validity/Shift Information",
  "clockInOutInfo": "Clock-In/Out Information",
  "labourInfo": "Labour Information",
  "action": "Action",
  "day": "Day",
  "productionDay": "Production Day",
  "data": "Data",
  "dayClass": "Day Class",
  "search": "Search",
  "maintenance": "Maintenance",
  "certification": "Certification",
  "subStep": "Sub-Step",
  "activityHook": "Activity Hook",
  "operationType": "Operation Type",
  "resourceType": "Resource Type",
  "defaultOperation": "Default Operation",
  "addAsErpOperation": "Add as ERP Operation",
  "maxLoopCount": "Max Loop Count",
  "enter": "Enter",
  "employeeNumber": "Employee Number",
  "hireDate": "Hire Date",
  "erpUser": "ERP User",
  "firstName": "First Name",
  "lastName": "Last Name",
  "emailAddress": "Email Address",
  "erpPersonnelNumber": "ERP Personal Number",
  "userGroup": "User Group",
  "labourTracking": "Labour Tracking",
  "supervisor": "Supervisor",
  "labourRule": "Labour Rule",
  "bomType": "BOM Type",
  "plannedBom": "Planned BOM",
  "plannedRouting": "Planned Routing",
  "lcc": "LCC",
  "plannedWorkCenter": "Planned Work Center",
  "orderedQty": "Ordered Qty",
  "buildQty": "Build Qty",
  "erpUom": "ERP UOM",
  "plannedStart": "Planned Start",
  "plannedCompletion": "Planned Completion",
  "scheduledStart": "Scheduled Start",
  "scheduledEnd": "Scheduled End",
  "customerOrder": "Customer Order",
  "customer": "Customer",
  "orderType": "Order Type",
  "plannedMaterial": "Planned Material",
  "productionQuantities": "Production Quantities",
  "serialPCU": "Serial PCU",
  "enable": "Enable",
  "serialNumber": "Serial Number",
  "pcuNumber": "PCU Number",
  "pcuQuantity": "PCU Quantity",
  "state": "State",
  "defineDeliveryToleranceIn": "Delivery Tolerance In",
  "unlimited_over_delivery": "Unlimited Over Delivery",
  "bomMaintenance": "BOM Maintenance",
  "bomTemplate": "BOM Template",
  "component": "Component",
  "assemblyOperation": "Assembly Operation",
  "assemblyQuantity": "Assembly Quantity",
  "copyBom": "Copy BOM",
  "updateBom": "Update BOM",
  "assemblySequence": "Assembly Sequence",
  "componentType": "Component Type",
  "maxNc": "Max NC",
  "maxUsage": "Max Usage",
  "storageLocation": "Storage Location",
  "createBomComponent": "Create BOM Component",
  "createNewBom": "Create New BOM",
  "alternateComponentVersion": "Alternate Component Version",
  "designCost": "Design Cost",
  "assySequence": "Assembly Sequence",
  "componentVersion": "Component Version",
  "componentDescription": "Component Description",
  "assyQty": "Assembly Quantity",
  "assyOperation": "Assembly Operation",
  "assemblyDataTypeBo": "Assembly Data Type",
  "storageLocationBo": "Storage Location",
  "close": "Close",
  "availableActivities": "Available Activities",
  "assignedActivities": "Assigned Activities",
  "activities": "Activities",
  "activityGroupName": "Activity Group Name",
  "activityGroupMaintenance": "Activity Group Maintenance",
  "createActivityGroup": "Create Activity Group",
  "activityGroupDescription": "Activity Group Description",
  "copyActivityGroup": "Copy Activity Group",
  container: "Container",
  selectContainer: "Select Container",



  // ===============================   Next Number     ==============================
  "recipientName": "Recipient Name",
  "recipientId": "Recipient ID",
  "numbeType": "Number Type",
  "definedBy": "Defined By",
  "objectVersion": "Object Version",
  "containerInput": "Container Input",
  "prefix": "Prefix",
  "suffix": "Suffix",
  "numberBase": "Number Base",
  "doneQty": "Done Quantity",
  "releasedQty": "Released Quantity",
  "qtyInQueueOrWork": "Quantity in Queue",
  "scrappedQty": "Scrapped Quantity",
  "unreleasedQty": "Unreleased Quantity",
  "sequenceLength": "Sequence Length",
  "minSequence": "Min Sequence",
  "maxSequence": "Max Sequence",
  "warningThreshold": "Warning Threshold",
  "incrementBy": "Increment By",
  "currentSequence": "Current Sequence",
  "resetSequenceNumber": "Reset Sequence Number",
  "nextNumberActivity": "Next Number Activity",
  "createContinuousSfc": "Create Continuous PCU on Import",
  "commitNextNumberChangesImmediately": "Commit Next Number Changes Immediately",
  "sampleNextNumber": "Sample Next Number",
  "nextNumberAppTitle": "Next Number Maintenance",
  "parametersAndDescription": "Parameter And Description",
  "selectItemGroup": "Select Item Group",
  "selectDataType": "Select DataType",
  "selectBOM": "Select BOM",
  "selectItem": "Select Item",
  "retrieve": "Retrieve",
  "clear": "Clear",
  "createNextNumber": "Create Next Number",
  "deleteMsg": "Do you want to delete this next number?",
  "sl_no": "Sl No",
  "packet_id": "Packet ID",
  "packet_description": "Packet Description",
  "qty_consumed": "Qty Consumed",
  "total_packets": "Total Packets",
  "remaining_capacity": "Remaining Capacity",

  "cycleTitle": "Cycle Time Maintenance",

  // ====================== Operational Settings ========================
  operationalSettingAppTitle: "Operational Setting",
  "uomAbb": "Unit of Measure",
  "reset": "Reset",
  "name": "Name",


  "podMaintenance": "Pod Maintenance",
  "podName": "Pod Name",
  "createPodName": "Create Pod Name",
  "podLayout": "Pod Layout",
  "kafkaIntegration": "Kafka Integration",
  "kafkaId": "Kafka ID",
  "operationCanBeChanged": "Operation Can Be Changed",
  "resourceCanBeChanged": "Resource Can Be Changed",
  "showQuantity": "Show Quantity",
  "documentName": "Document Name",
  "sessionTimeout": "Session Timeout",
  "refreshRate": "Refresh Rate",
  "podType": "Pod Type",
  "copyPod": "Copy Pod",
  "updatePod": "Update Pod",
  "buttonId": "Button ID",
  "buttonLabel": "Button Label",
  "buttonType": "Button Type",
  "buttons": "Buttons",
  "listOptions": "List Options",
  "podSelections": "Pod Selections",
  "printers": "Printers",
  "home": "Home",
  "buttonSize": "Button Size",
  "imageIcon": "Image Icon",
  "hotKey": "Hot Key",
  "buttonLocation": "Button Location",
  "podSelection": "POD SELECTION",
  "activitySequence": "Activity Sequence",
  "pluginLocation": "Plugin Location",
  "clearsPcu": "Clear PCU",
  "fixed": "Fixed",
  "createNewPod": "Create New Pod",
  "panelLayout": "Panel Layout",
  "selectDefaultOperation": "Select Default Operation",
  "selectDefaultResource": "Select Default Resource",
  "selectDocumentName": "Select Document Name",
  "browseWorkList": "Browse Work List",
  "podWorkList": "POD Work List",
  "assembleList": "Assemble List",
  "dcCollectList": "DC Collect List",
  "toolList": "Tool List",
  "workInstructionList": "Work Instruction List",
  "dcEntryList": "DC Entry List",
  "subStepList": "Sub Step List",
  "mainInput": "Main Input",
  "mainInputHotKey": "Main Input Hot Key",
  "infoLine1": "Info Line 1",
  "infoLine2": "Info Line 2",
  "documentPrinter": "Document Printer",
  "labelPrinter": "Label Printer",
  "travelerPrinter": "Traveler Printer",
  "recommendedBuildQtyToReachOrderedQty": "Reach Ordered Qty",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "Reach Minimum Qty",
  "generalInfo": "General Information",
  "materialCode": "Material Code",
  "materialDescription": "Product Name",
  "purchaseOrderNumber": "Purchase Order Number",
  "grnNumber": "GRN Number",
  "supplierInfo": "Supplier Information",
  "supplierName": "Supplier Name",
  "supplierId": "Supplier ID",
  "invoiceNumber": "Invoice Number",
  "warehouseCode": "Warehouse Code",
  "storageBin": "Storage Bin",
  "deliveryInfo": "Delivery Information",
  "deliveryNumber": "Delivery Number",
  "deliveryType": "Delivery Type",
  "vehicleNumber": "Vehicle Number",
  "inwardDetails": "Inward Details",
  "receiptDateTime": "Receipt Date & Time",
  "gateDockNumber": "Gate Dock Number",
  "attachmentDocument": "Attachment Document",
  "attachment": "Attachment",
  "materialInwardManagement": "Material Inward Management",


  // ============================ Consumption and packing =====================
  "consumptionAndPackingAppTitle": "Consumption And Packing",

  "users": "Users",
  "userGroupMaintenance": "User Group Maintenance",
  "selectPod": "Select Pod",
  "availableUsers": "Available Users",
  "assignedUsers": "Assigned Users",
  "availableActivityGroups": "Available Activity Groups",
  "assignedActivityGroups": "Assigned Activity Groups",
  "pickListManagement": "Pick List Management",
  "pickListNo": "Pick List No",
  "orderNo": "Order No",
  "generate": "Generate",
  "itemCode": "Item Code",
  "itemDescription": "Item Description",
  "qtyOrdered": "Qty Ordered",
  "qtyPicked": "Qty Picked",
  "location": "Location",
  "warehouse": "Warehouse",
  "pick": "Pick",
  "updatePick": "Update Pick",
  "print": "Print",
  "selectOrder": "Select Order",
  "resourceMaintenance": "Resource Maintenance",
  "createResource": "Create Resource",
  "createList": "Create List",
  "opcTag": "OPC Tag",
  "processResource": "Process Resource",
  "erpEquipmentNumber": "ERP Equipment Number",
  "erpPlantNumber": "ERP Plant Number",
  "availableResource": "Available Resource",
  "assignedResource": "Assigned Resource",
  "tagName": "Tag Name",
  "tagUrl": "Tag URL",
  "identity": "Identity",
  "selectCertification": "Select Certification",
  "cycleTimeMaintenance": "Cycle Time Maintenance",
  "dataType": "Data Type",
  "selectRouting": "Select Routing",
  "manageAlternateComponents": "Manage Alternate Components",
  "manageParentComponents": "Manage Parent Components",
  "selectComponent": "Select Component",
  "selectAssemblyOperation": "Select Assembly Operation",
  "selectAssemblyDataType": "Select Assembly Data Type",
  "selectAlternateComponent": "Select Alternate Component",
  "selectOperation": "Select Operation",
  "selectMaterial": "Select Material",
  "uomCode": "UOM Code",
  "selectList": "Select List",
  "list": "List",
  "selectPrinters": "Select Printers",
  "parameter": "Parameter",
  "enterFullScreen": "Enter Full Screen",
  "exitFullScreen": "Exit Full Screen",
  "release": "Release",
  "shopOrderRelease": "Shop Order Release",
  "qtyToRelease": "Quantity to Release",
  "addToNewProcessLot": "Add to New Process Lot",
  "availableQtyToRelease": "Available Quantity to Release",
  "flowChart": "Flow Chart",
  "serialBatchNumber": "Serial Batch Number",
  "bnoQuantity": "BNO Quantity",
  "bno": "BNO",
  "erpPlantMaintenanceOrder": "ERP Plant Maintenance Order",
  "availableResourceTypes": "Available Resource Types",
  "assignedResourceTypes": "Assigned Resource Types",
  "copyResource": "Copy Resource",
  'productCode': 'Product Code',

  // ==========================LIST APP=========================================

  "allowOperatorToChangeColumnSequence": "Allow Operator To Change Column Sequence",
  "allowOperatorToSortRows": "Allow Operator To Sort Rows",
  "allowMultipleSelection": "Allow Multiple Selection",
  "showAllActiveSfcsToOperator": "Show All Active SFCs To Operator",
  "maximumNumberOfRow": "Maximum Number Of Row",
  "columnSequence": "Sequence",
  "columnName": "Column Name",
  "rowSortOrder": "Row Sort Order",
  "ShowDetails": "Show Details",
  "width": "Width",
  "ascending": "Ascending",
  "descending": "Descending",
  "copyList": "Copy List",
  "deleteConfirmation": "Delete Confirmation",
  "ListMaintenance": "List Maintenance",

  // ============================ Item Group =====================
  "itemGroupAppTitle": "Item Group Maintenance",
  "groupDescription": "Group Description",
  "unitPrice": "Unit Price",
  "groupMember": "Group Member",
  "createItemGroup": "Create Item Group",
  "itemGroupDeleteMessage": "Do you want to delete this item group",
  "availableItems": "Available Items",
  "assignedItems": "Assigned Items",
  "selectMethod": "Select Method",
  "method": "Method",
  "resourceTypeMaintenance": "Resource Type Maintenance",
  "resourceTypeDescription": "Resource Type Description",
  "resourceMemberList": "Resource Member List",
  "createResourceType": "Create Resource Type",
  "createUserGroup": "Create User Group",
  "customdataMaintenance": "Custom Data Maintenance",
  "data field": "Data Field",
  "field label": "Field Label",
  "required": "Required",
  "selectdataField": "Select Data Field",


  // ============================================== DATA FIELD ===========================================
  "dataField": "Data Field",
  "fieldLabel": "Field Label",
  "dataFieldAppTitle": "Data Field Maintenance",
  "maskGroup": "Mask Group",
  "preSaveActivity": "Pre-Save Activity",
  "isTrackable": "Is Trackable",
  "qmSelectedSet": "QM Selected Set",
  "isMrfRef": "Is MFR Ref",
  "browseIcon": "Browse Icon",
  "defaultLabel": "Default Label",
  "fieldValue": "Field Value",
  "labelValue": "Label Value",
  "api": "API",
  "parameters": "Parameters",
  "title": "Title",
  "editValues": "Edit Values",
  "createDataField": "Create Data Field",

  // ============================================== DATA TYPE ===========================================
  "dataTypeAppTitle": "Data Type Maintenance",
  "createDataType": "Create Data Type",
  "selectDataField": "Select Data Field",
  "listDetails": "List Details",

  "order": "Order",
  "componentToScan": "Component to Scan",
  "assembled": "Assembled",
  "assemble": "Assemble",
  "remaining": "Remaining",
  "dataAttribute": "Data Attribute",
  "returnToPod": "Return to POD",
  "confirmCreateDataField": "Data Field not found, want to create this data field",

  // ============================================== DATA COLLECTION ===========================================
  "dataCollectionAppTitle": "Data Collection Maintenance",
  "dataCollection": "Data Collection",
  "createDC": "Create Data Collection",
  "collectionType": "Collection Type",
  "collectionDataAt": "Collection Data At",
  "collectDataAt": "Collect Data At",
  "erpGroup": "ERP Group",
  "qmInspectionGroup": "QM Inspection Group",
  "passOrFailGroup": "Pass or Fail Group",
  "failOrRejectNumber": "Fail or Reject Number",
  "userAuthenticationRequired": "User Authentication Required",
  "frequency": "Frequency",
  "parameterName": "Parameter Name",
  "parameterDetails": "Parameter Details",
  "prompt": "Prompt",
  "allowMissingValues": "Allow Missing Values",
  "displayDataValues": "Display Data Values",
  "falseValue": "False Value",
  "trueValue": "True Value",
  "formula": "Formula",
  "minValue": "Minimum Value",
  "maxValue": "Maximum Value",
  "targetValue": "Target Value",
  "softLimitCheckOnMinOrMaxValue": "Soft Limit Check on Min or Max Value",
  "overrideMinOrMax": "Override Min or Max",
  "autoLogNconMinOrMaxOverride": "Auto Log on Min or Max Override",
  "ncCode": "NC Code",
  "mask": "Mask",
  "unitOfMeasure": "Unit of Measure",
  "requiredDataEntries": "Required Data Entries",
  "optionalDataEntries": "Optional Data Entries",
  "attachmentDetails": "Attachment Details",
  "itemVersion": "Item Version",
  "attachmentList": "Attachment List",

  // ============================================= DC PLUGIN ===========================================
  "parameterList": "Parameter List",
  "showDetails": "Show Details",
  "collectData": "Collect Data",
  "saveDraft": "Save Draft",
  "submit": "Submit",
  "dataFieldList": "Data Field List",
  "collectedDCParameterList": "Collected DC Parameter List",
  "returnToDCList": "Return To DC List",
  "range": "Range",
  "dateTime": "DateTime",
  "collectionMethod": "Collection Method",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "Text Instruction",
  "urlInstruction": "URL Instruction",
  "instructionType": "Instruction Type",
  "WorkInstruction_Description": "Description",
  "WorkInstructionID_Revision": "Work Instruction / Revision",
  "Operation_StepId": "Operation StepId",
  "StepId": "Step Id",


  "workInstructionMaintenance": "Work Instruction Maintenance",
  "workInstruction": "Work Instruction",
  "createWorkInstruction": "Create Work Instruction",
  "alwaysShowInNewWindow": "Always Show in New Window",
  "logViewing": "Log Viewing",
  "changeAlert": "Change Alert",
  "erpWi": "ERP Work Instruction",
  "text": "Text",
  "url": "URL",
  "file": "File",
  // ============================================== Change Machine Status ===========================================
  "machineStatusChange": "Machine Status Change",

  // ============================================== Scrap Unscrap ===========================================
  "pcu/shopOrder/processLot": "PCU / Shop Order / Process Lot",
  "comments": "Comments",
  "scrap": "Scrap",
  "unscrap": "Unscrap",
  "Scrap": "Scrap",
  "Unscrap": "Unscrap",
  "scrapUnscrapTitle": "Scrap Unscrap",

  // ============================================== User Maintenance ===========================================
  "confirmPassword": "Confirm Password",
  "password": "Password",
  "selectSites": "Select Sites",
  "workflowIntegrationMaintenance": "Workflow Integration Maintenance",
  "workflowIntegration": "Workflow Integration",
  "createWorkflowIntegration": "Create Workflow Integration",
  "identifier": "Identifier",
  "messageId": "Message ID",
  "processBy": "Process By",
  "transformationType": "Transformation Type",
  "preprocessJolt": "Pre-Process Jolt",
  "preprocessApi": "Pre-Process API",
  "serviceApi": "Service API",
  "expectedSplits": "Expected Splits",
  "postProcessJolt": "Post-Process Jolt",
  "postProcessApi": "Post-Process API",
  "passHandler": "Pass Handler",
  "failHandler": "Fail Handler",
  "processTransformation": "Process Transformation",

  // ============================================== Jolt Spec ===========================================
  "specName": "Spec Name",
  "specNamePlaceholder": "Enter spec name",
  "specNameRequired": "Please input spec name!",
  "typePlaceholder": "Select type",
  "typeRequired": "Please select a type!",
  "joltSpec": "Jolt Spec",
  "joltSpecPlaceholder": "Enter Jolt specification",
  "xsltSpec": "XSLT Spec",
  "xsltSpecPlaceholder": "Enter XSLT specification",
  "encodeXsltSpec": "Encode XSLT Spec",
  "encodeXsltSpecPlaceholder": "Enter encoded XSLT specification",
  "jsonAtaSpec": "Jsonata Spec",
  "jsonAtaPlaceholder": "Enter JsonAta specification",
  "encodedJsonAtaSpec": "Encoded JsonAta Spec",
  "encodedJsonAtaSpecPlaceholder": "Enter encoded JsonAta specification",

  "joltAppTitle": "Jolt Spec Maintenance",
  "createSpec": "Create Spec",
  "encode": "Encode",
  "decode": "Decode",
  "spec": "Spec",
  "decodeXsltSpec": "Decoded XSLT Specification",
  "decodeJsonAtaSpec": "Decoded JsonAta Specification",

  "show": "Show",
  "joltSpecification": "Jolt Specification",
  "jsonataSpecification": "Jsonata Specification",
  "xsltSpecification": "Xslt Specification",
  "eventIntervalSeconds": "Event Interval Seconds",
  "cronExpression": "Cron Expression",
  "edit": "Edit",
  "runJob": "Run Job",
  "stopScheduler": "Stop Scheduler",

  "apiToProcess": "API to Process",
  "selectPreProcessJolt": "Select Pre-Process Jolt",
  "selectPostProcessJolt": "Select Post-Process Jolt",
  "selectPreProcessXSLT": "Select Pre-Process XSLT",
  "processJoltXslt": "Process Jolt XSLT",
  "splitConfigurations": "Split Configurations",
  "splitIdentifier": "Split Identifier",

  "conditional": "Conditional",
  "parallel": "Parallel",
  "anyOrder": "Any Order",
  "orderNumber": "Order Number",
  "recipeVersion": "Recipe Version",
  "recipeNo": "Recipe Number",
  "recipeDescription": "Description",
  "targetQuantity": "Target Quantity",
  "startDate": "Start Date",
  "finishDate": "Finish Date",
  "schedFinTime": "Scheduled Finish Time",
  "schedStartTime": "Scheduled Start Time",
  "selectRecipeNo": "Select Recipe Number",
  "batchNumber": "Batch Number",
  "batchNumberQuantity": "Batch Number Quantity",

  // ============================================== Process Order Plugin ===========================================
  "complete": "Complete",
  "start": "Start",


  // ============================================== NC Group ===========================================
  "ncGroup": "NC Group",
  "ncGroups": "NC Groups",
  "ncGroupAppTitle": "NC Group Maintenance",
  "availableNcGroups": "Available NC Groups",
  "assignedNcGroups": "Assigned NC Groups",
  "ncGroupFilterPriority": "NC Group Filter Priority",
  "validAtAllOperations": "Valid At All Operations",
  "parameterBo": "Parameter",
  "operationBO": "Operation",
  "dcGroupBO": "DC Group",
  "pcuBO": "PCU",
  "testDateTime": "Test Date Time",
  "dcGroupDescription": "DC Group Description",
  "subStepID": "Sub Step ID",
  "measureStatus": "Measure Status",
  "measureType": "Measure Type",
  "highLimit": "High Limit",
  "lowLimit": "Low Limit",
  "expected": "Expected",
  "actualNum": "Actual Number",
  "dcComment": "DC Comment",
  "usedLimitSeq": "Used Limit Sequence",
  "elapsedTime": "Elapsed Time",
  "originalActual": "Original Actual",
  "originalDcComment": "Original DC Comment",
  "originalTestDateTime": "Original Test Date Time",
  "edited": "Edited",
  "editedUserBO": "Edited User",
  "editedDateTime": "Edited Date Time",
  "internalMeasureID": "Internal Measure ID",
  "routingBO": "Routing",
  "stepID": "Step ID",
  "userBO": "User",
  "overrideUserBO": "Override User",
  "dcGroupVersion": "DC Group Version",
  "erpSent": "ERP Sent",
  "qmaccepted": "QM Accepted",
  "detailInformation": "Detail Information",
  "detail": "Detail",
  "dcGroup": "DC Group",
  "viewPdf": "View PDF",
  "createNCGroup": "Create NC Group",
  "ncCodeDPMOCategory": "NC Code DPMO Category",
  "operationList": "Operation List",
  "ncGroupDeleteMessage": "Do you want to delete this NC Group",
  "availableNCCodes": "Available NC Codes",
  "assignNCCodes": "Assign NC Codes",
  "assignedNC": "Assigned NC",
  "availableNC": "Available NC",

  "logNc": "Log NC",
  "done": "Done",

  "NcCodeMaintenance": "NC Code Maintenance",
  "NC Code": "NC Code",
  "operationGroups": "Operation Groups",
  "dispositionRoutings": "Disposition Routings",
  "NC Groups": "NC Groups",
  "secondaries": "Secondaries",
  "createNcCode": "Create NC Code",
  "assignNCtoComponent": "Assign NC to Component",
  "ncCategory": "NC Category",
  "dpmoCategory": "DPMO Category",
  "ncDatatype": "NC Datatype",
  "collectRequiredNCDataonNC": "Collect Required NC Data on NC",
  "ncPriority": "NC Priority",
  "maximumNCLimit": "Maximum NC Limit",
  "ncSeverity": "NC Severity",
  "secondaryCodeSpecialInstruction": "Secondary Code Special Instruction",
  "canBePrimaryCode": "Can be Primary Code",
  "closureRequired": "Closure Required",
  "autoClosePrimaryNC": "Auto Close Primary NC",
  "autoCloseIncident": "Auto Close Incident",
  "secondaryRequiredForClosure": "Secondary Required for Closure",
  "erpQNCode": "ERP QN Code",
  "erpCatalog": "ERP Catalog",
  "erpCodeGroup": "ERP Code Group",
  "erpCode": "ERP Code",
  "oeeQualityKPIRelevant": "OEE Quality KPI Relevant",
  "selectNcDatatype": "Select NC Datatype",
  "validOperations": "Valid Operations",
  "dispositionGroups": "Disposition Groups",
  "availableRouting": "Available Routing",
  "assignedRouting": "Assigned Routing",
  "availableSecondaries": "Available Secondaries",
  "assignedSecondaries": "Assigned Secondaries",
  "copyNcCode": "Copy NC Code",
  "toolNumberMaintenance": "Tool Number Maintenance",
  "toolNumber": "Tool Number",
  "toolGroup": "Tool Group",
  "qtyAvailable": "Quantity Available",
  "erpPlanMaintenanceOrder": "ERP Plan Maintenance Order",
  "toolQty": "Tool Quantity",
  "createToolNumber": "Create Tool Number",
  "calibration": "Calibration",
  "measurementPoints": "Measurement Points",
  "measurementPoint": "Measurement Point",
  "calibrationType": "Calibration Type",
  "calibrationPeriod": "Calibration Period",
  "calibrationCount": "Calibration Count",
  "maximumCalibrationCount": "Maximum Calibration Count",
  "expirationDate": "Expiration Date",
  "displayClosedNc": "Display Closed NC",
  "selectRoute": "Select Route",
  "customOrder": "Custom Order",
  "createToolGroup": "Create Tool Group",
  "timeBased": "Time Based",
  "quantityRequired": "Quantity Required",
  "trackingControl": "Tracking Control",
  "toolGroupMaintenance": "Tool Group Maintenance",
  "listConfiguration": "List Configuration",
  "multiProcessOrderRelease": "Multi Process Order Release",
  "multiProcessOrder": "Multi Process Order",
  "mrpController": "MRP Controller",
  "productionScheduler": "Production Scheduler",
  "reservationNumber": "Reservation Number",
  "productionStartDate": "Production Start Date",
  "productionFinishDate": "Production Finish Date",
  "actualStartDate": "Actual Start Date",
  "actualFinishDate": "Actual Finish Date",
  "inUse": "In Use",
  "measuredUom": "Measured Uom",
  "entryPhase": "Entry Phase",
  "exitPhase": "Exit Phase",
  "entryOperation": "Entry Operation",
  "lastOperationAtPhase": "Last Operation At Phase",
  "nextPhase": "Next Phase",

  "accept": "Accept",
  "reject": "Reject",
  "partial": "Partial",
  "skip": "Skip",
  "buyOff": "Buy Off",
  "username": "User Name",
  "userAuthentication": "User Authentication",
  "login": "Login",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "Certification Maintenance",
  "certifications": "Certifications",
  "createCertification": "Create Certification",
  "durationType": "Duration Type",
  "maxNumberOfExtensions": "Max Number of Extensions",
  "maxExtensionDuration": "Max Extension Duration",
  "assignment": "Assignment",
  "availableUserGroups": "Available User Groups",
  "assignedUserGroups": "Assigned User Groups",
  "measurementpoints": "Measurement Points",
  "copyCertification": "Copy Certification",
  // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "Line Clearance Maintenance",
  "lineClearance": "Line Clearance",
  "templateName": "Template Name",
  "clearanceTimeLimit": "Clearance Time Limit",
  "maxPendingTasks": "Max Pending Tasks",
  "clearanceReminderInterval": "Clearance Reminder Interval",
  "notifyOnCompletion": "Notify On Completion",
  "enablePhotoEvidence": "Enable Photo Evidence",
  "associated": "Associated",
  "workcenterId": "Workcenter ID",
  "resourceName": "Resource Name",
  "createLineClearance": "Create Line Clearance",
  "taskid": "Task ID",
  "taskname": "Task Name",
  "mandatory": "Mandatory",
  "evidencerequired": "Evidence Required",
  "userRoles": "User Roles",
  "userid": "User ID",
  "permissions": "Permissions",
  "selectUser": "Select User",

  "activityId": "Activity Id",
  "selectPcu": "Select Pcu",
  "selectBatchNo": "Select Batch No",
  "createPodMaintenance": "Create Pod Maintenance",
  "reloadWorkList": "Reload Work List",
  "reloadResource": "Reload Resource",
  "settings": "Settings",
  "layout": "Layout",
  "PCUOrBatchNumberBrowseActivity": "PCU Or Batch Number Browse Activity",
  "PodWorkListActivity": "Pod Work List Activity",
  "ButtonActivityInWork": "Button Activity in Work",
  "ButtonActivityInQueue": "Button Activity in Queue",
  "OnTabOutOfOperation": "On Tab Out of Operation",
  "OnTabOutOfWorkcenter": "On Tab Out of Workcenter",
  "OnTabOutOfResource": "On Tab Out of Resource",
  "UpdateFieldsToSession": "Update Fields To Session",
  "panel": "Panel",
  "defaultPlugin": "Default Plugin",
  "otherPlugin": "Other Plugin",
  "scrapQuantity": "Scrap Quantity",
  "subPod": "Sub Pod",
  "podCategory": "Pod Category",
  "buttonActivityInQueue": "Button Activity In Queue",
  "buttonActivityInWork": "Button Activity In Work",
  "activityDescription": "Activity Description",
  "workListPanel": "Work List Panel",
  "uomConversion": "UOM Conversion",
  "conversion": "Conversion",
  "materialCountConversion": "Material Count Conversion",
  "convertUom": "Convert UOM",
  "baseUnit": "Base Unit",
  "conversionUnit": "Conversion Unit",
  "conversionFactor": "Conversion Factor",
  "trackOee": "Track OEE",
  "conversionDeleteMessage": "Do you want to delete this conversion?",
  "baseAmt": "Base Amount",
  "convertionItem": "Convertion Item",
  "areYouSureDeleteThisSplit": "Are you sure you want to delete this split?",
  "attach": "Attach",
  "filePreview": "File Preview",
  "change": "Change",
  "preview": "Preview",
  "defaultPhaseId": "Default Phase ID",
  "reloadSiteConfirmation": "Are you sure you want to reload site?",
  "phaseCanBeChanged": "Phase Can Be Changed",
  "showResource": "Show Resource",
  "showOperation": "Show Operation",
  "showPhase": "Show Phase",
  "auditLogReport": "Audit Log Report",
  "dataCollectionReport": "Data Collection Report",
  "dataCollectionGraph": "Data Collection Graph",
  "selectCategory": "Select Category",
  "currentSetting": "Current Setting",
  "date/time": "Date/Time",
  "changeType": "Change Type",
  "dateRange": "Date Range",
  "time": "Time",
  "topicConfiguration": "Topic Configuration",
  "createTopicConfiguration": "Create Topic Configuration",
  "topicName": "Topic Name",
  "apiUrl": "API URL",
  "taskDescription": "Task Description",
  "evidence": "Evidence",
  "startedDateTime": "Started Date Time",
  "completedDateTime": "Completed Date Time",
  "reason": "Reason",
  "approved": "Approved",
  "approvedDateTime": "Approved Date Time",
  "approvedBy": "Approved By",
  "rejectedDateTime": "Rejected Date Time",
  "rejectedBy": "Rejected By",
  "updatedDateTime": "Updated Date Time",
  "updatedBy": "Updated By",
  "startedBy": "Started By",
  "completedBy": "Completed By",
  "taskName": "Task Name",
  "isMandatory": "Is Mandatory",
  "evidenceRequired": "Evidence Required",
  "theme": "Theme",
  "cycleTime(sec)": "Cycle Time (sec)",

  "shiftStart": "Shift Start",
  "shiftEnd": "Shift End",
  "shiftAvailableTime": "Shift Available Time",
  "totalBreakHours": "Total Break Hours",
  "createdDatetime": "Created Datetime",
  "updatedDatetime": "Updated Datetime",
  "createdBy": "Created By",
  "eventData": "Event Data",
  "plant": "Plant",
  "eventType": "Event Type",
  "buyOffAction": "Buy Off Action",
  "history": "History",
  "endDate": "End Date",
  "selectSite": "Select Site",
  "downtimeType": "Downtime Type",
  "selectStatus": "Select Status",
  "selectNewStatus": "Select New Status",
  "selectBatchNumber": "Select Batch Number",
  "selectOrderNumber": "Select Order Number",
  "batchStepStatus": "Batch Step Status",
  "PhaseId": "Phase Id",
  "InQueueQty": "In Queue Qty",
  "InWorkQty": "In Work Qty",
  "CompleteQty": "Complete Qty",
  "ScrapQty": "Scrap Qty",
  "batchStartedTime": "Batch Started Time",
  "batchCompletedTime": "Batch Completed Time",
  "level": "Level",
  "message": "Message",
  "approval": "Approval",

  "activityHookId": "Activity Hook ID",
  "targetClass": "Target Class",
  "targetMethod": "Target Method",
  "hookType": "Hook Type",
  "hookClass": "Hook Class",
  "hookMethod": "Hook Method",
  "executionMode": "Execution Mode",

  "hookAppTitle": "Activity Hook Maintenance",
  "createHook": "Create Hook",
  "hook": "Hook",
  "activityHookDeleteMessage": "Do you want to delete this Activity Hook",
  "logo": "Logo",
  "background": "Background",
  "color": "Color",
  "lineColor": "Line Color",

  "plannedCycleTime": "Planned Cycle Time",
  "actualCycleTime": "Actual Cycle Time",
  "totalBreakInMinutes": "Total Break (min)",


  "serviceExtension": "Service Extension",
  "createServiceExtension": "Create Service Extension",
  "createExtension": "Create Extension",
  "serviceExtensionAppTitle": "Service Extension Maintenance",
  "selectResourceType": "Select Resource Type",
  "executionPointId": "Execution Point ID",
  "extensionDeleteMessage": "Do you want to delete this extension",
  "executionPoint": "Execution Point",
  "extensionActivity": "Extension Activity",
  "MaterialDescription": "Material Description",
  "releaseTime": "Release Time",
  "unitOfMeasurement": "Unit Of Measurement",
  "releaseOrder": "Release Order",
  "createdDateTime": "Created Date Time",
  "releaseQty": "Release Qty",
  "productionTime": "Production Time",
  "downloadDate": "Download Date",
  "productName": "Product Name",
  "batchStatus": "Batch Status",


  "createConfiguration": "Create Configuration",
  "apiConfiguration": "API Configuration",
  "storedProcedure": "Stored Procedure",
  "httpMethod": "HTTP Method",
  "inputParameters": "Input Parameters",
  "outputStructure": "Output Structure",
  "apiName": "API Name",
  "deleteApiConfigMessage": "Do you want to delete this configuration",
  "apiConfigMaintenance": "API Configuration Maintenance",
  "configuration": "Configuration",

  "shiftId": "Shift Id",
  "selectShift": "Select Shift",

  "approvalWorkFLowDetails": "Approval Workflow Details",
  "approvalLevelConfiguration": "Approval Level Configuration",
  "advancedConfiguration": "Advanced Configuration",
  "userRole": "User Role",
  "finalApproval": "Final Approval",
  "approvalWorkFlowConfiguration": "Approval Workflow Configuration",
  "workflow": "Workflow",
  "createApprovalWorkflowConfiguration": "Create Approval Workflow Configuration",
  "reviewDate": "Review Date",

  "productGroup": "Product Group",
  "selectProductGroup": "Select Product Group",
  "startSfcBatch": "Batch Started",
  "signoffSfcBatch": "Batch Signoff",
  "ScrapSFC": "Scrap PCU",
  "machineScrapSfcBatch": "Machine Scrap Batch",
  "UNSCHEDULED_DOWN": "Unplanned Downtime",
  "SCHEDULED_DOWN": "Planned Downtime",
  "PRODUCTION": "Production",
  "completeLineclearanceBatch": "Complete Line Clearance Batch",
  "ApprovBuyoff Approved": "Approved",
  "doneSfcBatch": "Done Batch",
  "machineDoneSfcBatch": "Machine Done Batch",
  "completeSfcBatch": "Complete Batch",
  "machineCompleteSfcBatch": "Machine Complete Batch",
  "A": "Approved QA",
  "Buyoff Approved": "QA Approved",
  "monthlyPlan": "Monthly Plan",
  "productionVersion": "Production Version",


  "attachmentType": "Attachment Type",
  "attachedTo": "Attached To",
  "attachedStatus": "Attachment Status",
  "default": "Default",
  "userRoleConfiguration": "User Role Configuration",

  "workflowId": "Workflow Id",
  "workflowName": "Workflow Name",
  "entityValue": "Entity Value",
  "appliesTo": "Applies To",
  "reference": "Reference",
  "workFlowConfiguration": "Work Flow Configuration",

  "templateId": "Template Id",
  "workFlowDefinition": "Workflow Definition",
  "createWorkFlowDefinition": "Create Workflow Definition",
  "workflowStatusMaster": 'Workflow Status Master',
  "editableFields": 'Editable Fields',
  'isEnd': 'Is End',
  "mainForm": "Main Form",
  "generalInstructions": "General Instructions",
  "ccps": "Critical Control Points",
  "stageInstructions": "Stage Instructions",

  'baseQty': 'Base Quantity',

  "documentLinkPlugin": "Document Link Plugin",
  "documentLinks ": "Document Links ",
  "docType": "Doc Type",
  "annexureCount": "Annexure Count",
  "mainDocument": "Main Document",
  "annexures": "Annexures",
  "selectWorkflowReference": "Select Workflow Reference",
  "templateReference": "Template Reference",
  "selectTemplateReference": "Select Template Reference",
  "annexure": "Annexure",
  "workflowReference": "Workflow Reference",
  "addAnnexure": "Add Annexure",
  "copyDocumentLink": "Copy Document Link",
  "Annexure Count": "Annexure Count",
  "Doc Type": "Doc Type",
  "Item Group": "Item Group",
  "Template Name": "Template Name",
  "Workflow ID": "Workflow ID",
  "Workflow Name": "Workflow Name",
  "numberOfAnnexures": "Number of Annexures",
  "noDocumentsFound": "No Documents Found",
  "pleaseSelectTheDocumentType": "Please Select The Document Type",
  "annexureCountIsRequired": "Annexure count is required",
  "pleaseFillInTheFollowingRequiredFields": "Please fill in the following required fields",
  "createDocumentLink": "Create Document Link",
  "documentLinkCopiedSuccessfully": "Document link copied successfully",
  "documentLinkApp": "Document Link App",
  "documentLinkDeletedSuccessfully": "Document link deleted successfully",
  "deleteFailed": "Delete failed",
  "createNewPhase": "Create New Phase",
  "phaseConfiguration": "Phase Configuration",
  "operations": "Operations",
  "triggeredPhase": "Triggered Phase",
  "searchOperations": "Search Operations",
  "back": "Back",
  "validate": "Validate",
  "relayout": "Relayout",
  "createPhase": "Create Phase",
  "editPhaseId": "Edit Phase ID",
  "savePhase": "Save Phase",
  "procedureMaintenance": "Procedure Maintenance",
  "searchProcedureId": "Search Procedure ID",
  "procedureId": "Procedure ID",
  "procedureName": "Procedure Name",
  "procedureConfiguration": "Procedure Configuration",
  "effectiveFrom": "Effective From",
  "effectiveTo": "Effective To",
  "nodeDetails": "Node Details",
  "operationDetails": "Operation Details",
  "basicDetails": "Basic Details",
  "sequenceNumber": "Sequence Number",
  "operationName": "Operation Name",
  "timing": "Timing",
  "expectedDurationMin": "Expected Duration (min)",
  "durationMin": "Duration (min)",
  "actualDurationMin": "Actual Duration (min)",
  "flags": "Flags",
  "critical": "Critical",
  "optional": "Optional",
  "finalOperation": "Final Operation",
  "operationConnections": "Operation Connections",
  "previousOperation": "Previous Operation",
  "nextOperation": "Next Operation",
  "completionCriteria": "Completion Criteria",
  "dcVersion": "DC Version",
  "wiVersion": "WI Version",
  "procedureVersion": "Procedure Version",
  "wfVersion": "WF Version",
  "previousNodes": "Previous Nodes",
  "nextNodes": "Next Nodes",
  "entryNode": "Entry Node",
  "finalNode": "Final Node",
  "multiDimensionalDataCollection": "Multi Dimensional Data Collection",
  "dataCollectionName": "Data Collection Name",
  "createDataCollection": "Create Data Collection",
  "editDataCollection": "Edit Data Collection",
  "attachmentPoint": "Attachment Point",
  "dataCollectionGroups": "Data Collection Groups",
  "basicConfiguration": "Basic Configuration",
  "groupName": "Group Name",
  "layoutType": "Layout Type",
  "requiredGroup": "Required Group",
  "repeatableRows": "Repeatable Rows",
  "tableRowNumber": "Table Row Number",
  "tablePreview": "Table Preview",
  "addColumn": "Add Column",
  "label": "Label",
  "defaultValue": "Default Value",
  "readOnly": "Read Only",
  "prefillingRows": "Prefilling Rows",
  "validationRules": "Validation Rules",
  "saveGroup": "Save Group",
  "phaseAttachments": "Phase Attachments",
  "attachments": "Attachments",
  "createProcedure": "Create Procedure",
  "saveProcedure": "Save Procedure",
  "createNewProcedure": "Create New Procedure",
  "editProcedure": "Edit Procedure",
  "materialConsumption": "Material Consumption",
  "attachmentPoints": "Attachment Points",
  "cloneDataCollection": "Clone Data Collection",
  "deleteDataCollection": "Delete Data Collection",
  "areYouSureYouWantToDeleteThisDataCollection": "Are you sure you want to delete this data collection?",
  "column": "Column",
  "field": "Field",
  "table": "Table",
  "form": "Form",
  "unitofMeasure": "Unit of Measure",
  "targetBand": "Target Band",
  "options": "Options",
  "editPhase": "Edit Phase",

  // Recipe Enhancements

  "product": "Product",
  "usageCount": "Usage Count",
  "lastUsedDate": "Last Used Date",
  "duplicate": "Duplicate",
  "import": "Import",
  "export": "Export",
  "searchRecipes": "Search recipes...",
  "statusFilter": "Status Filter",
  "draft": "Draft",
  "total": "Total",
  "recipes": "Recipes",
  "newRecipe": "New Recipe",
  "headerTab": "Header",
  "ingredientsTab": "Ingredients",
  "phasesAndOperations": "Phases & Operations",
  "yieldAndProducts": "Yield & Products",
  "referenceLinks": "Reference Links",
  "yieldAndProductsComingSoon": "Yield & Products - Coming Soon",
  "referenceLinksComingSoon": "Reference Links - Coming Soon",
  "productionParameters": "Production Parameters",
  "bmrHeaders": "BMR Headers",
  "recipeNameLabel": "Recipe Name",
  "versionLabel": "Version",
  "currentVersionLabel": "Current Version",
  "statusLabel": "Status",
  "workCenterIdLabel": "Work Center ID",
  "processTypeLabel": "Process Type",
  "activeStatusLabel": "Active Status",
  "recipeDescriptionLabel": "Recipe Description",
  "batchSizeLabel": "Batch Size",
  "batchUomLabel": "Batch UOM",
  "expectedCycleTimeLabel": "Expected Cycle Time",
  "actualCycleTimeLabel": "Actual Cycle Time",
  "scalingTypeLabel": "Scaling Type",
  "minBatchSizeLabel": "Min Batch Size",
  "maxBatchSizeLabel": "Max Batch Size",
  "scalingFactorLabel": "Scaling Factor",
  "companyNameLabel": "Company Name",
  "documentTitleLabel": "Document Title",
  "documentNoLabel": "Document No",
  "marketLabel": "Market",
  "standardBatchSizeLabel": "Standard Batch Size",
  "productNameLabel": "Product Name",
  "effectiveDateLabel": "Effective Date",
  "expiryDateLabel": "Expiration Date",
  "shelfLifeLabel": "Shelf Life",
  "manufacturingLicenseLabel": "Manufacturing License",
  "recipeNamePlaceholder": "Enter recipe name",
  "versionPlaceholder": "1.0",
  "statusPlaceholder": "Select status",
  "workCenterIdPlaceholder": "Enter work center ID",
  "processTypePlaceholder": "Select process type",
  "recipeDescriptionPlaceholder": "Enter recipe description",
  "workCenterIdRequired": "Please enter work center ID",
  "recipeDescriptionRequired": "Please enter recipe description",
  "batchSizePlaceholder": "Enter batch size",
  "batchUomPlaceholder": "Select UOM",
  "expectedCycleTimePlaceholder": "e.g., 48h",
  "actualCycleTimePlaceholder": "e.g., 45h",
  "scalingTypePlaceholder": "Select scaling type",
  "minBatchSizePlaceholder": "Min size",
  "maxBatchSizePlaceholder": "Max size",
  "scalingFactorPlaceholder": "1.0",
  "companyNamePlaceholder": "Enter company name",
  "documentTitlePlaceholder": "Batch Manufacturing Record",
  "documentNoPlaceholder": "Enter document number",
  "marketPlaceholder": "Enter market",
  "standardBatchSizePlaceholder": "Enter standard batch size",
  "productNamePlaceholder": "Enter product name",
  "shelfLifePlaceholder": "e.g., 3 Years",
  "manufacturingLicensePlaceholder": "Enter license number",
  "recipeNameRequired": "Please enter recipe name",
  "versionRequired": "Please enter version",
  "statusRequired": "Please select status",
  "processTypeRequired": "Please select process type",
  "batchSizeRequired": "Please enter batch size",
  "batchUomRequired": "Please select UOM",
  "expectedCycleTimeRequired": "Please enter expected cycle time",
  "scalingTypeRequired": "Please select scaling type",
  "minBatchSizeRequired": "Please enter min batch size",
  "maxBatchSizeRequired": "Please enter max batch size",
  "scalingFactorRequired": "Please enter scaling factor",
  "companyNameRequired": "Please enter company name",
  "documentTitleRequired": "Please enter document title",
  "documentNoRequired": "Please enter document number",
  "marketRequired": "Please enter market",
  "standardBatchSizeRequired": "Please enter standard batch size",
  "productNameRequired": "Please enter product name",
  "effectiveDateRequired": "Please select effective date",
  "expiryDateRequired": "Please select expiration date",
  "shelfLifeRequired": "Please enter shelf life",
  "manufacturingLicenseRequired": "Please enter license number",
  "batchOption": "Batch",
  "continuousOption": "Continuous",
  "semiContinuousOption": "Semi-Continuous",
  "underReview": "Under Review",
  "linearOption": "Linear",
  "nonLinearOption": "Non-Linear",
  "ingredientRemovedSuccess": "Ingredient removed successfully",
  "ingredientAddedSuccess": "Ingredient added successfully",
  "ingredientUpdatedSuccess": "Ingredient updated successfully",
  "codeLabel": "Code",
  "deleteIngredientTitle": "Delete ingredient?",
  "deleteIngredientDescription": "Are you sure you want to delete this ingredient?",
  "subtotal": "Subtotal",
  "itemsLabel": "items",
  "totalQuantity": "Total Qty",
  "quantityUnit": "kg",
  "totalPercentage": "Total %",
  "totalIngredients": "Total Ingredients",
  "overallTotal": "Overall Total",
  "addNonBom": "Add Non BOM",
  "sequenceShort": "Seq",
  "ingredientNameColumn": "Ingredient Name",
  "percentageColumn": "Percentage",
  "quantityColumn": "Quantity",
  "uomColumn": "UOM",

  "companyDocumentInfo": "Company & Document Information",
  "productManufacturingInfo": "Product & Manufacturing Information",
  "actualBatchSizeLabel": "Actual Batch Size",
  "actualBatchSizeRequired": "Please enter actual batch size",
  "actualBatchSizePlaceholder": "Enter actual batch size",
  "supersedesDocumentNoAndDateLabel": "Supersedes Doc No & Date",
  "supersedesDocumentNoAndDateRequired": "Please enter supersedes document number and date",
  "supersedesDocumentNoAndDatePlaceholder": "e.g., BMR/3003687/1157/01-00 & 07/08/2020",
  "cmlLabel": "CML",
  "cmlRequired": "Please enter CML",
  "cmlPlaceholder": "e.g., All Kind",
  "batchNoLabel": "Batch No",
  "batchNoRequired": "Please enter batch number",
  "batchNoPlaceholder": "To be assigned per batch",
  "semiFinishedProductCodeLabel": "Semi-Finished Product Code",
  "semiFinishedProductCodeRequired": "Please enter semi-finished product code",
  "semiFinishedProductCodePlaceholder": "e.g., 3003687/01",
  "mfrRefLabel": "MFR Reference",
  "mfrRefRequired": "Please enter MFR reference",
  "mfrRefPlaceholder": "e.g., MFR/PH/19/0039/00",
  "manufacturingDateLabel": "Manufacturing Date",
  "manufacturingDateRequired": "Please select manufacturing date",
  "manufacturingDatePlaceholder": "Select date",
  "batchCommencedOnLabel": "Batch Commenced On",
  "batchCommencedOnRequired": "Please select batch commencement date",
  "batchCommencedOnPlaceholder": "Select date",
  "batchCompletedOnLabel": "Batch Completed On",
  "batchCompletedOnRequired": "Please select batch completion date",
  "batchCompletedOnPlaceholder": "Select date",
  "totalQuantityLabel": "Total Quantity",
  "totalQuantityRequired": "Please enter total quantity",
  "totalQuantityPlaceholder": "e.g., ___ Kg",
  "manufacturingYieldLabel": "Manufacturing Yield (%)",
  "manufacturingYieldRequired": "Please enter manufacturing yield",
  "manufacturingYieldPlaceholder": "e.g., ___ %",
  "breakdownOrDeviationLabel": "Breakdown/Deviation",
  "breakdownOrDeviationRequired": "Please enter breakdown or deviation details",
  "breakdownOrDeviationPlaceholder": "Yes/No + Remarks if any",
  "reviewedByProductionLabel": "Reviewed By (Production)",
  "reviewedByProductionRequired": "Please enter production reviewer",
  "reviewedByProductionPlaceholder": "Signature/Date",
  "reviewedByQALabel": "Reviewed By (QA)",
  "reviewedByQARequired": "Please enter QA reviewer",
  "reviewedByQAPlaceholder": "Signature/Date",
  "addAttachment": "Add Attachment",
  "searchDataCollectionName": "Search Datacollections Name",
  "numberOfColumns": "Number of Columns",
  "procedureType": "Procedure Type",
  "addNewToolGroup": "Add New Tool Group",
  "dataCollectionReferences": "Data Collection References",
  "workInstructionReferences": "Work Instruction References",
  "toolGroupReferences": "Tool Group References",
  "procedureReferences": "Procedure References",
  "dataCollectionId": "Data Collection ID",
  "dataCollectionVersion": "Data Collection Version",
  "workInstructionId": "Work Instruction ID",
  "workInstructionVersion": "Work Instruction Version",
  "toolGroupId": "Tool Group ID",
  "toolGroupVersion": "Tool Group Version",
  "addRow": "Add Row",
  "noReferencesAdded": "No references added yet",
  "yieldPercentage": "Yield (%)",
  "expectedYield": "Expected Yield",
  "minimumYield": "Minimum Yield",
  "maximumYield": "Maximum Yield",

  // ============================================== Historical Filter Table / OEE Tabs ===========================================
  "oeeBack": "Back",
  "overallOee": "Overall OEE:",
  "oeeAvailability": "Availability",
  "oeePerformance": "Performance",
  "oeeQuality": "Quality",
  "oeeExpand": "Expand",
  "oeeCollapse": "Collapse",
  "expandToFullWidth": "Expand to full width",
  "machineTimeline": "Machine Timeline",
  "oeeResource": "Resource",
  "oeeDate": "Date",
  "oeeAvailable": "Available",
  "oeePlannedDowntime": "Planned Downtime",
  "oeeUnplannedDowntime": "Unplanned Downtime",
  "batchwiseData": "Batch-wise Data",
  "oeeTotal": "Total",
  "oeeRecords": "record(s)",
  "oeeFrom": "from",
  "oeeResources": "resource(s)",
  "clickOnChartBarToLoadBatchDetails": "Click on a chart bar to load batch details",
  "downloadAsExcel": "Download as Excel",
  "oeeExport": "Export",
  "exitFullscreen": "Exit fullscreen",
  "fullscreenView": "Fullscreen view",
  "exitTableView": "Exit Table View",
  "oeeFilters": "Filters:",
  "placeholderResource": "Resource",
  "placeholderDate": "Date",
  "placeholderBatchNo": "Batch No",
  "oeeSelected": "Selected:",
  "oeeClearSelection": "Clear Selection",
  "selectionCleared": "Selection cleared",
  "allSelectionsCleared": "All selections cleared",
  "updatedBatchData": "Updated batch data",
  "failedToRefreshBatchData": "Failed to refresh batch data",
  "oeeOrderNo": "Order No",
  "oeeItemCode": "Item Code",
  "oeeProduct": "Product",
  "oeePlanQty": "Plan Qty",
  "oeeActualQty": "Actual Qty",
  "oeePlanDT": "Plan DT",
  "oeeActualPT": "Actual Time",
  "oeePlanPT": "Plan Time",
  "oeeUnplanDT": "Unplan DT",
  "oeeGoodQty": "Good Qty",
  "oeeBadQty": "Bad Qty",
  "oeeCycleTime": "Cycle Time",
  "oeeActualCycleTime": "Actual Cycle Time",
  "oeeOee": "OEE",
  "downtimeDetails": "Downtime Details",
  "oeeDetails": "Details",
  "viewDowntimeDetails": "View Downtime Details",
  "downtimeAnalysisReport": "Downtime Analysis Report",
  "oeeUnplannedDowntimes": "Unplanned Downtimes",
  "oeePlannedDowntimes": "Planned Downtimes",
  "lineClearanceActivities": "Line Clearance Activities",
  "oeeReasonCode": "Reason Code",
  "oeeReasonDescription": "Reason Description",
  "oeeDowntime": "Downtime",
  "downtimeMinutes": "Downtime (Minutes)",
  "oeeNA": "N/A",
  "oeeTargetQuantity": "Batch Size",
  "oeeUom": "UOM",
  "oeeProductName": "Product Name",
  "excellentNoDowntimeEvents": "Excellent! No Downtime Events Recorded",
  "batchCompletedWithoutInterruptions": "This batch completed without any planned or unplanned interruptions.",
  "noMessageFound": "No {{message}} Found",
  "noMessageDuringPeriod": "This batch had no {{message}} during the selected period.",
  "errorLoadingData": "Error Loading Data",
  "oeeReason": "Reason",
  "oeeRootCause": "Root Cause",
  "oeeDuration": "Duration",
  "oeeStartTime": "Start Time",
  "oeeEndTime": "End Time",
  "oeeComment": "Comment",
  "oeeCreatedBy": "Created By",
  "oeeObjectType": "Object Type",
  "machine": "Machine",
  "manual": "Manual",
  "historicalReport": "Historical Report",
  "pleaseSelectWorkCenter": "Please select work center",
  "pleaseSelectResource": "Please select resource",
  "Work Center": "Work Center",
  "Resource": "Resource",
  "Select Shift": "Select Shift",
  "Event Type": "Event Type",
  "Date Range": "Date Range",
  "filterby": "Filter by",
  "historicalTable": "Historical Table",
  "availabilityAgainstResource": "Availability Against Resource",
  "availabilityAgainstShift": "Availability Against Shift",
  "confirmLayoutChange": "Confirm Layout Change",
  "layoutChangeWarning": "Changing the layout type will clear all prefilled values in the table. Are you sure you want to continue?",
  "editAttachment": "Edit Attachment",
  "attachmentUpdated": "Attachment updated successfully",
  "attachmentAdded": "Attachment added successfully",
  "optionalEntries": "Optional Entries",
  "requiredEntries": "Required Entries",
  "relesable": "Relesable",
  "new": "New",
  "fieldType": "Field Type",
  "customDataFields": "Custom Data Fields",
  "editAttachmentPoint": "Edit Attachment Point",
  "mandatoryStep": "Mandatory Step",
  "canSkip": "Can Skip",
  "requiresSignOff": "Requires Sign Off",
  "autoProgressOnComplete": "Auto Progress On Complete",
  "procedureSteps": "Procedure Steps",
  "multiDataCollectionList": "Multi Data Collection List",
  "totalRecords": "Total Records",
  "collect": "Collect",
  "validationRange": "Validation Range",
  "phaseVersion": "Phase Version",
  "mfr": "MFR",
  "mfrVersion": "MFR Version",
  "bmr": "BMR",
  "bmrVersion": "BMR Version",
  "PleaseSelectAttachmentsToRemove": "Please select attachments to remove",
  "RemoveSelectedAttachments": "Remove selected attachments",
  "NoAttachmentsToRemove": "No attachments to remove",
  "RemoveAllAttachments": "Remove all attachments",
  "AreYouSureYouWantToRemoveAllAttachments": "Are you sure you want to remove all attachments?",
  "AllAttachmentsRemoved": "All attachments removed",
  "allowMultipleDc": "Multiple DC",
  "allowPartialSave": "Partial Save",
  "allowSaveOnValidateFail": "Save On Validate Fail",
  "optionalAndRequiredEntries": "Optional And Required Entries",
  "allowAddRow": "Allow Add Row",
  "overRideRangeValue": "Override Range Value",
  "selectNcCode": "Select NC Code",
  "ncLog": "NC Log",
  
  // Document History Report
  "documentHistoryReport": "Document History Report",
  "docNo": "Doc No",
  "docNoPlaceholder": "BMR-2024-*",
  "allDocuments": "All Documents",
  "statusNew": "New",
  "statusInProgress": "In Progress",
  "statusPending": "Pending",
  "statusApproved": "Approved",
  "statusCompleted": "Completed",
  "statusRejected": "Rejected",
  "statusDraft": "Draft",
  "noHistoryAvailable": "No history available",
  "searchSuccess": "Found {count} record(s)",
  "noRecordsFound": "No records found",
  "exportPdfSuccess": "PDF exported successfully",
  "exportExcelSuccess": "Excel exported successfully",
  "exportError": "Error exporting file",
  "searchError": "Error searching documents",
  "showingCount": "Showing {{count}} of {{total}} documents",

  // ============================================== OEE Report Dashboard ===========================================

  // Sidebar Navigation
  "oeeReportSidebarTitle": "OEE Dashboard",
  "oeeReportNavOverview": "Live OEE Overview",
  "oeeReportNavAvailability": "Avail & Downtime",
  "oeeReportNavPerformance": "Performance",
  "oeeReportNavQuality": "Quality",
  "oeeReportNavBatch": "Batch Wise OEE",
  "oeeReportNavWorkcenter": "WorkCenter & Resource",
  "oeeReportNavResourcetype": "Resource Type",

  // Filter Bar
  "oeeReportFilterDateRange": "Date Range",
  "oeeReportFilterEventMode": "Event Mode",
  "oeeReportFilterMachine": "Machine",
  "oeeReportFilterManual": "Manual",
  "oeeReportFilterWorkCenter": "Work Center",
  "oeeReportFilterResource": "Resource",
  "oeeReportFilterResourceType": "Resource Type",
  "oeeReportFilterShift": "Shift",
  "oeeReportFilterBatch": "Batch No",
  "oeeReportFilterItem": "Item",
  "oeeReportFilterApply": "Apply",
  "oeeReportFilterReset": "Reset",
  "oeeReportFilterAllLines": "All Lines",
  "oeeReportFilterAllResources": "All Resources",
  "oeeReportFilterAllTypes": "All Types",
  "oeeReportFilterAllShifts": "All Shifts",
  "oeeReportFilterAllBatches": "All Batches",
  "oeeReportFilterAllItems": "All Items",

  // Overview - Header
  "oeeReportOverviewTitle": "Plant OEE",
  "oeeReportOverviewLive": "LIVE",
  "oeeReportOverviewShiftMorning": "Morning Shift",
  "oeeReportOverviewShiftAfternoon": "Afternoon Shift",
  "oeeReportOverviewShiftNight": "Night Shift",
  "oeeReportOverviewIntervalToday": "Today",
  "oeeReportOverviewIntervalShift": "This Shift",
  "oeeReportOverviewInterval4h": "Last 4h",
  "oeeReportOverviewInterval1h": "Last 1h",

  // Overview - Tiles
  "oeeReportOverviewTileOee": "OEE",
  "oeeReportOverviewTileAvailability": "Availability",
  "oeeReportOverviewTilePerformance": "Performance",
  "oeeReportOverviewTileQuality": "Quality",
  "oeeReportOverviewTooltipOee": "Overall Equipment Effectiveness = Availability x Performance x Quality",
  "oeeReportOverviewTooltipAvailability": "Availability = Production Time / Scheduled Time",
  "oeeReportOverviewTooltipPerformance": "Performance = (Actual Output / Standard Output) during run time",
  "oeeReportOverviewTooltipQuality": "Quality = Good Units / Total Units Produced",

  // Overview - Detail Rows
  "oeeReportOverviewScheduledTime": "Scheduled Time",
  "oeeReportOverviewProductiveTime": "Productive Time",
  "oeeReportOverviewUnplannedStops": "Unplanned Stops",
  "oeeReportOverviewPlannedMaint": "Planned Maintenance",
  "oeeReportOverviewStdOutput": "Standard Output",
  "oeeReportOverviewActOutput": "Achieved Output",
  "oeeReportOverviewOpportunity": "Opportunity",
  "oeeReportOverviewSpeedVariance": "Speed Variance",
  "oeeReportOverviewTotalProduced": "Total Produced",
  "oeeReportOverviewGoodUnits": "Good Units",
  "oeeReportOverviewReworkRequired": "Rework Required",
  "oeeReportOverviewYieldOpp": "Yield Opportunity",

  // Overview - Production Progress
  "oeeReportOverviewTarget": "Target",
  "oeeReportOverviewAchieved": "Achieved",
  "oeeReportOverviewRemaining": "Remaining",
  "oeeReportOverviewEta": "ETA",

  // Overview - Trend Charts
  "oeeReportOverviewHourlyTrend": "OEE Hourly Trend - Today",
  "oeeReportOverviewWeeklyAvail": "Availability - Weekly",
  "oeeReportOverviewWeeklyPerf": "Performance - Weekly",
  "oeeReportOverviewWeeklyQual": "Quality - Weekly",

  // Overview - Analysis Panels
  "oeeReportOverviewPanelAvail": "Availability Analysis",
  "oeeReportOverviewPanelPerf": "Performance Analysis",
  "oeeReportOverviewPanelQual": "Quality Analysis",
  "oeeReportOverviewSelectAll": "Select All",
  "oeeReportOverviewStopReasons": "Stop Reasons",
  "oeeReportOverviewMachineUtil": "Machine Utilization",
  "oeeReportOverviewActionsTaken": "Actions Taken",
  "oeeReportOverviewImprovementOpp": "Improvement Opportunities",
  "oeeReportOverviewOutputCompare": "Output Comparison",
  "oeeReportOverviewTop10Items": "Top 10 Items - Quality Issues",
  "oeeReportOverviewTop10Reasons": "Top 10 Rejection Reasons",
  "oeeReportOverviewCategoryAnalysis": "Category Analysis",
  "oeeReportOverviewRecommendations": "Insights & Recommendations",
  "oeeReportOverviewViewDetails": "View Details",
  "oeeReportOverviewFocus": "Focus",

  // Overview - Pareto Charts
  "oeeReportOverviewDtPareto": "Downtime Pareto Analysis",
  "oeeReportOverviewPerfPareto": "Performance Loss Pareto",
  "oeeReportOverviewQualPareto": "Quality Rejection Pareto",

  // Overview - Machine Table
  "oeeReportOverviewTableMachine": "Machine",
  "oeeReportOverviewTableWc": "Work Centre",
  "oeeReportOverviewTableBatch": "Batch No",
  "oeeReportOverviewTableMaterial": "Material",
  "oeeReportOverviewTableStatus": "Status",
  "oeeReportOverviewTableOee": "OEE %",
  "oeeReportOverviewTableAvail": "Avail %",
  "oeeReportOverviewTablePerf": "Perf %",
  "oeeReportOverviewTableQual": "Qual %",
  "oeeReportOverviewTableStdOutput": "Std. Output",
  "oeeReportOverviewTableActOutput": "Actual Output",
  "oeeReportOverviewTableGood": "Good",
  "oeeReportOverviewTableRejected": "Rejected",
  "oeeReportOverviewTableRunRate": "Run Rate",
  "oeeReportOverviewTableDowntime": "Downtime",

  // Availability Section
  "oeeReportAvailTitle": "Availability & Downtime Analysis",
  "oeeReportAvailTotalDt": "Total Downtime",
  "oeeReportAvailDtEvents": "DT Events",
  "oeeReportAvailMttr": "MTTR",
  "oeeReportAvailReason": "Reason",
  "oeeReportAvailDuration": "Duration",
  "oeeReportAvailEvents": "Events",
  "oeeReportAvailActions": "Actions",

  // Performance Section
  "oeeReportPerfTitle": "Performance Analysis",
  "oeeReportPerfStdOutput": "Standard Output",
  "oeeReportPerfActOutput": "Actual Output",
  "oeeReportPerfSpeedLoss": "Speed Loss",
  "oeeReportPerfGap": "Gap",

  // Quality Section
  "oeeReportQualTitle": "Quality Analysis",
  "oeeReportQualTotalProduced": "Total Produced",
  "oeeReportQualGood": "Good",
  "oeeReportQualRejected": "Rejected",
  "oeeReportQualItem": "Item",
  "oeeReportQualCode": "Code",
  "oeeReportQualTrend": "Trend",
  "oeeReportQualCategory": "Category",
  "oeeReportQualCatMachine": "Machine",
  "oeeReportQualCatMaterial": "Material",
  "oeeReportQualCatMethod": "Method",
  "oeeReportQualCatMan": "Man",
  "oeeReportQualInsights": "Insights & Recommendations",

  // Batch Section
  "oeeReportBatchTitle": "Batch Wise OEE",
  "oeeReportBatchTotal": "Total Batches",
  "oeeReportBatchAvgOee": "Avg OEE",
  "oeeReportBatchAvgAvail": "Avg Availability",
  "oeeReportBatchAvgPerf": "Avg Performance",
  "oeeReportBatchAvgQual": "Avg Quality",
  "oeeReportBatchBest": "Best Batch",
  "oeeReportBatchCompare": "Compare Selected",
  "oeeReportBatchStatus": "Status",
  "oeeReportBatchCompleted": "Completed",
  "oeeReportBatchRunning": "Running",
  "oeeReportBatchHold": "Hold",

  // WorkCenter Section
  "oeeReportWcTitle": "WorkCenter & Resource Analysis",
  "oeeReportWcSearch": "Search work centers...",
  "oeeReportWcAll": "All",
  "oeeReportWcCritical": "Critical",
  "oeeReportWcWarning": "Warning",
  "oeeReportWcGood": "Good",
  "oeeReportWcExpandAll": "Expand All",
  "oeeReportWcCollapseAll": "Collapse All",
  "oeeReportWcSortDt": "Sort by DT",
  "oeeReportWcSortReject": "Sort by Reject",
  "oeeReportWcSortOee": "Sort by OEE",

  // Resource Type Section
  "oeeReportRtTitle": "Resource Type Analysis",
  "oeeReportRtMachines": "machines",
  "oeeReportRtAvgOee": "Avg OEE",

  // Drill-Down Modal
  "oeeReportDrillTitle": "Drill Down",
  "oeeReportDrillMachines": "Machines",
  "oeeReportDrillItems": "Items",
  "oeeReportDrillRejections": "Rejection Reasons",

  // Common
  "oeeReportCommonAboveTarget": "Above target",
  "oeeReportCommonBelowTarget": "below target",
  "oeeReportCommonNoData": "No data available",
  "oeeReportCommonLoading": "Loading...",
  "oeeReportCommonError": "An error occurred",
  "oeeReportCommonRetry": "Retry",
  "oeeReportCommonClose": "Close",
  "oeeReportCommonUnits": "units",
  "oeeReportCommonPcsMin": "pcs/min",

  // Status Values
  "oeeReportStatusRunning": "Running",
  "oeeReportStatusDown": "Down",
  "oeeReportStatusIdle": "Idle",
  "oeeReportStatusChangeover": "Changeover",
  "oeeReportStatusMaintenance": "Maintenance",

  // Delta Badge
  "oeeReportDeltaUp": "up from previous period",
  "oeeReportDeltaDown": "down from previous period",
  "oeeReportDeltaNoChange": "No change",
  "hideColumn": "Hide Column"
}
