export const kannadaLanguage = {
  "schedulerMaintenance": "ಅನೂಕುಲನೆ ನಿರ್ವಹಣೆ",
  "phaseDefinition": "ಪೈಶ ವಿಭಾಗ",
  "search phase": "ಹಂತವನ್ನು ಹುಡುಕಿ",
  "allStatus": "ಎಲ್ಲಾ ಸ್ಥಿತಿ",
  "all types": "ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು",
  "createNew": "ಹೊಸದನ್ನು ರಚಿಸಿ",
  "documentType": "ದಾಖಲೆ ಪ್ರಕಾರ",
  "requestType": "ಅನುರೋಧ ಪ್ರಕಾರ",
  "max": "ಗರಿಷ್ಠ",
  "min": "ಕಿಮ್ಮತ್ತು",
  "tolerance": "ಅನುಮತಿ",
  "actualValue": "ವಾಸ್ತವ ಮೌಲ್ಯ",
  "actionsOnFailure": "ವಿಫಲವಾದಾಗ ಚಟುವಟಿಕೆಗಳು",
  "monitoringFrequency": "ನಿಗಾ ಅವೃತ್ತಿ",
  "expectedValue": "ಅನುಮಾನಿತ ಮೌಲ್ಯ",
  "qcId": "ಕ್ಯೂಸೀ ಐಡಿ",
  "productCode": "ಪ್ರೋಡುಕ್ಸನ್ ಕೋಡ್",
  "expectedValueRange_kn": "ಅನುಮಾನದ ಮೌಲ್ಯ ವ್ಯಾಪ್ತಿ",
  "frequency": "ಆವೃತ್ತಿ",
  "dataPointID": "ದತ್ತೆ ಪಾಯಿಂಟ್ ಐಡಿ",
  "pressure": "ಊರ್ಜೆ",
  "productionVersion": "ಪ್ರೋಡುಕ್ಸನ್ ವರ್ಜನ",  
  "duration": "ಅವಧಿ",
  "rpm": "ಆರ್ಎಂಪಿ",
  "workCenterId": "ಕೋಶ ಐಡಿ",
  "defaultPhaseId": "ಡೀಫಾಲ್ಟ್ ಹಂತ ಐಡಿ",
  "multiDataCollectionList": "ಬಹು ಡೇಟಾ ಸಂಗ್ರಹ ಪಟ್ಟಿ",
  "totalRecords": "ಒಟ್ಟು ದಾಖಲೆಗಳು",
  "collect": "ಸಂಗ್ರಹಿಸು",
  "resourceId": "ಸಂಪತ್ತು ಐಡಿ",
  "adjustments": "ಸಂಯೋಜನೆಗಳು",
  "monthlyPlan": "ಮಾಸಿಕ ಯೋಜನೆ",
  "qualityControlParameters": "ಗುಣಮಟ್ಟದ ನಿಯಂತ್ರಣ ಪರಿಮಾಣಗಳು",
  "dataCollection": "ದತ್ತೆ ಸಂಗ್ರಹಣೆ",
  "unsavedChangesMessage": "ಅಪರಿಹಾರ್ಯ ಬದಲಾವಣೆಗಳು ಕೊನೆಗೊಳ್ಳುತ್ತವೆ. ನೀವು ಈ ಪುಟವನ್ನು ಛೊಡಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?",
  "unsavedChangesMessages": "ಅಪರಿಹಾರ್ಯ ಬದಲಾವಣೆಗಳು ಕೊನೆಗೊಳ್ಳುತ್ತವೆ. ನೀವು ಈ ಪುಟವನ್ನು ಛೊಡಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?",
  "resources": "ಸಂಪತ್ತುಗಳು",
  "validateRange": "ಶ್ರೇಣಿಯನ್ನು ಪರಿಶೀಲಿಸಿ",
  "tools": "ತಂಡಗಳು",
  "safetyProcedures": "ಭದ್ರತಾ ವಿಧಾನಗಳು",
  "yieldWasteTracking": "ಫಲಿತಾಂಶ ಮತ್ತು ತ್ಯಾಜ್ಯ ನಿಗಾ",
  "triggerPoints": "ಟ್ರಿಗರ್ ಪಾಯಿಂಟ್‌ಗಳು",
  "packagingLabeling": "ಪ್ಯಾಕೇಜಿಂಗ್ ಲೇಬ್ಲಿಂಗ್",
  "recipeName": "ಬಡಲೆ",
  "ccp": "ಸಿಸಿಪಿ",
  "stepName": "ಹಂತದ ಹೆಸರು",
  "instruction": "ಸೂಚನೆ",
  "steps": "ಹಂತಗಳು",
  "id": "ಐಡಿ",
  "associatedStep": "ಸಂಬಂದಿಸಿದ ಹಂತ",
  "expectedCycleTime": "ಅನುಮಾನದ ಚಕ್ರಕಾಲ",
  "ingredients": "ಪದಾರ್ಥಗಳು",
  "phases": "ಹಂತಗಳು",
  "phaseId": "ಹಂತದ ಐಡಿ",
  "phaseName": "ಹಂತದ ಹೆಸರು",
  "phasesName": "ಹಂತಗಳ ಹೆಸರುಗಳು",
  "inactive": "ನಿಷ್ಕ್ರಿಯ",
  "recipeId": "ಪಾಕವಿಧಾನ ಐಡಿ",
  "batchSize": "ಕಣದ ಗಾತ್ರ",
  "batchUom": "ಕಣದ ಏಕಕ",
  "totalExpectedCycleTime": "ಒಟ್ಟು ನಿರೀಕ್ಷಿತ ಚಕ್ರ ಸಮಯ",
  "totalActualCycleTime": "ಒಟ್ಟು ವಾಸ್ತವಿಕ ಚಕ್ರ ಸಮಯ",
  "active": "ಸಕ್ರಿಯ",
  "recipeStepDetails": "ವಿಧಾನ ಹಂತದ ವಿವರಗಳು",
  "workInstructions": "ಕಾರ್ಯ ಸೂಚನೆಗಳು",
  "dataCollections": "ದತ್ತಾಂಶ ಸಂಗ್ರಹಣೆ",
  "parameterLists": "ಪರಿಮಾಣ ಪಟ್ಟಿ",
  "classification": "ವರ್ಗೀಕರಣ",
  "relaxedRecipeFlow": "ಶ್ರೇಣೀಬದ್ಧವಾದ ವಿಧಾನ",
  "scan": "ಸ್ಕಾನ್",
  "shipmentOrderNumber": "ಕಳುಹಿಸುವ ಆದೇಶ ಸಂಖ್ಯೆ",
  "dispatchDetails": "ವಿತರಣೆಯ ವಿವರಗಳು",
  "dispatchDateTime": "ವಿತರಣೆಯ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "recipientInfo": "ಸ್ವೀಕೃತ್ತ ಮಾಹಿತಿ",
  "dispatchInfo": "ವಿತರಣೆಯ ಮಾಹಿತಿ",
  "recipeSteps": "ವಿಧಾನ ಹಂತಗಳು",
  "stageType": "ಹಂತ ಪ್ರಕಾರ",
  "recipeType": "ಬಳಕೆ ಪ್ರಕಾರ",
  "recipe": "ಬಳಕೆ",
  "stage": "ಹರವು",
  "processOrderRelease": "ಪ್ರಕ್ರಿಯೆ ಬಿಡುಗಡೆ",
  releaseProcessOrder: "ವಿಮೋಚನ ಪ್ರಕ್ರಿಯೆ ಆರ್ಡರ್",
  processOrder: "ಪ್ರಕ್ರಿಯೆ ಆರ್ಡರ್",
  appTitle: "ಐಟಂ ನಿರ್ವಹಣೆ",
  item: "ಐಟಂ",
  shiftName: "ಶಿಫ್ಟ್ ಹೆಸರು",
  description: "ವಿವರಣೆ",
  recipeDescription: "ವಿವರಣೆ",
  searchActivities: "ಚಟುವಟಿಕೆಗಳನ್ನು ಹುಡುಕಿ",
  logout: "ಲಾಗ್ ಔಟ್",
  revision: "ಪರಿಷ್ಕರಣೆ",
  "qtyConsumed": "ಖರೀದಿಸಿದ ಪ್ರಮಾಣ",
  status: "ಸ್ಥಿತಿ",
  procurementType: "ಸಂಗ್ರಹಣೆ ಪ್ರಕಾರ",
  lotSize: "ಸಾಕಷ್ಟು ಗಾತ್ರ",
  createShift: "ಶಿಫ್ಟ್ ರಚಿಸು",
  "data": "ಡೇಟಾ",
  workCenter: "ಕೆಲಸ ಕೇಂದ್ರ",
  resource: "ಸಾಧನ",
  add: "ಜೋಡಿಸು",
  main: "ಪ್ರಮುಖ",
  alternateComponent: "ಪರ್ಯಾಯ ಘಟಕ",
  printDocument: "ಮುದ್ರಣ ದಾಖಲೆ",
  customData: "ಕಸ್ಟಮ್ ಡೇಟಾ",
  itemGroup: "ಐಟಂ ಗುಂಪು",
  qtyRestriction: "ಪ್ರಮಾಣದ ನಿರ್ಬಂಧ",
  routing: "ರೌಟಿಂಗ್",
  routingVersion: "ರೌಟಿಂಗ್ ಆವೃತ್ತಿ",
  bom: "ಬಿಒಎಂ",
  bomVersion: "ಬಿಒಎಂ ಆವೃತ್ತಿ",
  assemblyDataType: "ವಿಧಾನ ಪ್ರಕಾರ",
  removalDataType: "ತೆಗೆಯುವ ಪ್ರಕಾರ",
  receiptDataType: "ಸ್ವೀಕೃತ ಪ್ರಕಾರ",
  currentVersion: "ಪ್ರಸ್ತುತ ಆವೃತ್ತಿ",
  itemType: "ಐಟಂ ಪ್ರಕಾರ",
  create: "ರಚಿಸಿ",
  save: "ಉಳಿಸಿ",
  cancel: "ರದ್ದುಮಾಡಿ",
  "sequence": "ಕ್ರಮಾಂಕ",
  "version": "ಆವೃತ್ತಿ",
  "versions": "ಆವೃತ್ತಿ: ",
  "parentMaterial": "ಪೋಷಕ ವಸ್ತು",
  "validFrom": "ಇಂದೆ ಮಾನ್ಯ",
  "validTo": "ಇಲ್ಲಿಯವರೆಗೆ ಮಾನ್ಯ",
  "createdDate": "ತಯಾರಿಸಿದ ದಿನಾಂಕ: ",
  "modifiedTime": "ಮಾರ್ಪಡಿಸಿದ ಸಮಯ: ",
  "availableDocuments": "ಲಭ್ಯವಿರುವ ದಾಖಲೆಗಳು",
  "assignedDocuments": "ನಿಯೋಜಿತ ದಾಖಲೆಗಳು",
  "document": "ದಾಖಲೆ",
  "createItem": "ಐಟಂ ರಚಿಸಿ",
  "value": "ಮೌಲ್ಯ",
  "go": "ಹೋಗು",
  copy: "ಪ್ರತಿ",
  confirmCopy: "ದೃಢೀಕರಿಸು ಪ್ರತಿ",
  delete: "ಅಳಿಸಿ",
  confirmDelete: "ಅಳಿಸುವುದು ದೃಢೀಕರಿಸಿ",
  deleteMessage: "ನೀವು ಈ ಐಟಂ ಅನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರಾ?",
  "insert": "ಸೇರಿಸು",
  "removeSelected": "ಆಯ್ದವುಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
  "removeAll": "ಎಲ್ಲವನ್ನು ತೆಗೆದುಹಾಕಿ",
  "generalInfo": "ಸಾಮಾನ್ಯ ಮಾಹಿತಿ",
  "materialCode": "ವಸ್ತು ಕೋಡ್",
  "materialDescription": "ವಸ್ತು ವಿವರಣೆ",
  "purchaseOrderNumber": "ಖರೀದಿ ಆದೇಶ ಸಂಖ್ಯೆ",
  "grnNumber": "GRN ಸಂಖ್ಯೆ",
  "supplierInfo": "ಪೂರೈಕೆದಾರರ ಮಾಹಿತಿ",
  "supplierName": "ಪೂರೈಕೆದಾರ ಹೆಸರು",
  "supplierId": "ಪೂರೈಕೆದಾರ ಐಡಿ",
  "invoiceNumber": "ಬಿಲ್ಲು ಸಂಖ್ಯೆ",
  "storageLocation": "ಸಂಗ್ರಹ ಸ್ಥಳ",
  "warehouseCode": "ಗೋದಾಮಿನ ಕೋಡ್",
  "storageBin": "ಸಂಗ್ರಹ ಬಿನ್",
  "deliveryInfo": "ವಿತರಣಾ ಮಾಹ��ತಿ",
  "deliveryNumber": "ವಿತರಣಾ ಸಂಖ್ಯೆ",
  "deliveryType": "ವಿತರಣಾ ಪ್ರಕಾರ",
  "vehicleNumber": "ವಾಹನ ಸಂಖ್ಯೆ",
  "inwardDetails": "ಊರ್ವೆ ವಿವರಗಳು",
  "receiptDateTime": "ಸ್ವೀಕೃತಿ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "gateDockNumber": "ಗೇಟ್ ಡಾಕ್ ಸಂಖ್ಯೆ",
  "attachmentDocument": "ಅಟಾಚ್‌ಮೆಂಟ್ ಡಾಕ್ಯುಮೆಂಟ್",
  "attachment": "ಅಟಾಚ್‌ಮೆಂಟ್",


  "boxNumber": "ಬಾಕ್ಸ್ ಸಂಖ್ಯೆ",
  "boxCapacity": "ಬಾಕ್ಸ್ ಸಾಮರ್ಥ್ಯ",
  "packetId": "ಪ್ಯಾಕೆಟ್ ಐಡಿ",
  "packetDescription": "ಪ್ಯಾಕೆಟ್ ವಿವರಣೆ",
  "remainingCapacity": "ಉಳಿದ ಸಾಮರ್ಥ್ಯ",
  "totalPacketsInBox": "ಬಾಕ್ಸ್‌ನಲ್ಲಿ ಒಟ್ಟು ಪ್ಯಾಕೆಟ್ಗಳು",

  // =====================================================================

  "reasonCodeAppTitle": "ಕಾರಣ ಕೋಡ್ ನಿರ್ವಹಣೆ",
  "reasonCode": "ಕಾರಣ ಕೋಡ್",
  "category": "ವರ್ಗ",
  "messageType": "ಸಂದೇಶ ಪ್ರಕಾರ",
  "createReasonCode": "ಕಾರಣ ಕೋಡ್ ರಚಿಸಿ",
  rowSelectionMsg: "ನೀವು ಸಾಲು ಆಯ್ಕೆಯನ್ನು ಮುಂದುವರಿಸಲು ಇಚ್ಛಿಸುತ್ತೀರಾ?",
  "selectMessageType": "ಸಂದೇಶ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectResource": "ಸಂಪನ್ಮೂಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectWorkCenter": "ಕಾರ್ಯ ಕೇಂದ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectContainer": "ಕಂಟೈನರ್ ಆಯ್ಕೆಮಾಡಿ",

  "consumptionAndPackingAppTitle": "ಖರ್ಚು ಮತ್ತು ಪ್ಯಾಕಿಂಗ್",
  //=============================================================


  "routingTitle": "ರೌಟಿಂಗ್ ನಿರ್ವಹಣೆ",
  "routingType": "ರೌಟಿಂಗ್ ಪ್ರಕಾರ",
  "routingSteps": "ರೌಟಿಂಗ್ ಹಂತಗಳು",
  "subType": "ಉಪ ಪ್ರಕಾರ",
  "dispositionGroup": "ವಿತರಣಾ ಗುಂಪು",
  "relaxedRoutingFlow": "ರಿಲ್ಯಾಕ್ಸ್‌ಡ್ ಫ್ಲೋ ರೌಟಿಂಗ್",
  "replicationToErp": "ಇಆರ್‌ಪಿ ಗೆ ಪ್ರತಿದಾನ",
  "details": "ವಿವರಗಳು",
  "nextStepId": "ಮುಂದಿನ ಹಂತಗಳ ಐಡಿ",
  "stepId": "ಹಂತ ಐಡಿ",
  "stepType": "ಹಂತದ ಪ್ರಕಾರ",
  "stepDescription": "ಹಂತದ ವಿವರಣೆ",
  "previousStepId": "ಹಿಂದಿನ ಹಂತಗಳ ಐಡಿ",
  "maximumLoopCount": "ಗರಿಷ್ಠ ಲೂಪ್ ಎಣಿಕೆ",
  "queueDecision": "ಪ್ರಧಾನ ನಿರ್ಧಾರ",
  "erpControlKey": "ಇಆರ್‌ಪಿ ನಿಯಂತ್ರಣ ಕೀ",
  "erpOperation": "ಇಆ್‌ಪಿ ಕಾರ್ಯಾಚರಣೆ",
  "erpWorkCenter": "ಇಆರ್‌ಪಿ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "requiredTimeInProcess": "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಬೇಕಾದ ಸಮಯ",
  "specialInstruction": "ವಿಶೇಷ ಸೂಚನೆ",
  "erpSequence": "ಇಆರ್‌ಪಿ ಕ್ರಮ",
  "blockPcusUntilInspectionFinished": "ನಿರೀಕ್ಷಣೆ ಮುಗಿಯುವವರೆಗೂ PCUs ಅನ್ನು ತಡೆ",
  "entryStep": "ಪ್ರವೇಶ ಹಂತ",
  "isLastReportingStep": "ಅಂತಿಮ ವರದಿ ಹಂತ",
  "reworkStep": "ಪುನಃಕಾರ್ಯ ಹಂತ",
  "routingStepDetails": "ರೌಟಿಂಗ್ ಹಂತದ ವಿವರಗಳು",
  "routingDescription": "ರೌಟರ್ ವಿವರಣೆ",
  "insertBefore": "ಮೊದಲಿನಿಂದ ಸೇರಿಸಿ",
  "insertAfter": "ನಂತರ ಸೇರಿಸಿ",
  "createRouting": "ಮಾರ್ಗಗಳನ್ನು ರಚಿಸಿ",
  "operation": "ಆಪರೇಶನ್",
  "trackOee": "ಒಇಇ ಹಿಂಬಾಲನೆ",
  "operationId": "ಆಪರೇಶನ್ ಐಡಿ",
  "operationVersion": "ಆಪರೇಶನ್ ಆವೃತ್ತಿ",
  "workListPanel": "ಕೆಲಸದ ಪಟ್ಟಿಯ ಪ್ಯಾನಲ್",

  // ============================= Activity =======================
  "activityAppTitle": "ಕಾರ್ಯಚಟುವಟಿಕೆ ನಿರ್ವಹಣೆ",
  "activity": "ಚಟುವಟಿಕೆ",
  "activityIds": "ಚಟುವಟಿಕೆ ಐಡಿ",
  "activityGroup": "ಚಟುವಟಿಕೆ ಗುಂಪು",
  "remove": "ಅಳಿಸಿ",
  "enabled": "ಸಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ",
  "visibleInActivityManager": "ಚಟುವಟಿಕೆ ನಿರ್ವಾಹಕದಲ್ಲಿ ಗೋಚರಿಸುತ್ತದೆ",
  "type": "ಪ್ರಕಾರ",
  "classOrProgram": "ತರಗತಿ / ಕಾರ್ಯಕ್ರಮ",
  "listOfMethod": "ವಿಧಾನಗಳ ಪಟ್ಟಿಯ",
  "createActivity": "ಚಟುವಟಿಕೆ ಸೃಷ್ಟಿಸಿ",
  "activityRules": "ಚಟುವಟಿಕೆ ನಿಯಮಗಳು",
  "activityHooks": "ಚಟುವಟಿಕೆ ಹೂಕ್ಸ್",
  "userArgument": "ಬಳಕೆದಾರ ವಾದ",
  "sites": "ಸೈಟ್",
  "hookableMethod": "ಹೂಕಬಲ್ ವಿಧಾನ",
  "hookPoint": "ಹೂಕ್ ಪಾಯಿಂಟ್",
  "rules": "ನಿಯಮಗಳು",
  "setting": "ಹೊಂದಾಣಿಕೆ",
  "addRules": "ನಿಯಮಗಳನ್ನು ಸೇರಿಸಿ",
  "addRule": "ನಿಯಮವನ್ನು ಸೇರಿಸಿ",
  restoreDefault: "ಡೀಫಾಲ್ಟ್ ಅನ್ನು ಪುನಃಸ್ಥಾಪಿಸಿ",
  "selectActivity": "ಚಟುವಟಿಕೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",

  // ========================== WORK CENTER =========================
  "workCenterAppTitle": "ಕಾರ್ಯ ಕೇಂದ್ರ ನಿರ್ವಹಣೆ",
  "workCenterCategory": "ಕಾರ್ಯ ಕೇಂದ್ರ ವರ್ಗ",
  "defaultParentWorkCenter": "ಡೀಫಾಲ್ಟ್ ಮೂಲ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "defaultWorkCenter": "ಡೀಫಾಲ್ಟ್ ಕಾರ್ಯ ಕೇಂದ್ರ",
  "createWorkCenter": "ಕಾರ್ಯ ಕೇಂದ್ರ ರಚಿಸಿ",
  "association": "ಸಂಘ",
  "associateId": "ಅಸೋಸಿಯೇಟ್ ಐಡಿ",
  "defaultResource": "ಡೀಫಾಲ್ಟ್ ಸಂಪನ್ಮೂಲ",
  "deleteWCMessage": "ನೀವು ಈ ಕೆಲಸದ ಕೇಂದ್ರವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿದೆಯೇ",
  "disabled": "ಅಚಲಿತ",
  "closeMsg": "ನೀವು ಪುಟವನ್ನು ಬಿಟ್ಟುಹೋಗಲು ಖಚಿತವಾಗಿದೆಯೇ?",
  "yes": "ಹೌದು",
  "no": "ಇಲ್ಲ",
  "ok": "ಸರಿ",
  "select": "ಆಯ್ಕೆ",
  "confirmation": "ದೃಢೀಕರಣ",
  "selectAssociateId": "ಸಂಬಂಧಿತ ಐಡಿ ಆಯ್ಕೆಮಾಡಿ",
  "closePageMsg": "ನೀವು ನಿಜವಾಗಿಯೂ ನಿರ್ಗಮಿಸಲು ಬಯಸುಿರಾ?",
  "leavePage": "ಪೇಜ್ ಬಿಟ್ಟುಬಿಡಿ",
  "router": "ರೌಟರ್",
  "prelautid": "ಪೂರ್ವ ಲಾಟಿಡ್",
  "materialName": "ವಸ್ತು ಹೆಸರು",
  "uom": "ಮಾಪನ ಏಕಕ",
  "expectedQty": "ಕೋರಲಾಗುವ ಪ್ರಮಾಣ",
  "unit": "ಏಕಕ",
  "receivedQty": "ಸ್ವೀಕೃತ ಪ್ರಮಾಣ",
  "actions": "ಕೃತ್ಯಗಳು",
  "phaseType": "ಹಂತ ಪ್ರಕಾರ",
  "headerTitle": "ಶಿಫ್ಟ್ ನಿರ್ವಹಣೆ",
  "siteMaintenance": "ಸೈಟ್ ನಿರ್ವಹಣೆ",
  "batchNo": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "pcu": "ಪಿಸಿಯು ",
  "itemBO": "ವಸ್ತು ",
  "routerBO": "ರೌಟರ್ ",
  "qty": "ಮಟ್ಟ",
  "shopOrderBO": "ಅಂಗಡಿಯ ಆದೇಶ ",
  "pod": "ಪಾಡ್",
  "timeZone": "ಟೈಮ್ ಝೋನ್",
  "local": "ಸ್ಥಳೀಯ",
  "site": "ಸೈಟ್ ನಿರ್ವಹಣೆ",
  "shift": "ಶಿಫ್ಟ್",
  "shopOrder": "ಅಂಗಡಿಕೆಗೆ ಆದೇಶ",
  "userHeaderTitle": "ಬಳಕೆದಾರ ನಿರ್ವಹಣೆ",
  "serialNumber": "ಅಂಕಿತ ಸಂಖ್ಯೆ",
  "pcuNumber": "ಪಿಸಿಇಯು ಸಂಖ್ಯೆ",
  "underDeliveryTolerance": "ಡಿಸ್ಪ್ಯಾಚ್ ಸಹಿಷ್ಣುತೆ",
  "defineDeliveryToleranceIn": "ಮಟ್ಟದ ತಾಳ್ಮೆ ವ್ಯಾಖ್ಯಾನಿಸಿ",
  "doneQty": "ಮುಗಿಯುವ ಪ್ರಮಾಣ",
  "releasedQty": "ಬಿಟ್ಟ ಪ್ರಮಾಣ",
  "qtyInQueueOrWork": "ಕ್ಯೂ ಅಥವಾ ಕೆಲಸದಲ್ಲಿ ಪ್ರಮಾಣ",
  "scrappedQty": "ಕಳ್ಳತನ ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "unreleasedQty": "ಬಿಟ್ಟದೆಲ್ಲದ ಪ್ರಮಾಣ",
  "buildQty": "ನಿರ್ಮಾಣ ಪ್ರಮಾಣ",
  "recommendedBuildQtyToReachOrderedQty": "ಆರ್ಡರ್ ಮಾಡಿದ ಪ್ರಮಾಣವನ್ನು ತಲುಪಲು ಶಿಫಾರಸು ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "ಕೀಟಿಕ ಡೆಲಿವರಿ ಪ್ರಮಾಣವನ್ನು ತಲುಪಲು ಶಿಫಾರಸು ಮಾಡಲಾದ ಪ್ರಮಾಣ",
  "temperature": "ತಾಪಮಾನ",
  "overDeliveryTolerance": "ಮೆಟ್ರಿಕ್ ಪೂರೈಕೆ ಸಹಿಷ್ಣುತೆ",
  "maximumDeliveryQty": "ಹೆಚ್ಚುಮಟ್ಟದ ಡೆಲಿವರಿ ಪ್ರಮಾಣ",
  "minimumDeliveryQty": "ಕೀಟಿಕ ಡೆಲಿವರಿ ಪ್ರಮಾಣ",
  "unlimited_over_delivery": "ಅನ್ಲಿಮಿಟೆಡ್ ಓವರ ಡೆಲಿವರಿ",
  "pcuQuantity": "ಪಿಸಿಇಯು ಪ್ರಮಾಣ",
  "state": "ರಾಜ್ಯ",
  "user": "ಬಳಕೆದಾರ",
  "noOfCount": "ಶಿಫ್ಟ್",
  "shiftType": "ಶಿಫ್ಟ್ ಪ್ರಕಾರ",
  "material": "ಪದಾರ್ಥ",
  "cycleTime": "ಚಕ್ರ ಕಾಲ",
  "manufacturedTime": "ತಯಾರಿತ ಸಮಯ",
  "createCycleTime": "ಚಕ್ರ ಸಮಯವನ್ನು ರಚಿಸು",
  "materialVersion": "ಪದಾರ್ಥ ಆವೃತ್ತಿ",
  "update": "ನವೀಕರಿಸಿ",
  "shiftInterval": "ಶಿಫ್ಟ್ ಅಂತರ",
  "calendarRules": "ಕ್ಯಾಲೆಂಡರ್ ನಿಯಮಗಳು",
  "createdOn": "ರಚಿಸಲಾಗಿದೆ",
  "modifiedOn": "ತಿದ್ದುಪಡಿ ಮಾಡಲಾಗಿದೆ",
  "erpShift": "ಇಆರ್‌ಪಿ ಶಿಫ್ಟ್",
  "confirm": "ದೃಢೀಕರಿಸು",
  "alertRow": "ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಸಾಲಿನೊಂದಿಗೆ ಮುಂದುವರಿಯಲು ಬಯಸುತ್ತೀರಾ?",
  "addBreak": "ಬ್ರೇಕ್ ಸೇರಿಸಿ",
  "Status": "ಸ್ಥಿತಿ",
  "comment": "ಕಾಮೆಂಟ್",
  "newStatus": "ಹೊಸ ಸ್ಥಿತಿ",
  "selectBy": "ಆಧಾರಿತ ಆಯ್ಕೆ ಮಾಡಿ",
  "validityShiftInfo": "ವಾಲಿಡಿಟಿ/ಶಿಫ್ಟ್ ಮಾಹಿತಿಯು",
  "clockInOutInfo": "ಕ್ಲಾಕ್-ಇನ್/ಔಟ್ ಮಾಹಿತಿಯು",
  "labourInfo": "ಶ್ರಮ ಮಾಹಿತಿಯು",
  "action": "ಕ್ರಿಯೆ",
  "day": "ದಿನ",
  "productionDay": "ಉತ್ಪಾದನೆ ದಿನ",
  "dayClass": "ದಿನ ವರ್ಗ",
  "search": "ಹುಡುಕಿ",
  "maintenance": "ನಿರ್ವಹಣೆ",
  "certification": "ಪ್ರಮಾಣಪತ್ರ",
  "subStep": "ಉಪ-ಹಂತ",
  "activityHook": "ಚಟುವಟಿಕೆ ಹುಕ್",
  "operationType": "ಆಪರೇಶನ್ ಪ್ರಕಾರ",
  "resourceType": "ಸಾಧನ ಪ್ರಕಾರ",
  "defaultOperation": "ಮೂಲ ಆಪರೇಶನ್",
  "addAsErpOperation": "ಇಆರ್‌ಪಿ ಆಪರೇಶನ್ ಆಗಿ ಸೇರಿಸಿ",
  "maxLoopCount": "ಹೆಚ್ಚಿನ ಲೂಪ್ ಸಂಖ್ಯಾ",
  "enter": "ನೀಡಿ",
  "employeeNumber": "ಮೂಕಿಂಗ್ ಸಂಖ್ಯೆ",
  "hireDate": "ಆಹ್ವಾನ ದಿನಾಂಕ",
  "erpUser": "ಇಆರ್‌ಪಿ ಬಳಕೆದಾರ",
  "firstName": "ಮೊದಲ ಹೆಸರ",
  "lastName": "ಅಂತಿಮ ಹೆಸರು",
  "emailAddress": "ಇಮೇಲ್ ವಿಳಾಸ",
  "erpPersonnelNumber": "ಇಆರ್‌ಪಿ ವೈಯಕ್ತಿಕ ಸಂಖ್ಯೆ",
  "sl_no": "ಕ್ರಮ ಸಂಖ್ಯೆ",
  "packet_id": "ಪ್ಯಾಕೆಟ್ ಐಡಿ",
  "packet_description": "ಪ್ಯಾಕೆಟ್ ವಿವರಣೆ",
  "qty_consumed": "ಬಳಸಿದ ಪ್ರಮಾಣ",
  "total_packets": "ಒಟ್ಟು ಪ್ಯಾಕೆಟ್‌ಗಳು",
  "remaining_capacity": "ಉಳಿತಾಯ ಸಾಮರ್ಥ್ಯ",
  "userGroup": "ಬಳಕೆದಾರ ಗುಂಪು",
  "labourTracking": "ಶ್ರಮ ಹಿಂಬಾಲಿಸುವಿಕೆ",
  "supervisor": "ಮೂಲಕ",
  "labourRule": "ಶ್ರಮ ನಿಯಮ",
  "bomType": "ಬೋಮ್ ಪ್ರಕಾರ",
  "plannedBom": "ಯೋಚಿಸಲಾದ ಬೋಮ್",
  "plannedRouting": "ಯೋಚಿಸಲಾದ ಮಾರ್ಗಸೂಚಿ",
  "lcc": "ಎಲ್‌ಸಿಸಿ",
  "plannedWorkCenter": "ಯೋಚಿಸಲಾದ ಕೆಲಸದ ಕೇಂದ್ರ",
  "orderedQty": "ಆದೇಶಿತ ಪ್ರಮಾಣ",
  "priority": "ಪ್ರಾಮುಖ್ಯತೆ",
  "erpUom": "ಇಆರ್‌ಪಿ ಯುಒಎಮ್",
  "plannedStart": "ಯೋಚಿಸಲಾದ ಆರಂಭ",
  "plannedCompletion": "ಯೋಚಿಸಲಾದ ಪೂರ್ಣಗೊಳ್ಳುವುದು",
  "scheduledStart": "ನಿಯೋಜಿತ ಆರಂಭ",
  "scheduledEnd": "ನಿಯೋಜಿತ ಅಂತ್ಯ",
  "customerOrder": "ಗ್ರಾಹಕ ಆದೇಶ",
  "customer": "ಗ್ರಾಹಕ",
  "orderType": "ಆದೇಶ ಪ್ರಕಾರ",
  "plannedMaterial": "ಯೋಚಿಸಲಾದ ಪದಾರ್ಥ",
  "productionQuantities": "ಉತ್ಪಾದನಾ ಪ್ರಮಾಣಗಳು",
  "serialPCU": "ಸೀರಿಯಲ್ ಪಿಸಿಯು",
  "enable": "ಆಗೋಷ್ಟ",
  "bomMaintenance": "ಬೋಮ್ ನಿರ್ವಹಣೆ",
  "bomTemplate": "ಬೋಮ್ ಟೆಂಪ್ಲೇಟ್",
  "component": "ಘಟಕ",
  "assemblyOperation": "ಅಸೆಂಬ್ಲಿ ಆಪರೇಶನ್",
  "assemblyQuantity": "ಅಸೆಂಬ್ಲಿ ಪ್ರಮಾಣ",
  "copyBom": "ನಕಲು ಬೋಮ್",
  "updateBom": "ನವೀಕರಿಸಿ ಬೋಮ್",
  "assemblySequence": "ಅಸೆಂಬ್ಲಿ ಕ್ರಮ",
  "componentType": "ಘಟಕ ಪ್ರಕಾರ",
  "maxNc": "ಅತ್ಯದಿಕ ಎನ್‌ಸಿ",
  "maxUsage": "ಅತ್ಯದಿಕ ಬಳಸುವಿಕೆ",
  "createBomComponent": "ಬೋಮ್ ಘಟಕವನ್ನು ರಚಿಸಿ",
  "createNewBom": "ಹೊಸ ಬೊಮ್ ಅನ್ನು ರಚಿಸಿ",
  "alternateComponentVersion": "ಆಪ್ತಘಟಕ ಆವೃತ್ತಿ",
  "designCost": "ಡಿಸೈನ್ ವೆಚ್ಚ",
  "assySequence": "ಅಸಂಬ್ಲಿ ಕ್ರಮ",
  "componentVersion": "ಸಾಧನ ಆವೃತ್ತಿ",
  "componentDescription": "ಸಾಧನ ವರ್ಣನೆ",
  "assyQty": "ಅಸಂಬ್ಲಿ ಪ್ರಮಾಣ",
  "assyOperation": "ಅಸಂಬ್ಲಿ ಕಾರ್",
  "assemblyDataTypeBo": "ಅಸಂಬ್ಲಿ ಡೇಟಾ ಶ್ರೇಣಿ ",
  "storageLocationBo": "ಸಂಗ್ರಹಣಾ ಸ್ಥಳ ",
  "close": "ಮುಚ್ಚು",
  "availableActivities": "ಉಪಲಬ್ಧ ಚಟುವಟಿಕೆಗಳು",
  "assignedActivities": "ನಿಯೋಜಿತ ಚಟುವಟಿಕೆಗಳು",
  "activities": "ಚಟುವಟಿಕೆಗಳು",
  "activityGroupName": "ಚಟುವಟಿಕೆ ಗುಂಪು ಹೆಸರು",
  "activityGroupMaintenance": "ಚಟುವಟಿಕೆ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "createActivityGroup": "ಚಟುವಟಿಕೆ ಗುಂಪು ರಚಿಸಿ",
  "activityGroupDescription": "ಚಟುವಟಿಕೆ ಗುಂಪು ವಿವರಣೆ",
  "copyActivityGroup": "ನಕಲು ಚಟುವಟಿಕೆ ಗುಂಪು",
  "selectRouting": "ಮಾರ್ಗದರ್ಶನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "container": "ಕಂಟೈನರ್",
  "hold": "ಹೋಲ್ಡ್",
  "receive": "ಸ್ವೀಕರಿಸು",
  "reject": "ತಿರಸ್ಕರಿಸು",


  // ===============================   Next Number     ==============================
  "numbeType": "ಸಂಖ್ಯಾ ಪ್ರಕಾರ",
  "definedBy": "ನಿರ್ದಿಷ್ಟಗೊಳಿಸಲಾಗಿದೆ",
  "objectVersion": "ವಸ್ತುವಿನ ಆವೃತ್ತಿ",
  "containerInput": "ಕಂಟೈನರ್ ಇನ್ಪುಟ್",
  "prefix": "ಆರಂಭಿಕ",
  "suffix": "ಉಪಸರ್ಗ",
  "numberBase": "ಸಂಖ್ಯಾ ಮೂಲ",
  "sequenceLength": "ಆಗತದ ಉದ್ದ",
  "minSequence": "ಕನಿಷ್ಠ ಕ್ರಮ",
  "maxSequence": "ಅತಿದೊಡ್ಡ ಕ್ರಮ",
  "warningThreshold": "ಎಚ್ಚರಿಕೆ ಹಾರಿ",
  "incrementBy": "ಹೆಚ್ಚಿಸುವುದು",
  "currentSequence": "ಪ್ರಸ್ತುತ ಕ್ರಮ",
  "resetSequenceNumber": "ಕ್ರಮ ಸಂಖ್ಯೆಯನ್ನು ಪುನರಾವೃತ್ತ ಮಾಡು",
  "nextNumberActivity": "ಮುಂದಿನ ಸಂಖ್ಯಾ ಕ್ರಿಯೆ",
  "createContinuousSfc": "ಆಮದಿಯಲ್ಲಿ ನಿರಂತರ ಎಸ್‌ಎಫ್‌ಸಿಯನ್ನು ರಚಿಸು",
  "commitNextNumberChangesImmediately": "ಮುಂದಿನ ಸಂಖ್ಯಾ ಬದಲಾವಣೆಗಳನ್ನು ತಕ್ಷಣವೇ ಬದಲಾಗಿಸು",
  "sampleNextNumber": "ಉದಾಹರಣೆಯ ಮುಂದಿನ ಸಂಖ್ಯಾ",
  "nextNumberAppTitle": "ಮುಂದಿನ ಸಂಖ್ಯೆ ನಿರ್ವಹಣೆ",
  "parametersAndDescription": "ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು ಮತ್ತು ವಿವರ",
  "selectItemGroup": "ಐಟಂ ಗುಂಪು ಆಯ್ಕೆಮಾಡಿ",
  "selectDataType": "ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "selectBOM": "ಬಿಒಎಮ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectItem": "ಐಟಂ ಆಯ್ಕೆಮಾಡಿ",
  "retrieve": "ಮತ್ತೆ ಪಡೆಯಿರಿ",
  "clear": "ಸ್ಪಷ್ಟ",
  "createNextNumber": "ಮುಂದಿನ ಸಂಖ್ಯೆಯನ್ನು ರಚಿಸಿ",



  "podMaintenance": "ಪೋಡ್ ನಿರ್ವಹಣೆ",
  "podName": "ಪೋಡ್ ಹೆಸರು",
  "createPodName": "ಪೋಡ್ ಹೆಸರು ರಚಿಸಿ",
  "podLayout": "ಪೋಡ್ ವಿನ್ಯಾಸ",
  "kafkaIntegration": "ಕಾಫ್ಕಾ ಇಂಟಿಗ್ರೇಶನ್",
  "kafkaId": "ಕಾಫ್ಕಾ ಐಡಿ",
  "operationCanBeChanged": "ಕ್ರಿಯೆ ಬದಲಾಯಿಸಲಾಗುತ್ತದೆ",
  "resourceCanBeChanged": "ಆಸ್ಪತ್ರೆ ಬದಲಾಯಿಸಬಹುದು",
  "showQuantity": "ಮಟ್ಟವನ್ನು ತೋರಿಸಿ",
  "documentName": "ಡಾಕ್ಯುಮೆಂಟ ಹೆಸರು",
  "sessionTimeout": "ಸೆಷನ್ ಟೈಮ್ಔಟ್",
  "refreshRate": "ರಿಫ್ರೆಶ್ ಶ್ರೇಣಿಯು",
  "podType": "ಪೋಡ್ ಪ್ರಕಾರ",
  "copyPod": "ಪೋಡ್ ನಕಲು ಮಾಡಿ",
  "updatePod": "ಪೋಡ್ ನವೀಕರಿಸಿ",
  "recipientName": "ಸ್ವೀಕರಿಸುವವರ ಹೆಸರು",
  "recipientId": "ಸ್ವೀಕರಿಸುವವರ ಐಡಿ",
  "buttonId": "ಬಟನ್ ಐಡಿ",
  "buttonLabel": "ಬಟನ್ ಲೇಬಲ್",
  "buttonType": "ಬಟನ್ ಪ್ರಕಾರ",
  "buttons": "ಬಟನ್ಗಳು",
  "listOptions": "ಓಹುಪರಿವಾರ",
  "podSelections": "ಪೋಡ್ ಆಯ್ಕೆಗಳು",
  "printers": "ಮುದ್ರಕಗಳು",
  "home": "ಮನೆ",
  "buttonSize": "ಬಟನ್ ಗಾತ್ರ",
  "imageIcon": "ಇಮೇಜ್ ಐಕಾನ್",
  "hotKey": "ಹಾಟ್ ಕೀ",
  "buttonLocation": "ಬಟನ್ ಸ್ಥಳ",
  "podSelection": "ಪೋಡ್ ಆಯ್ಕೆ",
  "activitySequence": "ಚಟುವಟಿಕೆ ಕ್ರಮ",
  "pluginLocation": "ಪ್ಲಗಿನ್ ಸ್ಥಳ",
  "clearsPcu": "ಪಿಸಿಯು ಅಳಿಸಿ",
  "fixed": "ನಿರ್ಧರಿತ",
  "createNewPod": "ಹೊಸ ಪೊಡ್ ರಚಿಸಿ",
  "panelLayout": "ಪ್ಯಾನಲ್ ವಿನ್ಯಾಸ",
  "selectDefaultOperation": "ಮೂಲ ಕ್ರಿಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectDefaultResource": "ಮೂಲ ಸಂಪತ್ತನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectDocumentName": "ಡಾಕ್ಯುಮೆಂಟ್ ಹೆಸರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "browseWorkList": "ಕೆಲಸದ ಪಟ್ಟಿಯನ್ನು ವೀಕ್ಷಿಸಿ",
  "podWorkList": "ಪೋಡ್ ಕೆಲಸದ ಪಟ್ಟಿಯು",
  "assembleList": "ಆಸಂಬ್ಲಿ ಪಟ್ಟಿಯು",
  "dcCollectList": "ಡಿಸಿ ಸಂ��್ರಹ ಪಟ್ಟಿಯು",
  "toolList": "ಉಪಕರಣ ಪಟ್ಟಿಯು",
  "workInstructionList": "ಕೆಲಸದ ಸೂಚನೆಯ ಪಟ್ಟಿಯು",
  "dcEntryList": "ಡಿಸಿ ಎಂಟ್ರಿ ಪಟ್ಟಿಯು",
  "subStepList": "ಉಪ ಹಂತಗಳ ಪಟ್ಟಿ���ು",
  "mainInput": "ಮೂಲ ಇನ್ಪುಟ್",
  "mainInputHotKey": "ಮೂಲ ಇನ್ಪುಟ್ ಹಾಟ್ ಕೀ",
  "infoLine1": "ಮಾಹಿತಿ ಸಾಲು 1",
  "infoLine2": "ಮಾಹಿತಿ ಸಾಲು 2",
  "documentPrinter": "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಿಂಟರ್",
  "labelPrinter": "ಲೇಬಲ್ ಪ್ರಿಂಟರ್",
  "travelerPrinter": "ಮ್ಯಾಪರ್ ಪ್ರಿಂಟರ್",
  "materialInwardManagement": "ವಸ್ತು ಒಳಹೋಗುವ ನಿರ್ವಹಣೆ",

  "users": "ಬಳಕೆದಾರರು",
  "userGroupMaintenance": "ಬಳಕೆದಾರ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "selectPod": "ಪಾಡ್ ಆಯ್ಕೆ ಮಾಡಿ",
  "availableUsers": "ಉಪಲಭ್ಯ ಬಳಕೆದಾರರು",
  "assignedUsers": "ನಿಯೋಜಿತ ಬಳಕೆದಾರರು",
  "availableActivityGroups": "ಉಪಲಭ್ಯ ಚಟುವಟಿಕೆ ಗುಂಪುಗಳು",
  "assignedActivityGroups": "ನಿಯೋಜಿತ ಚಟುವಟಿಕೆ ಗುಂಪುಗಳು",


  "pickListManagement": "ಪಿಕ್ ಲಿಸ್ಟ್ ನಿರ್ವಹಣೆ",
  "pickListNo": "ಪಿಕ್ ಲಿಸ್ಟ್ ನಂ",
  "orderNo": "ಆರ್ಡರ್ ನಂ",
  "generate": "ಸೃಷ್ಟಿ",
  "itemCode": "ಐಟಂ ಕೋಡ್",
  "itemDescription": "ಐಟಂ ವಿವರಣೆ",
  "qtyOrdered": "ಆರ್ಡರ್ ಮಾಡಿರುವ ಪ್ರಮಾಣ",
  "qtyPicked": "ಹೊರಹಾಕಿದ ಪ್ರಮಾಣ",
  "location": "ಸ್ಥಳ",
  "warehouse": "ಗೋದಾಮು",
  "pick": "ತಗೆ",
  "updatePick": "ತಗೆಯುವುದು ನವೀಕರಿಸಿ",
  "print": "ಮುದ್ರಣ",
  "selectOrder": "ಆರ್ಡರ್ ಆಯ್ಕೆ ಮಾಡಿ",
  "resourceMaintenance": "ಸಾಧನ ನಿರ್ವಹಣೆ",
  "createResource": "ಸಾಧನವನ್ನು ರಚಿಸು",
  "opcTag": "ಓಪಿಸಿ ಟ್ಯಾಗ್",
  "processResource": "ಸಾಧನವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸು",
  "erpEquipmentNumber": "ಈರಪಿ ಸಾಧನ ಸಂಖ್ಯೆ",
  "erpPlantNumber": "ಈರಪಿ ಗಿಡ ಸಂಖ್ಯೆ",
  "availableResource": "ಲಭ್ಯವಿರುವ ಸಂಪತ್ತು",
  "assignedResource": "ನಿಯೋಜಿತ ಸಂಪತ್ತು",
  "tagName": "ಟ್ಯಾಗ್ ಹೆಸರು",
  "tagUrl": "ಟ್ಯಾಗ್ URL",
  "identity": "ಪರಿಚಯ",
  "selectCertification": "ಪ್ರಮಾಣಪತ್ರ ಆಯ್ಕೆ ಮಾಡಿ",
  "cycleTimeMaintenance": "ಚಕ್ರ ಕಾಲ ನಿರ್ವಹಣೆ",
  "dataType": "ಡೇಟಾ ಪ್ರಕಾರ",
  "manageAlternateComponents": "ಬದಲಿಯಾದ ಘಟಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  "manageParentComponents": "ಮೂಲ ಘಟಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  "selectComponent": "ಪೊರೆಯ ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAssemblyOperation": "ಸಂಗ್ರಹಣ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAssemblyDataType": "ಸಂಗ್ರಹಣ ಡೇಟಾ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectAlternateComponent": "ಬದಲಿ ಘಟಕವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "selectOperation": "ಕ್ರಿಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "selectMaterial": "ವಸ್ತುವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "name": "ಹೆಸರು",
  "operationalSettingAppTitle": "ಆಪರೇಶನಲ್ ಸೆಟಿಂಗ್",
  "reset": "ಮೀಡು",
  "uomCode": "ಯುಒಎಂ ಕೋಡ್",
  "selectList": "ಪಟ್ಟಿ ಆಯ್ಕೆ ಮಾಡಿ",
  "list": "ಪಟ್ಟಿ",
  "selectPrinters": "ಮುದ್ರಕಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "deleteMsg": "ನೀವು ಈ ಮುಂದಿನ ಸಂಖ್ಯೆಯನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
  "parameter": "ಪ್ಯಾರಾಮೀಟರ್",
  "enterFullScreen": "ಪೂರ್ಣ ಪರದೆಯೊಳಗೆ ನುಸುಳಿ",
  "exitFullScreen": "ಪೂರ್ಣ ಪರೆಯಿಂದ ಹೊರಬರಿ",
  "release": "ಬಿಡುಗಡೆ",
  "shopOrderRelease": "ದೂಸು ಆದೇಶ ಬಿಡುಗಡೆ",
  "qtyToRelease": "ಬಿಡುಗಡೆಗೆ ಪ್ರಮಾಣ",
  "addToNewProcessLot": "ಹೊಸ ಪ್ರಕ್ರಿಯೆ ಸಮೂಹದಲ್ಲಿ ಸೇರಿಸಿ",
  "availableQtyToRelease": "ಬಿಡುಗಡೆಗೆ ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "flowChart": "ಪ್ರವಾಹ ಚಾರ್ಟ್",
  "serialBatchNumber": "ಸೀರಿಯಲ್ ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "bnoQuantity": "ಬಿಎನ್‌ಒ ಪ್ರಮಾಣ",
  "bno": "ಬಿಎನ್‌ಒ",
  "detail": "ವಿವರ",
  "dcGroup": "ಡಿಸಿ ಗುಂಪು",
  "viewPdf": "ಪಿಡಿಎಫ್ ವೀಕ್ಷಿಸಿ",


  // ============================== ITEM GROUP ========================
  "itemGroupAppTitle": "ಐಟಂ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "groupDescription": "ಗುಂಪು ವಿವರಣೆ",
  "unitPrice": "ಘಟಕ ಬೆಲೆ",
  "groupMember": "ಗುಂಪು ಸದಸ್ಯ",
  "createItemGroup": "ಐಟಂ ಗುಂಪು ರಚಿಸಿ",
  "itemGroupDeleteMessage": "ನೀವು ಈ ಐಟಂ ಗುಂಪನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ",

  "erpPlantMaintenanceOrder": "ಇಆರ್‌ಪಿ ಸಂಗ್ರಹಣಾ ಆದೇಶ",
  "availableResourceTypes": "ಕನಿಷ್ಠ ಸಂಪತ್ತುಗಳ ಪ್ರಕಾರ",
  "assignedResourceTypes": "ನಿಯೋಜಿತ ಸಂಪತ್ತುಗಳ ಪ್ರಕಾರ",
  "copyResource": "ನಕಲಿ ಸಂಪತ್ತು",
  "selectMethod": "ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "method": "ವಿಧಾನ",



  "resourceTypeMaintenance": "ಸಂಪತ್ತು ಪ್ರಕಾರ ನಿರ್ವಹಣೆ",
  "resourceTypeDescription": "ಸಂಪತ್ತು ಪ್ರಕಾರ ವಿವರಣೆ",
  "resourceMemberList": "ಸಂಪತ್ತು ಸದಸ್ಯರ ಪಟ್ಟಿ",
  "createResourceType": "ಸಂಪತ್ತು ಪ್ರಕಾರ ಸೃಷ್ಟಿಸಿ",
  "createUserGroup": "ಬಳಕೆದಾರ ಗುಂಪನ್ನು ರಚಿಸಿ",

  "customdataMaintenance": "ಕಸ್ಟಮ್ ಡೇಟಾ ನಿರ್ವಹಣೆ",
  "data field": "ಡೇಟಾ ಪ್ರಕಾರ",
  "field label": "ಪ್ರಕಾರ ಲೇಬಲ್",
  "required": "ಅಗತ್ಯವಿರುವ",
  "selectdataField": "ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ",

  // ============================================== DATA FIELD ===========================================
  "dataField": "ಡೇಟಾ ಕ್ಷೇತ್ರ",
  "fieldLabel": "ಕ್ಷೇತ್ರ ಲೇಬಲ್",
  "dataFieldAppTitle": "ಡೇಟಾ ಕ್ಷೇತ್ರ ನಿರ್ವಹಣೆ",
  "maskGroup": "ಮಾಸ್ಕ್ ಗುಂಪು",
  "preSaveActivity": "ಉಳಿಸುವ ಮೊದಲಿನ ಚಟುವಟಿಕೆ",
  "isTrackable": "ಟ್ರ್ಯಾಕ್ ಮಾಡಬಹುದಾದುದು",
  "qmSelectedSet": "QM ಆಯ್ಕೆ ಮಾಡಿದ ಸೆಟ್",
  "isMrfRef": "MRF ಉಲ್ಲೇಖವೇ",
  "browseIcon": "ಬ್ರೌಸ್ ಐಕಾನ್",
  "defaultLabel": "ಡೀಫಾಲ್ಟ್ ಲೇಬಲ್",
  "fieldValue": "ಕ್ಷೇತ್ರ ಮೌಲ್ಯ",
  "labelValue": "ಲೇಬಲ್ ಮೌಲ್ಯ",
  "api": "ಎಪಿಐ",
  "width": "ಅಗಲ",
  "parameters": "ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು",
  "title": "ಶೀರ್ಷಿಕೆ",
  "editValues": "ಮೌಲ್ಯಗಳನ್ನು ಸಂಪಾದಿಸಿ",
  "createDataField": "ಡೇಟಾ ಫೀಲ್ಡ್ ರಚಿಸಿ",

  // ============================================== DATA TYPE ===========================================

  "dataTypeAppTitle": "ಡೇಟಾ ಪ್ರಕಾರ ನಿರ್ವಹಣೆ",
  "createDataType": "ಡೇಟಾ ಪ್ರಕಾರವನ್ನು ರಚಿಸಿ",
  "selectDataField": "ಡೇಟಾ ಕ್ಷೇತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "listDetails": "ಪಟ್ಟಿ ವಿವರಗಳು",

  "order": "ಆದೇಶ",
  "componentToScan": "ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಘಟಕ",
  "assembled": "ಸಂಪೂರ್ಣಗೊಂಡವು",
  "assemble": "ಸೆಟ್ಗಳನ್ನು ಸೇರಿಸಿ",
  "remaining": "ಉಳಿದಿರುವುದು",
  "dataAttribute": "ಡೇಟಾ ಗುಣಲಕ್ಷಣ",
  "returnToPod": "POD ಗೆ ಹಿಂದಿರುಗಿಸಿ",
  "confirmCreateDataField": "ಡೇಟಾ ಕ್ಷೇತ್ರ ಕಂಡುಬಂದಿಲ್ಲ, ನೀವು ಈ ಡೇಟಾ ಕ್ಷೇತ್ರವನ್ನು ರಚಿಸಲು ಬಯಸುತ್ತೀರಾ",
  "attachmentList": "ಅಟಾಚ್ಮೆಂಟ್ ಪಟ್ಟಿ",

  // ============================================= DC PLUGIN ===========================================
  "parameterList": "ಪ್ಯಾರಾಮೀಟರ್ ಪಟ್ಟಿ",
  "showDetails": "ವಿವರಗಳನ್ನು ತೋರಿಸಿ",
  "collectData": "ಡೇಟಾ ಸಂಗ್ರಹಿಸಿ",
  "saveDraft": "ಮಸೂದೆಯನ್ನು ಉಳಿಸಿ",
  "submit": "ಸಲ್ಲಿಸು",
  "dataFieldList": "ಡೇಟಾ ಕ್ಷೇತ್ರ ಪಟ್ಟಿ",
  "collectedDCParameterList": "ಸಂಗ್ರಹಿತ ಡಿಸಿ ಪ್ಯಾರಾಮೀಟರ್ ಪಟ್ಟಿ",
  "returnToDCList": "ಡಿಸಿ ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ",
  "range": "ಶ್ರೇಣಿಯ",
  "dateTime": "ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "collectionMethod": "ಸಂಗ್ರಹ ವಿಧಾನ",
  "parameterName": "ಪ್ಯಾರಾಮೀಟರ್ ಹೆಸರು",
  "collectDataAt": "ಡೇಟಾ ಸಂಗ್ರಹಿಸಲು",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "ಪಠ್ಯ ಸೂಚನೆ", // Kannada
  "urlInstruction": "ಯುಆರ್‌ಎಲ್ ಸೂಚನೆ",
  "instructionType": "ನಿರ್ದೇಶನ ಪ್ರಕಾರ",
  "WorkInstruction_Description": "ವಿವರಣೆ",
  "WorkInstructionID_Revision": "ಕೆಲಸದ ನಿರ್ದೇಶನ / ಪರಿಷ್ಕರಣೆ",
  "Operation_StepId": "ಚಾಲನೆ ಹಂತ ಐಡಿ",
  "StepId": "ಹಂತ ಐಡಿ",


  "workInstructionMaintenance": "ಕೆಲಸದ ಸೂಚನೆ ನಿರ್ವಹಣೆ",
  "workInstruction": "ಕೆಲಸದ ಸೂಚನೆ",
  "createWorkInstruction": "ಕೆಲಸದ ಸೂಚನೆ ರಚಿಸಿ",
  "alwaysShowInNewWindow": "ಯಾವಾಗಲೂ ಹೊಸ ಕಿಟಕಿಯಲ್ಲಿ ತೋರಿಸಿ",
  "logViewing": "ಲಾಗ್ ವೀಕ್ಷಣೆ",
  "changeAlert": "ಬದಲಾವಣೆ ಎಚ್ಚರಿಕೆ",
  "erpWi": "ERP ಕೆಲಸದ ಸೂಚನೆ",
  "text": "ಪಠ್ಯ",
  "url": "ಯುಆರ್‌ಎಲ್",
  "file": "ಕಡತ",

  // ================================== SCRAP AND USER =======================

  "pcu/shopOrder/processLot": "ಪಿಸಿಯು / ಶಾಪ್ ಆರ್ಡರ್ / ಪ್ರೊಸೆಸ್ ಲಾಟ್",
  "comments": "ಟಿಪ್ಪಣಿಗಳು",
  "scrap": "ತ್ಯಾಜ್ಯ",
  "unscrap": "ತ್ಯಾಜ್ಯ ರದ್ದು",
  "Scrap": "ತ್ಯಾಜ್ಯ",
  "Unscrap": "ತ್ಯಾಜ್ಯ ರದ್ದು",
  "scrapUnscrapTitle": "ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ",
  "confirmPassword": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  "password": "ಪಾಸ್‌ವರ್ಡ್",
  "selectSites": "ಸೈಟ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "PCU": "ಪಿಸಿಯು",
  "Shop Order": "ಶಾಪ್ ಆರ್ಡರ್",
  "Process Lot": "ಪ್ರೊಸೆಸ್ ಲಾಟ್",
  "workflowIntegrationMaintenance": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟ ನಿರ್ವಹಣೆ",
  "workflowIntegration": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟ",
  "createWorkflowIntegration": "ಕಾರ್ಯಪ್ರವಾಹ ಒಕ್ಕೂಟವನ್ನು ರಚಿಸಿ",
  "identifier": "ಗುರುತಿಕೆ",
  "messageId": "ಸಂದೇಶ ಐಡಿ",
  "processBy": "ಇದರ ಮೂಲಕ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ",
  "transformationType": "ರಿವರ್ತನೆ ಪ್ರಕಾರ",
  "preprocessJolt": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್",
  "preprocessApi": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ API",
  "serviceApi": "ಸೇವಾ API",
  "expectedSplits": "ನಿರೀಕ್ಷಿತ ವಿಭಜನೆಗಳು",
  "postProcessJolt": "ಪ್ರಕ್ರಿಯೆ ನಂತರದ ಜೋಲ್ಟ್",
  "postProcessApi": "ಪ್ರಕ್ರಿಯೆ ನಂತರದ API",
  "passHandler": "ಹಸ್ತಾಂತರ ಮಾಡುವವನು",
  "failHandler": "ಅನುತ್ತೀರ್ಣ ಮಾಡುವವನು",
  "processTransformation": "ಪ್ರಕ್ರಿಯೆ ಪರಿವರ್ತನೆ",

  // ============================================== Jolt Spec ===========================================
  "specName": "ಸ್ಪೆಕ್ ಹೆಸರು",
  "specNamePlaceholder": "ಸ್ಪೆಕ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "specNameRequired": "ದಯವಿಟ್ಟು ಸ್ಪೆಕ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ!",

  "typePlaceholder": "ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "typeRequired": "ದಯವಿಟ್ಟು ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ!",
  "joltSpec": "ಜೋಲ್ಟ್ ಸ್ಪೆಕ್",
  "joltSpecPlaceholder": "ಜೋಲ್ಟ್ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "xsltSpec": "XSLT ಸ್ಪೆಕ್",
  "xsltSpecPlaceholder": "XSLT ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "encodeXsltSpec": "ಎನ್ಕೋಡ್ XSLT ಸ್ಪೆಕ್",
  "encodeXsltSpecPlaceholder": "ಎನ್ಕೋಡ್ ಮಾಡಿದ XSLT ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "jsonAta": "JsonAta ಸ್ಪೆಕ್",
  "jsonAtaPlaceholder": "JsonAta ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "encodedJsonAtaSpec": "ಎನ್ಕೋಡ್ ಮಾಡಿದ JsonAta ಸ್ಪೆಕ್",
  "encodedJsonAtaSpecPlaceholder": "ಎನ್ಕೋಡ್ ಮಾಡಿದ JsonAta ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",

  "joltAppTitle": "ಜೋಲ್ಟ್ ಸ್ಪೆಕ್ ನಿರ್ವಹಣೆ",
  "createSpec": "ಸ್ಪೆಕ್ ರಚಿಸಿ",
  "encode": "ಎನ್‌ಕೋಡ್",
  "decode": "ಡಿಕೋಡ್",
  "spec": "ಸ್ಪೆಕ್",
  "decodeXsltSpec": "ಡಿಕೋಡ್ ��ಾಡಿದ XSLT ವಿವರಣೆ",
  "decodeJsonAtaSpec": "ಡಿಕೋಡ್ ಮಾಡಿದ JsonAta ವಿವರಣೆ",

  "entityType": "ಘಟಕದ ಪ್ರಕಾರ",
  "eventIntervalSeconds": "ಘಟನೆಯ ಅಂತರ ಸೆಕೆಂಡುಗಳು",
  "cronExpression": "ಕ್ರೋನ್ ಅ��ಿವ್ಯಕ್ತಿ",
  "entityName": "ಘಟಕದ ಹೆಸರು",

  "edit": "ಸಂಪಾದಿಸು",
  "runJob": "ಕೆಲಸ ಚಲಾಯಿಸು",
  "stopScheduler": "ನಿಯೋಜಕವನ್ನು ನಿಲ್ಲಿಸು",
  "machineStatusChange": "ಯಂತ್ರ ಸ್ಥಿತಿ ಬದಲಾವಣೆ",

  "apiToProcess": "ಪ್ರಕ್ರಿಯೆಗೆ API",
  "selectPreProcessJolt": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectPostProcessJolt": "ಪೋಸ್ಟ್ ಪ್ರಕ್ರಿಯೆ ಜೋಲ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "selectPreProcessXSLT": "ಪೂರ್ವ ಪ್ರಕ್ರಿಯೆ XSLT ಆಯ್ಕೆಮಾಡಿ",
  "processJoltXslt": "ಜೋಲ್ಟ್ XSLT ಪ್ರಕ್ರಿಯೆ",
  "splitConfigurations": "ವಿಭಜನೆ ಕಾನ್ಫಿಗರೆಷನ್",
  "splitIdentifier": "ವಿಭಜನೆ ಗುರುತಿಸುವಿಕೆ",
  "conditional": "ಷರತ್ತುಬದ್ಧ",
  "parallel": "ಸಮಾನಾಂತರ",
  "anyOrder": "ಯಾವುದೇ ಕ್ರಮ",

  "orderNumber": "ಆದೇಶ ಸಂಖ್ಯೆ",
  "recipeVersion": "ವಿನ್ಯಾಸ ಆವೃತ್ತಿ",
  "recipeNo": "ವಿನ್ಯಾಸ ಸಂಖ್ಯೆ",
  "targetQuantity": "ಗುರಿ ಪ್ರಮಾಣ",
  "startDate": "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
  "finishDate": "ಅಂತಿಮ ದಿನಾಂಕ",
  "schedFinTime": "ನಿಗದಿತ ಅಂತಿಮ ಸಮಯ",
  "schedStartTime": "ನಿಗದಿತ ಪ್ರಾರಂಭ ಸಮಯ",
  "selectRecipeNo": "ವಿನ್ಯಾಸ ಸಂಖ್ಯೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "batchNumber": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "batchNumberQuantity": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ ಪ್ರಮಾಣ",

  // ============================================== Process Order Plugin ===========================================
  "complete": "ಪೂರ್ಣ",
  "start": "ಪ್ರಾರಂಭಿಸಿ",

  // ============================================== NC Group ===========================================
  "ncGroup": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ",
  "ncCode": "ಎನ್‌ಸಿ ಕೋಡ್",
  "ncGroups": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹಗಳು",
  "ncGroupAppTitle": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ ನಿರ್ವಹಣೆ",
  "ncGroupFilterPriority": "ನಿಕ್ಷಿಪ್ತ ಸಮೂಹ ಫಿಲ್ಟರ್ ಪ್ರಾಥಮಿಕೆ",
  "validAtAllOperations": "ಎಲ್ಲಾ ಕಾರ್ಯಗಳಲ್ಲಿ ವಾಸ್ತವವಾಗಿರುತ್ತದೆ",
  // New additions
  "parameterBo": "ಪ್ಯಾರಾಮೀಟರ್ ಬಿಒ",
  "operationBO": "ಕಾರ್ಯಾಚರಣೆ ಬಿಒ",
  "dcGroupBO": "ಡಿಸಿ ಗುಂಪು ಬಿಒ",
  "pcuBO": "ಪಿಸಿಯು ಬಿಒ",
  "testDateTime": "ಪರೀಕ್ಷೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "dcGroupDescription": "ಡಿಸಿ ಗುಂಪು ವಿವರಣೆ",
  "subStepID": "ಉಪ ಹಂತ ಐಡಿ",
  "measureStatus": "ಅಳತೆ ಸ್ಥಿತಿ",
  "measureType": "ಅಳತೆ ಪ್ರಕಾರ",
  "unitOfMeasure": "ಅಳತೆಯ ಏಕಕ",
  "highLimit": "ಉನ್ನತ ಮಿತಿ",
  "lowLimit": "ಕಡಿಮೆ ಮಿತಿ",
  "expected": "ನಿರೀಕ್ಷಿತ",
  "actualNum": "ವಾಸ್ತವಿಕ ಸಂಖ್ಯೆ",
  "dcComment": "ಡಿಸಿ ಕಾಮೆಂಟ್",
  "usedLimitSeq": "ಬಳಸಿದ ಮಿತಿ ಕ್ರಮ",
  "elapsedTime": "ಕಳೆದ ಸಮಯ",
  "originalActual": "ಮೂಲ ವಾಸ್ತವಿಕ",
  "originalDcComment": "ಮೂಲ ಡಿಸಿ ಕಾಮೆಂಟ್",
  "originalTestDateTime": "ಮೂಲ ಪರೀಕ್ಷೆ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "edited": "ಸಂಪಾದಿಸಲಾಗಿದೆ",
  "editedUserBO": "ಸಂಪಾದಿಸಿದ ಬಳಕೆದಾರ ಬಿಒ",
  "editedDateTime": "ಸಂಪಾದಿಸಿದ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ",
  "internalMeasureID": "ಆಂತರಿಕ ಅಳತೆ ಐಡಿ",
  "routingBO": "ರೌಟಿಂಗ್ ಬಿಒ",
  "stepID": "ಹಂತ ಐಡಿ",
  "userBO": "ಬಳಕೆದಾರ ಬಿಒ",
  "overrideUserBO": "ಓವರ್‌ರೈಡ್ ಬಳಕೆದಾರ ಬಿಒ",
  "dcGroupVersion": "ಡಿಸಿ ಗುಂಪು ಆವೃತ್ತಿ",
  "erpSent": "ಇಆರ್‌ಪಿ ಕಳುಹಿಸಲಾಗಿದೆ",
  "qmAccepted": "QM ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  "ncCodeDPMOCategory": "ಎನ್‌ಸಿ ಕೆಡ್ ಡಿಪಿಎಂಒ ಶ್ರೆಂಚ",
  "operationList": "ಕಾರ್ಯಾಚರಣೆ ಪಟ್ಟಿ",
  "createNCGroup": "ಎನ್‌ಸಿ ಸಮೂಹ ರಚಿಸಿ",
  "availableNCCodes": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ ಕೆಡ್",
  "assignNCCodes": "ಎನ್‌ಸಿ ಕೆಡ್ ಸೌಂಪಿಸಿ",
  "ncGroupDeleteMessage": "ನೀವು ಈ ಎನ್‌ಸಿ ಸಮೂಹವನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?",
  "assignedNC": "ಅಸ್ಥಾಯಿಸಿದ ಎನ್‌ಸಿ",
  "availableNC": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ",
  "logNc": "ಲೋಗ್ ಏನ್‌ಸಿ",
  "done": "ಪೂರ್ಣ",
  "NcCodeMaintenance": "ಎನ್‌ಸಿ ಕೋಡ್ ನಿರ್ವಹಣೆ",
  "NC Code": "ಎನ್‌ಸಿ ಕೋಡ್",
  "operationGroups": "ಆಪರೇಷನ್ ಗುಂಪುಗಳು",
  "dispositionRoutings": "ವ್ಯವಸ್ಥಿತ ಮಾರ್ಗಗಳು",
  "NC Groups": "ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "secondaries": "ದ್ವಿತೀಯಗಳು",
  "createNcCode": "ಎನ್‌ಸಿ ಕೋಡ್ ರಚಿಸಿ",
  "assignNCtoComponent": "ಕಾಂಪೋನೆಂಟ್‌ಗೆ ಎನ್‌ಸಿ ಅಸೈನ್ ಮಾಡಿ",
  "ncCategory": "ಎನ್‌ಸಿ ವರ್ಗ",
  "dpmoCategory": "ಡಿಪಿಎಂಒ ವರ್ಗ",
  "ncDatatype": "ಎನ್‌ಸಿ ಡೇಟಾ ಪ್ರಕಾರ",
  "collectRequiredNCDataonNC": "ಎನ್‌ಸಿಯಲ್ಲಿ ಅಗತ್ಯವಿರುವ ಡೇಟಾವನ್ನು ಸಂಗ್ರಹಿಸಿ",
  "ncPriority": "ಎನ್‌ಸಿ ಪ್ರಾಮುಖ್ಯತೆ",
  "maximumNCLimit": "ಗರಿಷ್ಠ ಎನ್‌ಸಿ ಮಿತಿ",
  "ncSeverity": "ಎನ್‌ಸಿ ತೀವ್ರತೆ",
  "secondaryCodeSpecialInstruction": "ದ್ವಿತೀಯ ಕೋಡ್ ವಿಶೇಷ ಸೂಚನೆ",
  "canBePrimaryCode": "ಪ್ರಾಥಮಿಕ ಕೋಡ್ ಆಗಬಹುದು",
  "closureRequired": "ಮುಚ್ಚುವಿಕೆ ಅಗತ್ಯವಿದೆ",
  "autoClosePrimaryNC": "ಪ್ರಾಥಮಿಕ ಎನ್‌ಸಿಯನ್ನು ಸ್ವಯಂ ಮುಚ್ಚಿ",
  "autoCloseIncident": "ಸ್ವಯಂ ಮುಚ್ಚುವ ಘಟನೆ",
  "secondaryRequiredForClosure": "ಮುಚ್ಚುವಿಕೆಗೆ ದ್ವಿತೀಯ ಅಗತ್ಯವಿದೆ",
  "erpQNCode": "ERP QN ಕೋಡ್",
  "erpCatalog": "ERP ಕ್ಯಾಟಲಾಗ್",
  "erpCodeGroup": "ERP ಕೋಡ್ ಗುಂಪು",
  "erpCode": "ERP ಕೋಡ್",
  "oeeQualityKPIRelevant": "OEE ಗುಣಮಟ್ಟ KPI ಸಂಬಂಧಿತ",
  "selectNcDatatype": "ಎನ್‌ಸಿ ಡೇಟಾ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "validOperations": "ಮಾನ್ಯವಾದ ಕಾರ್ಯಾಚರಣೆಗಳು",
  "dispositionGroups": "ಸ್ಥಿತಿಗತಿ ಗುಂಪುಗಳು",
  "availableRouting": "ಲಭ್ಯವಿರುವ ಮಾರ್ಗ ನಿರ್ವಾಹಕರು",
  "assignedRouting": "ನಿಯೋಜಿತ ಮಾರ್ಗ ನಿರ್ವಾಹಕರು",
  "availableSecondaries": "ಲಭ್ಯವಿರುವ ದ್ವಿತೀಯಗಳು",
  "assignedSecondaries": "ನಿಯೋಜಿತ ದ್ವಿತೀಯಗಳು",
  "availableNcGroups": "ಉಪಲಬ್ಧ ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "assignedNcGroups": "ಅಸ್ಥಾಯಿಸಿದ ಎನ್‌ಸಿ ಗುಂಪುಗಳು",
  "copyNcCode": "ಎನ್‌ಸಿ ಕೋಡ್ ಕಳೆಯಿರಿ",
  "toolNumberMaintenance": "ಟೂಲ್ ನಂಬರ್ ನಿರ್ವಹಣೆ",
  "toolNumber": "ಟೂಲ್ ನಂಬರ್",
  "toolGroup": "ಟೂಲ್ ಗುಂಪು",
  "qtyAvailable": "ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "erpPlanMaintenanceOrder": "ಇಆರ್‌ಪಿ ಯೋಜನೆ ನಿರ್ವಹಣೆ ಆರ್ಡರ್",
  "toolQty": "ಟೂಲ್ ಪ್ರಮಾಣ",
  "createToolNumber": "ಟೂಲ್ ನಂಬರ್ ರಚಿಸಿ",
  "calibration": "ಕ್ಯಾಲಿಬ್ರೇಷನ್",
  "measurementPoints": "ಮಾಪನ ಪಾಯಿಂಟ್‌ಗಳು",
  "measurementPoint": "ಮಾಪನ ಪಾಯಿಂಟ್",
  "calibrationType": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಪ್ರಕಾರ",
  "calibrationPeriod": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಅವಧಿ",
  "calibrationCount": "ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಸಂಖ್ಯೆ",
  "maximumCalibrationCount": "ಗರಿಷ್ಟ ಕ್ಯಾಲಿಬ್ರೇಷನ್ ಸಂಖ್ಯೆ",
  "expirationDate": "ಅವಧಿ ಮೀರಿದ ದಿನಾಂಕ",
  "displayClosedNc": "ಬಂದ ಏನ್ಸಿ ಪ್ರದರ್ಶಿಸಿ",
  "selectRoute": "ರೌಟಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ",
  "customOrder": "ಕಸ್ಟಮ್ ಆದೇಶ",
  "createToolGroup": "ಸಾಧನ ಗುಂಪು ರಚಿಸಿ",
  "timeBased": "ಸಮಯ ಆಧಾರಿತ",
  "quantityRequired": "ಅಗತ್ಯವಿರುವ ಪ್ರಮಾಣ",
  "erpGroup": "ERP ಗುಂಪು",
  "itemVersion": "ಐಟಂ ಆವೃತ್ತಿ",
  "trackingControl": "ಟ್ರ್ಯಾಕಿಂಗ್ ಕನ್ಟ್ರೋಲ್",
  "toolGroupMaintenance": "ಸಾಧನ ಗುಂಪು ನಿರ್ವಹಣೆ",
  "listConfiguration": "ಪಟ್ಟಿ ಅಮಾವೃತ್ತಿ",
  "multiProcessOrderRelease": "ಏಕಾಧಿಕ ಪ್ರಕ್ರಿಯೆ ಆದೇಶ ಉತ್ಸರ್ಗ",
  "multiProcessOrder": "ಏಕಾಧಿಕ ಪ್ರಕ್ರಿಯೆ ಆದೇಶ",
  "phase": "ಹಂತಗಳು",
  "mrpController": "ಮ್ರ್ಪ್ ನಿಯಂತ್ರಕ",
  "productionScheduler": "ಉತ್ಪಾದನ ಶೇಡ್ಯೂಲರ್",
  "reservationNumber": "ರಿಜರ್ವೇಶನ್ ಸಂಖ್ಯೆ",
  "productionStartDate": "ಉತ್ಪಾದನ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "productionFinishDate": "ಉತ್ಪಾದನ ಅಂತಿಮ ದಿನಾಂಕ",
  "actualStartDate": "ವಾಸ್ತವಿಕ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "actualFinishDate": "ವಾಸ್ತವಿಕ ಅಂತಿಮ ದಿನಾಂಕ",
  "inUse": "ಬಳಸಲಾಗಿದೆ",
  "measuredUom": "ಅಳತೆ ಏಕಕ",
  "entryPhase": "ಪ್ರವೇಶ ಹಂತ",
  "exitPhase": "ನಿಷ್ಕ್ರಿಯ ಹಂತ",
  "entryOperation": "ಪ್ರವೇಶ ಕಾರ್ಯ",
  "lastOperationAtPhase": "ಕಳೆದ ಕಾರ್ಯ",
  "nextPhase": "ಮುಂದಿನ ಹಂತ",

  "accept": "ಸ್ವೀಕರಿಸಿ",
  "partial": "ಆಂಶಿಕ",
  "skip": "ನಿರ್ಗಮಿಸಿ",
  "buyOff": "ಕುರಿಯಾಗಿಸಿ",
  "username": "ಬಳಕೆದಾರ ಹೆಸರು",
  "userAuthentication": "ಬಳಕೆದಾರ ಪ್ರಮಾಣೀಯನ್ನು ಪರಿಶೀಲಿಸಿ",
  "login": "ಪ್ರವೇಶ",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "ಪ್ರಮಾಣೀಕರಣ ನಿರ್ವಹಣೆ",
  "certifications": "ಪ್ರಮಾಣಪತ್ರಗಳು",
  "createCertification": "ಪ್ರಮಾಣಪತ್ರ ರಚಿಸಿ",
  "durationType": "ಅವಧಿ ಪ್ರಕಾರ",
  "maxNumberOfExtensions": "ಗರಿಷ್ಠ ವಿಸ್ತರಣೆಗಳ ಸಂಖ್ಯೆ",
  "maxExtensionDuration": "ಗರಿಷ್ಠ ವಿಸ್ತರಣೆ ಅವಧಿ",
  "assignment": "ನಿಯೋಜನೆ",
  "availableUserGroups": "ಲಭ್ಯವಿರುವ ಬಳಕೆದಾರ ಗುಂಪುಗಳು",
  "assignedUserGroups": "ನಿಯೋಜಿತ ಬಳಕೆದಾರ ಗುಂಪುಗಳು",
  "measurementpoints": "ಅಳತೆ ಪಾಯಿಂಟ್‌ಗಳು",
  "copyCertification": "ಪ್ರಮಾಣಪತ್ರ ಕಳೆಯಿರಿ",
  "activityId": "ಚಟುವಟಿಕೆ ಐಡಿ",
  "selectPcu": "ಪ್ರಮಾಣಪತ್ರ ಕಳೆಯಿರಿ",
  "selectBatchNo": "ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "createPodMaintenance": "ಪ್ರಮಾಣಪತ್ರ ರಚಿಸಿ",
  "reloadWorkList": "ಕಾರ್ಯ ಪಟ್ಟಿ ಮರೆಯಿರಿ",
  "reloadResource": "ಸಂಸ್ಥಾನ ಮರೆಯಿರಿ",
  "settings": "ಸೆಟಿಂಗ್ಸ್",
  "layout": "ಲೇಆಉಟ್",
  "PCUOrBatchNumberBrowseActivity": "PCU ಅಥವಾ ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಬ್ರಾಉಜ್ ಚಟುವಟಿಕೆ",
  "PodWorkListActivity": "ಪ್ರಮಾಣಪತ್ರ ಕಾರ್ಯ ಪಟ್ಟಿ ಚಟುವಟಿಕೆ",
  "ButtonActivityInWork": "ಕಾರ್ಯ ಚಟುವಟಿಕೆ",
  "ButtonActivityInQueue": "ಕ್ರಮ ಚಟುವಟಿಕೆ",
  "OnTabOutOfOperation": "ಕಾರ್ಯ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "OnTabOutOfWorkcenter": "ವರ್ಕ್‌ಸೆಂಟರ್ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "OnTabOutOfResource": "ಸಂಸ್ಥಾನ ಸ್ಥಳದಲ್ಲಿ ಬಾಹ್ಯಾಸ್ಥಿತಿ",
  "UpdateFieldsToSession": "ಸಮಯದಲ್ಲಿ ಕ್ಷೇತ್ರಗಳನ್ನು ಅಪ್ಡೇಟ್ ಮಾಡಿ",
  "scrapQuantity": "ಸ್ಕ್ರೇಪ್ ಪ್ರಮಾಣ",
  "subPod": "ಉಪ ಪ್ರಮಾಣಪತ್ರ",
  "podCategory": "ಪ್ರಮಾಣಪತ್ರ ಶ್ರೆಂಚ",
  "buttonActivityInQueue": "ಕ್ರಮ ಚಟುವಟಿಕೆ",
  "buttonActivityInWork": "ಕಾರ್ಯ ಚಟುವಟಿಕೆ",
  "activityDescription": "ಗತಿವಿಧಿ ವಿವರಣೆ",
  "panel": "ಪ್ಯಾನೆಲ್",
  "defaultPlugin": "ಡಿಫಾಲ್ಟ್ ಪ್ಲಗಿನ್",
  "otherPlugin": "ಇತರ ಪ್ಲಗಿನ್",
  // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್ ನಿರ್ವಹಣೆ",
  "lineClearance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್",
  "templateName": "ಟೆಂಪ್ಲೇಟ್ ಹೆಸರು",
  "clearanceTimeLimit": "ಕ್ಲಿಯರೆನ್ಸ್ ಸಮಯ ಮಿತಿ",
  "maxPendingTasks": "ಗರಿಷ್ಠ ಬಾಕಿ ಕಾರ್ಯಗಳು",
  "clearanceReminderInterval": "ಕ್ಲಿಯರೆನ್ಸ್ ರಿಮೈಂಡರ್ ಅಂತರ",
  "notifyOnCompletion": "ಪೂರ್ಣಗೊಂಡಾಗ ಸೂಚಿಸಿ",
  "enablePhotoEvidence": "ಫೋಟೋ ಸಾಕ್ಷ್ಯ ಸಕ್ರಿಯಗೊಳಿಸಿ",
  "associated": "ಸಂಬಂಧಿತ",
  "workcenterId": "ವರ್ಕ್‌ಸೆಂಟರ್ ಐಡಿ",
  "resourceName": "ಸಂಪನ್ಮೂಲ ಹೆಸರು",
  "createLineClearance": "ಲೈನ್ ಕ್ಲಿಯರೆನ್ಸ್ ರಚಿಸಿ",
  "taskid": "ಕಾರ್ಯ ಐಡಿ",
  "taskname": "ಕಾರ್ಯ ಹೆಸರು",
  "mandatory": "ಕಡ್ಡಾಯ",
  "evidencerequired": "ಸಾಕ್ಷ್ಯ ಅಗತ್ಯವಿದೆ",
  "userRoles": "ಬಳಕೆದಾರ ಪಾತ್ರಗಳು",
  "userid": "ಬಳಕೆದಾರ ಐಡಿ",
  "permissions": "ಅನುಮತಿಗಳು",
  "selectUser": "ಬಳಕೆದಾರರನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "tasks": "ಕಾರ್ಯಗಳು",
  "uomConversion": "ಯೂಓಎಂ ರೂಪಾಂತರಣೆ",
  "conversion": "ರೂಪಾಂತರಣೆ",
  "materialCountConversion": "Material Count Conversion",
  "convertUom": "ಯೂಓಎಂ ರೂಪಾಂತರಣೆ",
  "count": "ಗಿನತಿ",
  "conversionDeleteMessage": "ಈ ರೂಪಾಂತರಣೆಯನ್ನು ಅಳಿಸಬೇಕೋ?",
  "baseAmt": "ಆಧಾರ ರಾಶಿ",
  "conversionItem": "ರೂಪಾಂತರಣೆ ಆಇಟಂ",
  "areYouSureDeleteThisSplit": "ಈ ವಿಭಾಜನೆಯನ್ನು ಅಳಿಸಬೇಕೋ?",
  "attach": "ಸೇರಿಸಿ",
  "filePreview": "ಫೋಟೋ ಪೂರ್ವಾವಲೋಕನ",
  "change": "ಬದಲಾಯಿಸಿ",
  "preview": "ಪೂರ್ವಾವಲೋಕನ",
  "reloadSiteConfirmation": "ಈ ಸೈಟ್ ಅಳಿಸಲು ಖಚಿತವಾಗಿಯೇ ಇರುವುದೋ?",
  "phaseCanBeChanged": "ಚರಣ ಬದಲಾಯಿಸಬಹುದು",
  "showResource": "ಸಂಸ್ಥಾನ ದಿಕ್ಕೆ",
  "showOperation": "ಕಾರ್ಯ ದಿಕ್ಕೆ",
  "showPhase": "ಚರಣ ದಿಕ್ಕೆ",
  "auditLogReport": "಑ಡಿಟ್ ಲೋಗ್ ರಿಪೋರ್ಟ್",
  "dataCollectionReport": "ಡೇಟಾ ಕಲೆಕ್ಷನ್ ರಿಪೋರ್ಟ್",
  "dataCollectionGraph": "ಡೇಟಾ ಕಲೆಕ್ಷನ್ ಗ್ರಾಫ್",
  "selectCategory": "ಶ್ರೆಂಚ ಆಯ್ಕೆಮಾಡಿ",
  "currentSetting": "ಪ್ರಸ್ತುತ ಸೆಟಿಂಗ್",
  "date/time": "ದಿನಾಂಕ/ಸಮಯ",
  "changeType": "ಪರಿವರ್ತನ ಪ್ರಕಾರ",
  "dateRange": "ದಿನಾಂಕ ವ್ಯಾಪ್ತಿ",
  "time": "ಸಮಯ",
  "topicConfiguration": "ಟೋಪಿಕ್ ಕೊನ್ಫಿಗರೇಶನ್",
  "createTopicConfiguration": "ಟೋಪಿಕ್ ಕೊನ್ಫಿಗರೇಶನ್ ರಚಿಸಿ",
  "topicName": "ಟೋಪಿಕ್ ಹೆಸರು",
  "apiUrl": "ಏಪಿಐ ಯುಆರ್ಲ್",

  "taskDescription": "ಕಾರ್ಯ ವಿವರಣೆ",
  "evidence": "ಪ್ರಮಾಣ",
  "startedDateTime": "ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "completedDateTime": "ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "reason": "ಕಾರಣ",
  "approved": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  "approvedDateTime": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "approvedBy": "ಸ್ವೀಕರಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "rejectedDateTime": "ರದ್ದುಪಡೆದಾಗ ದಿನಾಂಕ",
  "rejectedBy": "ರದ್ದುಪಡೆದಾಗ ದಿನಾಂಕ",
  "updatedDateTime": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "updatedBy": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "startedBy": "ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "completedBy": "ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "taskName": "ಕಾರ್ಯ ಹೆಸರು",
  "isMandatory": "ಅನಿವಾರ್ಯ",
  "evidenceRequired": "ಪ್ರಮಾಣ ಅಗತ್ಯ",
  "theme": "ಥೈಮ್",
  "cycleTime(sec)": "ಕಾಲಕ್ರಮ ಸಮಯ (ಸೆಕೆಂಡ್)",

  "shiftStart": "ಶಿಫ್ಟ್ ಪ್ರಾರಂಭ",
  "shiftEnd": "ಶಿಫ್ಟ್ ಅಂತಿಮ",
  "shiftAvailableTime": "ಶಿಫ್ಟ್ ಉಪಲಬ್ಧ ಸಮಯ",
  "totalBreakHours": "ಮೊತ್ತ ಬ್ರೇಕ್ ಘಂಟೆಗಳು",
  "createdDatetime": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "updatedDatetime": "ಅಪ್ಡೇಟ್ ದಿನಾಂಕ",
  "createdBy": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "eventData": "ಘಟನೆ ಡೇಟಾ",
  "plant": "ಫುಲಾವಾ",
  "eventType": "ಘಟನೆ ಪ್ರಕಾರ",
  "buyOffAction": "ಖರೀದಿ ಅವಧಿ ಕ್ರಿಯೆ",
  "history": "ಇತಿಹಾಸ",
  "endDate": "ಅಂತಿಮ ದಿನಾಂಕ",
  "selectSite": "ಸೈಟ್ ಆಯ್ಕೆಮಾಡಿ",
  "downtimeType": "ಡೌನ್ಟೈಮ್ ಪ್ರಕಾರ",
  "selectStatus": "ಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ",
  "selectNewStatus": "ಹೊಸ ಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ",
  "selectBatchNumber": "ಬೆಚ್ಚೆ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "selectOrderNumber": "ಆದೇಶ ಸಂಖ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
  "batchStepStatus": "ಬೆಚ್ಚೆ ಸ್ಟೆಪ್ ಸ್ಟ್ಯಾಚ್ ಸ್ಟ್ಯಾಚ್",
  "batchStartedTime": "ಬೆಚ್ಚೆ ಪ್ರಾರಂಭಿಸಲು ದಿನಾಂಕ",
  "batchCompletedTime": "ಬೆಚ್ಚೆ ಪೂರ್ಣಗೊಂಡಾಗ ದಿನಾಂಕ",
  "approval": "ಅನುಮೋದನೆ",
  "PhaseId": "ಚರಣ ಐಡಿ",
  "InQueueQty": "ಕ್ರಮ ಮಾತ್ರ",
  "InWorkQty": "ಕಾರ್ಯ ಮಾತ್ರ",
  "CompleteQty": "ಪೂರ್ಣಗೊಂಡ ಮಾತ್ರ",
  "ScrapQty": "ಸ್ಕ್ರೇಪ್ ಮಾತ್ರ",
  "level": "ಸ್ತರ",
  "message": "ಸಂದೇಶ",

  "activityHookId": "ಚಟುವಟಿಕೆ ಹುಕ್ ಐಡಿ",
  "targetClass": "ಗುರಿ ವರ್ಗ",
  "targetMethod": "ಗುರಿ ವಿಧಾನ",
  "hookType": "ಹುಕ್ ಪ್ರಕಾರ",
  "hookClass": "ಹುಕ್ ವರ್ಗ",
  "hookMethod": "ಹುಕ್ ವಿಧಾನ",
  "executionMode": "ಕಾರ್ಯಗತ ಮೋಡ್",
  "logo": "ಲೋಗೋ",
  "background": "ಬ್ಯಾಕಗ್ರಾಉಂಡ್",
  "color": "ರಂಗ",
  "lineColor": "ವರಿ ರಂಗ",

  "plannedCycleTime": "ಯೋಜನಾ ಕಾಲಕ್ರಮ ಸಮಯ",
  "actualCycleTime": "ವಾಸ್ತವಿಕ ಕಾಲಕ್ರಮ ಸಮಯ",
  "totalBreakInMinutes": "ಮೊತ್ತ ಬ್ರೇಕ್ (ನಿಮಿಷ)",


  "serviceExtension": "ಸೇವಾ ವಿಸ್ತರಣೆ",
  "createServiceExtension": "ಸೇವಾ ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "createExtension": "ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "serviceExtensionAppTitle": "ಸೇವಾ ವಿಸ್ತರಣೆ ರಚಿಸಿ",
  "selectResourceType": "ಸಂಸ್ಥಾನ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "executionPointId": "ಕಾರ್ಯಗತ ಬಿಂದು ಐಡಿ",
  "extensionDeleteMessage": "ಈ ವಿಸ್ತರಣೆಯನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
  "executionPoint": "ಕಾರ್ಯಗತ ಬಿಂದು",
  "extensionActivity": "ವಿಸ್ತರಣಾ ಚಟುವಟಿಕೆ",
  "MaterialDescription": "ಮಾಲ್ ವಿವರಣೆ",
  "releaseTime": "ಉತ್ಸರ್ಹ ಸಮಯ",
  "unitOfMeasurement": "ಯೂಓಎಂ",
  "releaseOrder": "ಏಕಾಧಿಕ ಆದೇಶ",
  "createdDateTime": "ರಚಿಸಲಾಗಿದೆ ದಿನಾಂಕ",
  "releaseQty": "ಉತ್ಸರ್ಹ ಮಾತ್ರ",
  "productionTime": "ಉತ್ಪಾದನ ಸಮಯ",
  "productName": "ಉತ್ಪನ್ನದ ಹೆಸರು",
  "downloadDate": "ಡೌನ್‌ಲೋಡ್ ದಿನಾಂಕ",
  "batchStatus": "ಬೆಚ್ಚೆ ಸ್ಥಿತಿ",


  "createConfiguration": "ಕಾನ್ಫಿಗರೇಷನ್ ರಚಿಸಿ",
  "apiConfiguration": "ಎಪಿಐ ಕಾನ್ಫಿಗರೇಷನ್",
  "storedProcedure": "ಸ್ಟೋರ್ಡ್ ಪ್ರೊಸೀಜರ್",
  "httpMethod": "ಎಚ್ಟಿಟಿಪಿ ವಿಧಾನ",
  "inputParameters": "ಇನ್ಪುಟ್ ಪಾರಾಮೀಟರ್ಸ್",
  "outputStructure": "ಔಟ್ಪುಟ್ ಸ್ಟ್ರಕ್ಚರ್",
  "apiName": "ಎಪಿಐ ಹೆಸರು",
  "deleteApiConfigMessage": "ಈ ಕಾನ್ಫಿಗರೇಷನ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
  "apiConfigMaintenance": "ಎಪಿಐ ಕಾನ್ಫಿಗರೇಷನ್ ನಿರ್ವಹಣೆ",
  "configuration": "ಕಾನ್ಫಿಗರೇಷನ್",

  "shiftId": "ಶಿಫ್ಟ್ ಐಡಿ",
  "selectShift": "ಶಿಫ್ಟ್ ಆಯ್ಕೆಮಾಡಿ",

  "productGroup": "ಉತ್ಪಾದ ಸಮೂಹ",
  "selectProductGroup": "ಉತ್ಪಾದ ಸಮೂಹ ಆಯ್ಕೆಮಾಡಿ",

  "attachmentType": "ಲಗತ್ತಿನ ಪ್ರಕಾರ",
  "attachedTo": "ಲಗತ್ತಿಸಲಾಗಿದೆ",
  "attachedStatus": "ಲಗತ್ತಿನ ಸ್ಥಿತಿ",
  "default": "ಡೀಫಾಲ್ಟ್",
  "userRoleConfiguration": "ಬಳಕೆದಾರ ಪಾತ್ರ ಸಂರಚನೆ",
  "workflowId": "ವರ್ಕ್ಫ್ಲೋ ಐಡಿ",
  "workflowName": "ವರ್ಕ್ಫ್ಲೋ ಹೆಸರು",
  "entityValue": "ಘಟಕ ಮೌಲ್ಯ",
  "appliesTo": "ಅನ್ವಯಿಸುತ್ತದೆ",
  "reference": "ಉಲ್ಲೇಖ",
  "mainForm": "ಮುಖ್ಯ ಫಾರ್ಮ್",
  "generalInstructions": "ಸಾಮಾನ್ಯ ಸೂಚನೆಗಳು",
  "ccps": "ಮಹತ್ವದ ನಿಯಂತ್ರಣ ಬಿಂದುಗಳು",
  "stageInstructions": "ಹಂತದ ಸೂಚನೆಗಳು",

  "baseQty": "ಮೂಲ ಪ್ರಮಾಣ",

  "documentLinkPlugin": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್ ಪ್ಲಗಿನ್",
  "documentLinks ": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್‌ಗಳು ",
  "docType": "ಡಾಕ್ ಪ್ರಕಾರ",
  "annexureCount": "ಅಂಧ್ಯಕ್ಕೆಳಗಳ ಎಕ್ಕು",
  "basicInformation": "ძ್ಱೆಂಟ್ ಜಾನ್ಕಾರಿ",
  "mainDocument": "ძ್ಱೆಂಟ್ ದಾಕ್ಯುಮೆಂಟ್",
  "annexures": "ಅಂಧ್ಯಕ್ಕೆಳಗಳು",
  "selectWorkflowReference": "ವರ್ಕ್ಫ್ಲೋ ಉಲ್ಲೇಖ ಆಯ್ಕೆಮಾಡಿ",
  "templateReference": "ಟೆಂಪ್ಲೇಟ್ ಸಂದರ್ಭ",
  "selectTemplateReference": "ಟೆಂಪ್ಲೇಟ್ ಸಂದರ್ಭ ಆಯ್ಕೆಮಾಡಿ",
  "annexure": "ಅಂಧ್ಯಕ್ಕೆಳಗ್",
  "workflowReference": "ವರ್ಕ್ಫ್ಲೋ ಉಲ್ಲೇಖ",
  "addAnnexure": "ಅಂಧ್ಯಕ್ಕೆಳಗ್ ಜೋಡಿ",
  "copyDocumentLink": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್ ಕopi",
  "Annexure Count": "ಅನುಬಂಧ ಎಣಿಕೆ",
  "Doc Type": "ಡಾಕ್ಯುಮೆಂಟ್ ಪ್ರಕಾರ",
  "Item Group": "ವಸ್ತು ಸಮೂಹ",
  "Template Name": "ಟೆಂಪ್ಲೇಟ್ ಹೆಸರು",
  "Workflow ID": "ವರ್ಕ್ಫ್ಲೋ ಐಡಿ",
  "Workflow Name": "ವರ್ಕ್ಫ್ಲೋ ಹೆಸರು",
  "Number of Annexures": "ಅಂಧ್ಯಕ್ಕೆಳಗಳ ಎಕ್ಕು",
  "noDocumentsFound": "ಡಾಕ್ಯುಮೆಂಟ್ ಇಲ್ಲ",
  "pleaseSelectTheDocumentType": "ದಸ್ತಾವೇಜ್ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "annexureCountIsRequired": "ಅಂಧ್ಯಕ್ಕೆಳಗಳ ಎಕ್ಕು ಆवಶ್ಯಕ",
  "pleaseFillInTheFollowingRequiredFields": "ನिम್ಮೆಲ್ಲಿನ ಆವಶ್ಯಕ ಕ್ಷೇತ್ರಗಳಲ್ಲಿ ಭರೆಯಿರಿ",
  "createDocumentLink": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್ ರಚಿಸಿ",
  "documentLinkCopiedSuccessfully": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್ ಯಾಯಿಸಲಾಗಿದೆ",
  "documentLinkApp": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್",
  "documentLinkDeletedSuccessfully": "ಡಾಕ್ಯುಮೆಂಟ್ ಲಿಂಕ್ ಹटೆಯಲು ಸಫಲತೆಯೊಂದು",
  "deleteFailed": "ಅಳಿಸಲು ಯಾಯಿಸಲು ಯಾವುದೇ ದೋಷ",
  "createNewPhase": "ಹೊಸ ಹಂತವನ್ನು ರಚಿಸಿ",
  "phaseConfiguration": "ಹಂತ ಸಂರಚನೆ",
  "operations": "ಆಪರೇಶನ್‌ಗಳು",
  "triggeredPhase": "ಟ್ರಿಗರ್ ಮಾಡಿದ ಹಂತ",
  "searchOperations": "ಆಪರೇಶನ್‌ಗಳನ್ನು ಹುಡುಕಿ",
  "back": "ಹಿಂದೆ",
  "validate": "ಮಾನ್ಯಗೊಳಿಸಿ",
  "relayout": "ಮರು ವಿನ್ಯಾಸಗೊಳಿಸಿ",
  "createPhase": "ಹಂತ ಐಡಿ",
  "editPhaseId": "ಹಂತ ಐಡಿ ಸಂಪಾದಿಸಿ",
  "savePhase": "ಹಂತವನ್ನು ಉಳಿಸಿ",
  "clone": "ಕ್ಲೋನ್ ಮಾಡಿ",
  "procedureMaintenance": "ವಿಧಾನ ನಿರ್ವಹಣೆ",
  "searchProcedureId": "ವಿಧಾನ ಐಡಿ ಹುಡುಕಿ",
  "procedureId": "ವಿಧಾನ ಐಡಿ",
  "procedureName": "ವಿಧಾನ ಹೆಸರು",
  "procedureConfiguration": "ವಿಧಾನ ಸಂರಚನೆ",
  "effectiveFrom": "ಇಂದಿನಿಂದ ಪರಿಣಾಮಕಾರಿ",
  "effectiveTo": "ತನಕ ಪರಿಣಾಮಕಾರಿ",
  "nodeDetails": "ನೋಡ್ ವಿವರಗಳು",
  "operationDetails": "ಆಪರೇಶನ್ ವಿವರಗಳು",
  "basicDetails": "ಮೂಲ ವಿವರಗಳು",
  "sequenceNumber": "ಕ್ರಮ ಸಂಖ್ಯೆ",
  "operationName": "ಆಪರೇಶನ್ ಹೆಸರು",
  "timing": "ಸಮಯ",
  "expectedDurationMin": "ಅಪೇಕ್ಷಿತ ಅವಧಿ (ನಿಮಿಷ)",
  "durationMin": "ಅವಧಿ (ನಿಮಿಷ)",
  "actualDurationMin": "ವಾಸ್ತವ ಅವಧಿ (ನಿಮಿಷ)",
  "flags": "ಫ್ಲಾಗ್‌ಗಳು",
  "critical": "ಗಂಭೀರ",
  "optional": "ಐಚ್ಛಿಕ",
  "finalOperation": "ಅಂತಿಮ ಆಪರೇಶನ್",
  "operationConnections": "ಆಪರೇಶನ್ ಸಂಪರ್ಕಗಳು",
  "previousOperation": "ಹಿಂದಿನ ಆಪರೇಶನ್",
  "nextOperation": "ಮುಂದಿನ ಆಪರೇಶನ್",
  "completionCriteria": "ಪೂರ್ಣಗೊಳಿಸುವ ಮಾನದಂಡ",
  "dcVersion": "ಡಿಸಿ ಆವೃತ್ತಿ",
  "wiVersion": "ಡಬ್ಲ್ಯುಐ ಆವೃತ್ತಿ",
  "procedureVersion": "ವಿಧಾನ ಆವೃತ್ತಿ",
  "wfVersion": "ಡಬ್ಲ್ಯುಎಫ್ ಆವೃತ್ತಿ",
  "previousNodes": "ಹಿಂದಿನ ನೋಡ್‌ಗಳು",
  "nextNodes": "ಮುಂದಿನ ನೋಡ್‌ಗಳು",
  "entryNode": "ಪ್ರವೇಶ ನೋಡ್",
  "finalNode": "ಅಂತಿಮ ನೋಡ್",
  "multiDimensionalDataCollection": "ಬಹು ಆಯಾಮದ ಡೇಟಾ ಸಂಗ್ರಹ",
  "dataCollectionName": "ಡೇಟಾ ಸಂಗ್ರಹ ಹೆಸರು",
  "createDataCollection": "ಡೇಟಾ ಸಂಗ್ರಹ ರಚಿಸಿ",
  "editDataCollection": "ಡೇಟಾ ಸಂಗ್ರಹ ಸಂಪಾದಿಸಿ",
  "attachmentPoint": "ಲಗತ್ತು ಬಿಂದು",
  "dataCollectionGroups": "ಡೇಟಾ ಸಂಗ್ರಹ ಗುಂಪುಗಳು",
  "basicConfiguration": "ಮೂಲ ಸಂರಚನೆ",
  "groupName": "ಗುಂಪಿನ ಹೆಸರು",
  "collectionType": "ಸಂಗ್ರಹ ಪ್ರಕಾರ",
  "layoutType": "ಲೇಔಟ್ ಪ್ರಕಾರ",
  "requiredGroup": "ಅಗತ್ಯ ಗುಂಪು",
  "repeatableRows": "ಪುನರಾವರ್ತಿತ ಸಾಲುಗಳು",
  "tableRowNumber": "ಟೇಬಲ್ ಸಾಲು ಸಂಖ್ಯೆ",
  "tablePreview": "ಟೇಬಲ್ ಪೂರ್ವದೃಶ್ಯ",
  "addColumn": "ಕಾಲಮ್ ಸೇರಿಸಿ",
  "fieldConfiguration": "ಫೀಲ್ಡ್ ಸಂರಚನೆ",
  "label": "ಲೇಬಲ್",
  "defaultValue": "ಡೀಫಾಲ್ಟ್ ಮೌಲ್ಯ",
  "readOnly": "ಓದಲು ಮಾತ್ರ",
  "prefillingRows": "ಪೂರ್ವ ಭರ್ತಿ ಸಾಲುಗಳು",
  "validationRules": "ಮಾನ್ಯತೆ ನಿಯಮಗಳು",
  "saveGroup": "ಗುಂಪನ್ನು ಉಳಿಸಿ",
  "phaseAttachments": "ಹಂತದ ಅಟ್ಯಾಚ್‌ಮೆಂಟ್‌ಗಳು",
  "createProcedure": "ವಿಧಾನವನ್ನು ರಚಿಸಿ",
  "saveProcedure": "ವಿಧಾನವನ್ನು ಉಳಿಸಿ",
  "createNewProcedure": "ಹೊಸ ವಿಧಾನವನ್ನು ರಚಿಸಿ",
  "editProcedure": "ವಿಧಾನವನ್ನು ಸಂಪಾದಿಸಿ",
  "materialConsumption": "ವಸ್ತು ಬಳಕೆ",
  "attachmentPoints": "ಅಟ್ಯಾಚ್‌ಮೆಂಟ್ ಪಾಯಿಂಟ್‌ಗಳು",
  "cloneDataCollection": "ಡೇಟಾ ಸಂಗ್ರಹಣೆಯನ್ನು ನಕಲಿಸಿ",
  "deleteDataCollection": "ಡೇಟಾ ಸಂಗ್ರಹಣೆಯನ್ನು ಅಳಿಸಿ",
  "areYouSureYouWantToDeleteThisDataCollection": "ನೀವು ಈ ಡೇಟಾ ಸಂಗ್ರಹಣೆಯನ್ನು ಅಳಿಸಲು ಖಚಿತವೇ?",
  "column": "ಕಾಲಮ್",
  "field": "ಫೀಲ್ಡ್",
  "table": "ಕೋಷ್ಟಕ",
  "form": "ಫಾರ್ಮ್",
  "unitofMeasure": "ಅಳತೆ ಘಟಕ",
  "targetValue": "ಗುರಿ ಮೌಲ್ಯ",
  "targetBand": "ಗುರಿ ವ್ಯಾಪ್ತಿ",
  "options": "ಆಯ್ಕೆಗಳು",
  "trueValue": "ನಿಜ ಮೌಲ್ಯ",
  "falseValue": "ಸುಳ್ಳು ಮೌಲ್ಯ",
  "attachments": "ಅಟೈಚ್ಮೆಂಟ್‌ಗಳು",
  "editPhase": "ಪೈಶಾ ಸಂಪಾದಿಸಿ",
  "addAttachment": "ಅಟೈಚ್ಮೆಂಟ್ ಸೇರಿಸಿ",
  "searchDataCollectionName": "ಡಾಟಾ ಸಾಲಿಕೆಗಳ ಹೆಸರು ಹುಡುಕಿ",
  "numberOfColumns": "ಸಂಖ್ಯೆ ರಾಜ್ಯಗಳು",
  "procedureType": "ಪ್ರಾಕ್ಟಿಕ್ ತೆರಾಮಾಡಿ",
  "addNewToolGroup": "ಹೊಸ ಟೂಲ್ ಸமೂಹವನ್ನು ಸೇರಿಸಿ",
  "dataCollectionReferences": "ಡೇಟಾ ಸಂಗ್ರಹ ಉಲ್ಲೇಖಗಳು",
  "workInstructionReferences": "ಕಾರ್ಯ ಸೂಚನೆ ಉಲ್ಲೇಖಗಳು",
  "toolGroupReferences": "ಟೂಲ್ ಗುಂಪು ಉಲ್ಲೇಖಗಳು",
  "procedureReferences": "ವಿಧಾನ ಉಲ್ಲೇಖಗಳು",
  "dataCollectionId": "ಡೇಟಾ ಸಂಗ್ರಹ ID",
  "dataCollectionVersion": "ಡೇಟಾ ಸಂಗ್ರಹ ಆವೃತ್ತಿ",
  "workInstructionId": "ಕಾರ್ಯ ಸೂಚನೆ ID",
  "workInstructionVersion": "ಕಾರ್ಯ ಸೂಚನೆ ಆವೃತ್ತಿ",
  "toolGroupId": "ಟೂಲ್ ಗುಂಪು ID",
  "toolGroupVersion": "ಟೂಲ್ ಗುಂಪು ಆವೃತ್ತಿ",
  "addRow": "ಸಾಲು ಸೇರಿಸಿ",
  "noReferencesAdded": "ಇನ್ನೂ ಯಾವುದೇ ಉಲ್ಲೇಖಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ",
  "yieldPercentage": "ಉತ್ಪಾದನೆ (%)",
  "expectedYield": "ನಿರೀಕ್ಷಿತ ಉತ್ಪಾದನೆ",
  "minimumYield": "ಕನಿಷ್ಟ ಉತ್ಪಾದನೆ",
  "maximumYield": "ಗರಿಷ್ಟ ಉತ್ಪಾದನೆ",
  // Recipe Enhancements

  "product": "ಉತ್ಪನ್ನ",
  "usageCount": "ಬಳಕೆ ಸಂಖ್ಯೆ",
  "lastUsedDate": "ಕೊನೆಯ ಬಳಕೆ ದಿನಾಂಕ",
  "duplicate": "ನಕಲು",
  "import": "ಆಮದು",
  "export": "ರಫ್ತು",
  "searchRecipes": "ರೆಸಿಪಿಗಳನ್ನು ಹುಡುಕಿ...",
  "statusFilter": "ಸ್ಥಿತಿ ಫಿಲ್ಟರ್",
  "draft": "ಕರಡು",
  "total": "ಒಟ್ಟು",
  "recipes": "ರೆಸಿಪಿಗಳು",
  "newRecipe": "ಹೊಸ ರೆಸಿಪಿ",
  "headerTab": "ಹೆಡರ್",
  "ingredientsTab": "ಘಟಕಗಳು",
  "phasesAndOperations": "ಹಂತಗಳು ಮತ್ತು ಕಾರ್ಯಾಚರಣೆಗಳು",
  "yieldAndProducts": "ಉತ್ಪಾದನೆ ಮತ್ತು ಉತ್ಪನ್ನಗಳು",
  "referenceLinks": "ಉಲ್ಲೇಖ ಲಿಂಕ್‌ಗಳು",
  "yieldAndProductsComingSoon": "ಉತ್ಪಾದನೆ ಮತ್ತು ಉತ್ಪನ್ನಗಳು - ಶೀಘ್ರದಲ್ಲೇ",
  "referenceLinksComingSoon": "ಉಲ್ಲೇಖ ಲಿಂಕ್‌ಗಳು - ಶೀಘ್ರದಲ್ಲೇ",
  "productionParameters": "ಉತ್ಪಾದನಾ ಮಾನದಂಡಗಳು",
  "bmrHeaders": "BMR ಶೀರ್ಷಿಕೆಗಳು",
  "recipeNameLabel": "ರೆಸಿಪಿ ಹೆಸರು",
  "versionLabel": "ಆವೃತ್ತಿ",
  "currentVersionLabel": "ಪ್ರಸ್ತುತ ಆವೃತ್ತಿ",
  "statusLabel": "ಸ್ಥಿತಿ",
  "workCenterIdLabel": "ಕಾರ್ಯ ಕೇಂದ್ರ ID",
  "processTypeLabel": "ಪ್ರಕ್ರಿಯೆ ಪ್ರಕಾರ",
  "activeStatusLabel": "ಸಕ್ರಿಯ ಸ್ಥಿತಿ",
  "recipeDescriptionLabel": "ರೆಸಿಪಿ ವಿವರಣೆ",
  "batchSizeLabel": "ಬ್ಯಾಚ್ ಗಾತ್ರ",
  "batchUomLabel": "ಬ್ಯಾಚ್ ಮಾಪನ ಘಟಕ",
  "expectedCycleTimeLabel": "ನಿರೀಕ್ಷಿತ ಚಕ್ರ ಸಮಯ",
  "actualCycleTimeLabel": "ವಾಸ್ತವ ಚಕ್ರ ಸಮಯ",
  "scalingTypeLabel": "ಸ್ಕೇಲಿಂಗ್ ಪ್ರಕಾರ",
  "minBatchSizeLabel": "ಕನಿಷ್ಠ ಬ್ಯಾಚ್ ಗಾತ್ರ",
  "maxBatchSizeLabel": "ಗರಿಷ್ಠ ಬ್ಯಾಚ್ ಗಾತ್ರ",
  "scalingFactorLabel": "ಸ್ಕೇಲಿಂಗ್ ಅಂಶ",
  "companyNameLabel": "ಕಂಪನಿ ಹೆಸರು",
  "documentTitleLabel": "ದಾಖಲೆ ಶೀರ್ಷಿಕೆ",
  "documentNoLabel": "ದಾಖಲೆ ಸಂಖ್ಯೆ",
  "marketLabel": "ಮಾರುಕಟ್ಟೆ",
  "standardBatchSizeLabel": "ಪ್ರಮಾಣಿತ ಬ್ಯಾಚ್ ಗಾತ್ರ",
  "productNameLabel": "ಉತ್ಪನ್ನ ಹೆಸರು",
  "effectiveDateLabel": "ಪ್ರಭಾವಿ ದಿನಾಂಕ",
  "expiryDateLabel": "ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ",
  "shelfLifeLabel": "ಶೆಲ್ಫ್ ಜೀವನ",
  "manufacturingLicenseLabel": "ತಯಾರಿಕಾ ಪರವಾನಗಿ",
  "recipeNamePlaceholder": "ರೆಸಿಪಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "versionPlaceholder": "1.0",
  "statusPlaceholder": "ಸ್ಥಿತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "workCenterIdPlaceholder": "ಕಾರ್ಯ ಕೇಂದ್ರ ID ನಮೂದಿಸಿ",
  "processTypePlaceholder": "ಪ್ರಕ್ರಿಯೆ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "recipeDescriptionPlaceholder": "ರೆಸಿಪಿ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "workCenterIdRequired": "ದಯವಿಟ್ಟು ಕಾರ್ಯ ಕೇಂದ್ರ ID ನಮೂದಿಸಿ",
  "recipeDescriptionRequired": "ದಯವಿಟ್ಟು ರೆಸಿಪಿ ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ",
  "batchSizePlaceholder": "ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "batchUomPlaceholder": "ಮಾಪನ ಘಟಕ ಆಯ್ಕೆಮಾಡಿ",
  "expectedCycleTimePlaceholder": "ಉದಾ., 48h",
  "actualCycleTimePlaceholder": "ಉದಾ., 45h",
  "scalingTypePlaceholder": "ಸ್ಕೇಲಿಂಗ್ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "minBatchSizePlaceholder": "ಕನಿಷ್ಠ ಗಾತ್ರ",
  "maxBatchSizePlaceholder": "ಗರಿಷ್ಠ ಗಾತ್ರ",
  "scalingFactorPlaceholder": "1.0",
  "companyNamePlaceholder": "ಕಂಪನಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "documentTitlePlaceholder": "ಬ್ಯಾಚ್ ಮ್ಯಾನುಫ್ಯಾಕ್ಚರಿಂಗ್ ದಾಖಲೆ",
  "documentNoPlaceholder": "ದಾಖಲೆ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  "marketPlaceholder": "ಮಾರುಕಟ್ಟೆಯನ್ನು ನಮೂದಿಸಿ",
  "standardBatchSizePlaceholder": "ಪ್ರಮಾಣಿತ ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "productNamePlaceholder": "ಉತ್ಪನ್ನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "shelfLifePlaceholder": "ಉದಾ., 3 ವರ್ಷ",
  "manufacturingLicensePlaceholder": "ಪರವಾನಗಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  "recipeNameRequired": "ದಯವಿಟ್ಟು ರೆಸಿಪಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "versionRequired": "ದಯವಿಟ್ಟು ಆವೃತ್ತಿ ನಮೂದಿಸಿ",
  "statusRequired": "ದಯವಿಟ್ಟು ಸ್ಥಿತಿ ಆಯ್ಕೆಮಾಡಿ",
  "processTypeRequired": "ದಯವಿಟ್ಟು ಪ್ರಕ್ರಿಯೆ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "batchSizeRequired": "ದಯವಿಟ್ಟು ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "batchUomRequired": "ದಯವಿಟ್ಟು ಮಾಪನ ಘಟಕ ಆಯ್ಕೆಮಾಡಿ",
  "expectedCycleTimeRequired": "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿತ ಚಕ್ರ ಸಮಯ ನಮೂದಿಸಿ",
  "scalingTypeRequired": "ದಯವಿಟ್ಟು ಸ್ಕೇಲಿಂಗ್ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",
  "minBatchSizeRequired": "ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "maxBatchSizeRequired": "ದಯವಿಟ್ಟು ಗರಿಷ್ಠ ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "scalingFactorRequired": "ದಯವಿಟ್ಟು ಸ್ಕೇಲಿಂಗ್ ಅಂಶ ನಮೂದಿಸಿ",
  "companyNameRequired": "ದಯವಿಟ್ಟು ಕಂಪನಿ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "documentTitleRequired": "ದಯವಿಟ್ಟು ದಾಖಲೆ ಶೀರ್ಷಿಕೆ ನಮೂದಿಸಿ",
  "documentNoRequired": "ದಯವಿಟ್ಟು ದಾಖಲೆ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  "marketRequired": "ದಯವಿಟ್ಟು ಮಾರುಕಟ್ಟೆ ನಮೂದಿಸಿ",
  "standardBatchSizeRequired": "ದಯವಿಟ್ಟು ಪ್ರಮಾಣಿತ ಬ್ಯಾಚ್ ಗಾತ್ರ ನಮೂದಿಸಿ",
  "productNameRequired": "ದಯವಿಟ್ಟು ಉತ್ಪನ್ನ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "effectiveDateRequired": "ದಯವಿಟ್ಟು ಪ್ರಭಾವಿ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "expiryDateRequired": "ದಯವಿಟ್ಟು ಅವಧಿ ಮುಕ್ತಾಯ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "shelfLifeRequired": "ದಯವಿಟ್ಟು ಶೆಲ್ಫ್ ಜೀವನ ನಮೂದಿಸಿ",
  "manufacturingLicenseRequired": "ದಯವಿಟ್ಟು ಪರವಾನಗಿ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  "batchOption": "ಬ್ಯಾಚ್",
  "continuousOption": "ನಿರಂತರ",
  "semiContinuousOption": "ಅರ್ಧ ನಿರಂತರ",
  "underReview": "ಪರಿಶೀಲನೆಯಲ್ಲಿ",
  "linearOption": "ರೆಖೀಯ",
  "nonLinearOption": "ಅರೆಖೀಯ",
  "ingredientRemovedSuccess": "ಘಟಕವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ",
  "ingredientAddedSuccess": "ಘಟಕವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ",
  "ingredientUpdatedSuccess": "ಘಟಕವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ",
  "codeLabel": "ಕೋಡ್",
  "deleteIngredientTitle": "ಘಟಕ ಅಳಿಸಬೇಕೇ?",
  "deleteIngredientDescription": "ನೀವು ಖಚಿತವಾಗಿ ಈ ಘಟಕವನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?",
  "subtotal": "ಉಪಮೊತ್ತ",
  "itemsLabel": "ಐಟಂಗಳು",
  "totalQuantity": "ಒಟ್ಟು ಪ್ರಮಾಣ",
  "quantityUnit": "ಕೆಜಿ",
  "totalPercentage": "ಒಟ್ಟು %",
  "totalIngredients": "ಒಟ್ಟು ಘಟಕಗಳು",
  "overallTotal": "ಒಟ್ಟು ಮೊತ್ತ",
  "addNonBom": "Non-BOM ಸೇರಿಸಿ",
  "sequenceShort": "ವರಿಚೈ",
  "ingredientNameColumn": "ಘಟಕ ಹೆಸರು",
  "percentageColumn": "ಶೇಕಡಾವಾರು",
  "quantityColumn": "ಪ್ರಮಾಣ",
  "uomColumn": "ಉದ್ದೇಶದಂಡ",

  "companyDocumentInfo": "ಕಂಪನಿ ಮತ್ತು ಡಾಕ್ಯುಮೆಂಟ್ ಮಾಹಿತಿ",
  "productManufacturingInfo": "ಉತ್ಪನ್ನ ಮತ್ತು ತಯಾರಿಕಾ ಮಾಹಿತಿ",
  "actualBatchSizeLabel": "ನಿಜವಾದ ಬ್ಯಾಚ್ ಗಾತ್ರ",
  "actualBatchSizeRequired": "ದಯವಿಟ್ಟು ನಿಜವಾದ ಬ್ಯಾಚ್ ಗಾತ್ರವನ್ನು ನಮೂದಿಸಿ",
  "actualBatchSizePlaceholder": "ನಿಜವಾದ ಬ್ಯಾಚ್ ಗಾತ್ರವನ್ನು ನಮೂದಿಸಿ",
  "supersedesDocumentNoAndDateLabel": "ಹಿಂದಿನ ಡಾಕ್ಯುಮೆಂಟ್ ಸಂಖ್ಯೆ ಮತ್ತು ದಿನಾಂಕ",
  "supersedesDocumentNoAndDateRequired": "ದಯವಿಟ್ಟು ಹಿಂದಿನ ಡಾಕ್ಯುಮೆಂಟ್ ಸಂಖ್ಯೆ ಮತ್ತು ದಿನಾಂಕವನ್ನು ನಮೂದಿಸಿ",
  "supersedesDocumentNoAndDatePlaceholder": "ಉದಾ., BMR/3003687/1157/01-00 & 07/08/2020",
  "cmlLabel": "CML",
  "cmlRequired": "ದಯವಿಟ್ಟು CML ನಮೂದಿಸಿ",
  "cmlPlaceholder": "ಉದಾ., All Kind",
  "batchNoLabel": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "batchNoRequired": "ದಯವಿಟ್ಟು ಬ್ಯಾಚ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  "batchNoPlaceholder": "ಪ್ರತಿ ಬ್ಯಾಚ್‌ಗೆ ನೀಡಲಾಗುತ್ತದೆ",
  "semiFinishedProductCodeLabel": "ಅರ್ಧ ಮುಗಿದ ಉತ್ಪನ್ನ ಕೋಡ್",
  "semiFinishedProductCodeRequired": "ದಯವಿಟ್ಟು ಅರ್ಧ ಮುಗಿದ ಉತ್ಪನ್ನ ಕೋಡ್ ನಮೂದಿಸಿ",
  "semiFinishedProductCodePlaceholder": "ಉದಾ., 3003687/01",
  "mfrRefLabel": "MFR ರೆಫರೆನ್ಸ್",
  "mfrRefRequired": "ದಯವಿಟ್ಟು MFR ರೆಫರೆನ್ಸ್ ನಮೂದಿಸಿ",
  "mfrRefPlaceholder": "ಉದಾ., MFR/PH/19/0039/00",
  "manufacturingDateLabel": "ತಯಾರಿಕಾ ದಿನಾಂಕ",
  "manufacturingDateRequired": "ದಯವಿಟ್ಟು ತಯಾರಿಕಾ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "manufacturingDatePlaceholder": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "batchCommencedOnLabel": "ಬ್ಯಾಚ್ ಪ್ರಾರಂಭವಾದ ದಿನಾಂಕ",
  "batchCommencedOnRequired": "ದಯವಿಟ್ಟು ಬ್ಯಾಚ್ ಪ್ರಾರಂಭ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "batchCommencedOnPlaceholder": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "batchCompletedOnLabel": "ಬ್ಯಾಚ್ ಪೂರ್ಣಗೊಂಡ ದಿನಾಂಕ",
  "batchCompletedOnRequired": "ದಯವಿಟ್ಟು ಬ್ಯಾಚ್ ಪೂರ್ಣಗೊಂಡ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "batchCompletedOnPlaceholder": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "totalQuantityLabel": "ಒಟ್ಟು ಪ್ರಮಾಣ",
  "totalQuantityRequired": "ದಯವಿಟ್ಟು ಒಟ್ಟು ಪ್ರಮಾಣ ನಮೂದಿಸಿ",
  "totalQuantityPlaceholder": "ಉದಾ., ___ Kg",
  "manufacturingYieldLabel": "ತಯಾರಿಕಾ ಉತ್ಪಾದನೆ (%)",
  "manufacturingYieldRequired": "ದಯವಿಟ್ಟು ತಯಾರಿಕಾ ಉತ್ಪಾದನೆ ನಮೂದಿಸಿ",
  "manufacturingYieldPlaceholder": "ಉದಾ., ___ %",
  "breakdownOrDeviationLabel": "ಬ್ರೇಕ್‌ಡೌನ್ / ವಿಚಲನ",
  "breakdownOrDeviationRequired": "ದಯವಿಟ್ಟು ಬ್ರೇಕ್‌ಡೌನ್ ಅಥವಾ ವಿಚಲನ ವಿವರ ನಮೂದಿಸಿ",
  "breakdownOrDeviationPlaceholder": "ಹೌದು/ಇಲ್ಲ + ಟಿಪ್ಪಣಿ ಇದ್ದರೆ",
  "reviewedByProductionLabel": "ಪರಿಶೀಲಿಸಿದವರು (Production)",
  "reviewedByProductionRequired": "ದಯವಿಟ್ಟು Production ವಿಮರ್ಶಕನನ್ನು ನಮೂದಿಸಿ",
  "reviewedByProductionPlaceholder": "ಸಹಿ / ದಿನಾಂಕ",
  "reviewedByQALabel": "ಪರಿಶೀಲಿಸಿದವರು (QA)",
  "reviewedByQARequired": "ದಯವಿಟ್ಟು QA ವಿಮರ್ಶಕನನ್ನು ನಮೂದಿಸಿ",
  "reviewedByQAPlaceholder": "ಸಹಿ / ದಿನಾಂಕ",

  // ============================================== Historical Filter Table / OEE Tabs ===========================================
  "oeeBack": "ಹಿಂದೆ",
  "overallOee": "ಸಮಗ್ರ OEE:",
  "oeeAvailability": "ಉಪಲಬ್ಧತೆ",
  "oeePerformance": "ಕಾರ್ಯದಕ್ಷತೆ",
  "oeeQuality": "ಗುಣಮೇನ",
  "oeeExpand": "ವಿಸ್ತರಿಸಿ",
  "oeeCollapse": "ಸಂಕ್ಷಿಪ್ತಗೊಳಿಸಿ",
  "expandToFullWidth": "ಪೂರ್ಣ ಅಗಲಕ್ಕೆ ವಿಸ್ತರಿಸಿ",
  "machineTimeline": "ಯಂತ್ರ ಸಮಯರೇಖೆ",
  "oeeResource": "ಸಂಸಾಧನೆ",
  "oeeDate": "ದಿನಾಂಕ",
  "oeeAvailable": "ಉಪಲಬ್ಧ",
  "oeePlannedDowntime": "ಯೋಜಿತ ಡೌನ್‌ಟೈಮ್",
  "oeeUnplannedDowntime": "ಅನಿಯೋಜಿತ ಡೌನ್‌ಟೈಮ್",
  "batchwiseData": "ಬ್ಯಾಚ್‌ವಾರು ಡೇಟಾ",
  "oeeTotal": "ಒಟ್ಟು",
  "oeeRecords": "ರೆಕಾರ್ಡ್‌ಗಳು",
  "oeeFrom": "ಹಿಂದಿನ",
  "oeeResources": "ಸಂಸಾಧನೆಗಳು",
  "clickOnChartBarToLoadBatchDetails": "ಬ್ಯಾಚ್ ವಿವರಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಚಾರ್ಟ್ ಬಾರ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ",
  "downloadAsExcel": "ಎಕ್ಸೆಲ್‌ಗೆ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
  "oeeExport": "ರಫ್ತು",
  "exitFullscreen": "ಪೂರ್ಣಸ್ಕ್ರೀನ್‌ನಿಂದ ಬಿಡಿ",
  "fullscreenView": "ಪೂರ್ಣಸ್ಕ್ರೀನ್ ದೃಶ್ಯ",
  "exitTableView": "ಟೇಬಲ್ ದೃಶ್ಯದಿಂದ ಬಿಡಿ",
  "oeeFilters": "ಫಿಲ್ಟರ್‌ಗಳು:",
  "placeholderResource": "ಸಂಸಾಧನೆ",
  "placeholderDate": "ದಿನಾಂಕ",
  "placeholderBatchNo": "ಬ್ಯಾಚ್ ಸಂಖ್ಯೆ",
  "oeeSelected": "ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ:",
  "oeeClearSelection": "ಆಯ್ಕೆಯನ್ನು ಸಾಫ್ ಮಾಡಿ",
  "selectionCleared": "ಆಯ್ಕೆ ಸಾಫ್ ಮಾಡಲಾಗಿದೆ",
  "allSelectionsCleared": "ಎಲ್ಲಾ ಆಯ್ಕೆಗಳನ್ನು ಸಾಫ್ ಮಾಡಲಾಗಿದೆ",
  "updatedBatchData": "ಬ್ಯಾಚ್ ಡೇಟಾ ಅಪ್‌ಡೇಟ್ ಮಾಡಲಾಗಿದೆ",
  "failedToRefreshBatchData": "ಬ್ಯಾಚ್ ಡೇಟಾ ರಿಫ್ರೆಶ್ ಮಾಡಲು ವಿಫಲವಾಯಿತು",
  "oeeOrderNo": "ಆದೇಶ ಸಂಖ್ಯೆ",
  "oeeItemCode": "ಐಟಂ ಕೋಡ್",
  "oeeProduct": "ಉತ್ಪನ್ನ",
  "oeePlanQty": "ಯೋಜನೆ ಪ್ರಮಾಣ",
  "oeeActualQty": "ವಾಸ್ತವ ಪ್ರಮಾಣ",
  "oeePlanDT": "ಯೋಜನೆ DT",
  "oeeActualPT": "ವಾಸ್ತವ PT",
  "oeePlanPT": "ಯೋಜನೆ PT",
  "oeeUnplanDT": "ಅನಿಯೋಜಿತ DT",
  "oeeGoodQty": "ಒಳ್ಳೆಯ ಪ್ರಮಾಣ",
  "oeeBadQty": "ಕೆಟ್ಟ ಪ್ರಮಾಣ",
  "oeeCycleTime": "ಚಕ್ರ ಸಮಯ",
  "oeeActualCycleTime": "ವಾಸ್ತವ ಚಕ್ರ ಸಮಯ",
  "oeeOee": "OEE",
  "downtimeDetails": "ಡೌನ್‌ಟೈಮ್ ವಿವರಗಳು",
  "oeeDetails": "ವಿವರಗಳು",
  "viewDowntimeDetails": "ಡೌನ್‌ಟೈಮ್ ವಿವರಗಳನ್ನು ನೋಡಿ",
  "downtimeAnalysisReport": "ಡೌನ್‌ಟೈಮ್ ವಿಶ್ಲೇಷಣೆ ರಿಪೋರ್ಟ್",
  "oeeUnplannedDowntimes": "ಅನಿಯೋಜಿತ ಡೌನ್‌ಟೈಮ್‌ಗಳು",
  "oeePlannedDowntimes": "ಯೋಜಿತ ಡೌನ್‌ಟೈಮ್‌ಗಳು",
  "lineClearanceActivities": "ಲೈನ್ ಕ್ಲಿಯರನ್ಸ್ ಚಳುವಳಿಕೆಗಳು",
  "oeeReasonCode": "ಕಾರಣ ಕೋಡ್",
  "oeeReasonDescription": "ಕಾರಣ ವಿವರಣೆ",
  "oeeDowntime": "ಡೌನ್‌ಟೈಮ್",
  "downtimeMinutes": "ಡೌನ್‌ಟೈಮ್ (ನಿಮಿಷಗಳು)",
  "oeeNA": "ಉಪಲಬ್ಧವಿಲ್ಲ",
  "oeeTargetQuantity": "ಗುರಿ ಪ್ರಮಾಣ",
  "oeeUom": "ಮಾಪನ ಘಟಕ",
  "oeeProductName": "ಉತ್ಪನ್ನ ಹೆಸರು",
  "excellentNoDowntimeEvents": "ಅದ್ಭುತ! ಡೌನ್‌ಟೈಮ್ ಘಟನೆಗಳು ದಾಖಲಾಗಿಲ್ಲ",
  "batchCompletedWithoutInterruptions": "ಯೋಜಿತ ಅಥವಾ ಅನಿಯೋಜಿತ ತಡೆಗಳಿಲ್ಲದೆ ಈ ಬ್ಯಾಚ್ ಪೂರ್ಣಗೊಂಡಿದೆ.",
  "noMessageFound": "ಯಾವುದೇ {{message}} ಕಂಡುಬಂದಿಲ್ಲ",
  "noMessageDuringPeriod": "ಆಯ್ಕೆ ಮಾಡಿದ ಅವಧಿಯಲ್ಲಿ ಈ ಬ್ಯಾಚ್‌ನಲ್ಲಿ ಯಾವುದೇ {{message}} ಇರಲಿಲ್ಲ.",
  "errorLoadingData": "ಡೇಟಾ ಲೋಡ್ ಮಾಡುವಲ್ಲಿ ದೋಷ",
  "oeeReason": "ಕಾರಣ",
  "oeeRootCause": "ಮೂಲ ಕಾರಣ",
  "oeeDuration": "ಅವಧಿ",
  "oeeStartTime": "ಪ್ರಾರಂಭ ಸಮಯ",
  "oeeEndTime": "ಅಂತ್ಯ ಸಮಯ",
  "oeeComment": "ಕಾಮೆಂಟ್",
  "oeeCreatedBy": "ರಚಿಸಿದವರು",
  "oeeObjectType": "ವಸ್ತು ಪ್ರಕಾರ",
  "machine": "ಯಂತ್ರ",
  "manual": "ಕೈಯಾರೆ",
  "historicalReport": "ಐತಿಹಾಸಿಕ ವರದಿ",
  "pleaseSelectWorkCenter": "ದಯವಿಟ್ಟು ಕೆಲಸದ ಕೇಂದ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "pleaseSelectResource": "ದಯವಿಟ್ಟು ಸಂಪನ್ಮೂಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "Work Center": "ಕೆಲಸದ ಕೇಂದ್ರ",
  "Resource": "ಸಂಪನ್ಮೂಲ",
  "Select Shift": "ಶಿಫ್ಟ್ ಅನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "Event Type": "ಘಟನೆಯ ಪ್ರಕಾರ",
  "Date Range": "ದಿನಾಂಕ ಶ್ರೇಣಿ",
  "filterby": "ಅಂತಹ",
  "historicalTable": "ಐತಿಹಾಸಿಕ ಟೇಬಲ್",
  "availabilityAgainstResource": "ಸಂಪನ್ಮೂಲಕ್ಕೆ ವಿರುದ್ಧವಾಗಿ ಲಭ್ಯತೆ",
  "availabilityAgainstShift": "ಶಿಫ್ಟ್‌ಗೆ ವಿರುದ್ಧವಾಗಿ ಲಭ್ಯತೆ",
  "confirmLayoutChange": "ವಿನ್ಯಾಸ ಬದಲಾವಣೆಯನ್ನು ಖಚಿತಪಡಿಸಿ",
  "layoutChangeWarning": "ಲೈನ್ ಕ್ಲಿಯರನ್ಸ್ ಚಳುವಳಿಕೆಗಳು ದಾಖಲಾಗಿಲ್ಲ",
  "relesable": "ರೇಲೇಸೇಬಲ",
  "new": "ನ್ಯಾ",
  "fieldType": "ಫೀಲ್ಡ್ ಟೈಪ್",
  "customDataFields": "ಕಸ್ಟಮ್ ಡೇಟಾ ಫೀಲ್ಡ್ಗಳು",
  "editAttachmentPoint": "ಸಂಲಗ್ನ ಪೋಇಂಟ್ ಸಂಪಾದಿಸಿ",
  "mandatoryStep": "ಕರ್ತವ್ಯ ಚರ್ಚೆ",
  "canSkip": "ಸ್ಕಿಪ್ ಕೊಡ್",
  "requiresSignOff": "ಸಂಕೇತ ದೇನಾಗಿದೆ",
  "autoProgressOnComplete": "ಪೂರ್ಣ ಹೋದುವುದು",
  "procedureSteps": "ಪ್ರಕ್ರಿಯೆ ಚರ್ಚೆ",
    "phaseVersion": "ಹಂತ ಆವೃತ್ತಿ",
  "mfr": "ಎಂಎಫ್‌ಆರ್",
  "mfrVersion": "ಎಂಎಫ್‌ಆರ್ ಆವೃತ್ತಿ",
  "bmr": "ಬಿಎಂಆರ್",
  "bmrVersion": "ಬಿಎಂಆರ್ ಆವೃತ್ತಿ",
  "PleaseSelectAttachmentsToRemove": "ತೆಗೆದುಹಾಕಲು ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
  "RemoveSelectedAttachments": "ಆಯ್ದ ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
  "NoAttachmentsToRemove": "ತೆಗೆದುಹಾಕಲು ಯಾವುದೇ ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳಿಲ್ಲ",
  "RemoveAllAttachments": "ಎಲ್ಲಾ ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಿ",
  "AreYouSureYouWantToRemoveAllAttachments": "ಎಲ್ಲಾ ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಲು ನೀವು ಖಚಿತವೇ?",
  "AllAttachmentsRemoved": "ಎಲ್ಲಾ ಅಟ್ಯಾಚ್ಮೆಂಟ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಲಾಗಿದೆ",
  "allowMultipleDc": "ಏಕಾಧಿಕ ಡೀಸಿ",
  "allowPartialSave": "ಇಸ್ತೀಫೀ ಸೇವ್",
  "allowSaveOnValidateFail": "ಸತ್ಯಾಪನೆ ಅಸ್ತು ಸೇವ್",
  "optionalAndRequiredEntries": "ವೈಕಲ್ಪಿಕ ಔಂದು ಆವಶ್ಯಕ ಪ್ರವಿಷ್ಟೀಯ",
  "allowAddRow": "ಪಂಕ್ತಿ ಜೋಡಿ",
  "overRideRangeValue": "ರೇಂಜ ಮೂಲಕ ಮಾನವಿದೆ",
  "selectNcCode": "NC ಕೋಡ್ ಅಯ್ಕೆ",
  "ncLog": "NC ಲೋಗ",
  "hideColumn": "ಕ೉ಲಂ ಛೋಡಿ",

  // HRM Settings
  "settings.sidebar.profile": "Profile",
  "settings.sidebar.security": "Security",
  "settings.sidebar.notifications": "Notifications",
  "settings.sidebar.preferences": "Preferences",
  "settings.sidebar.support": "Help & Support",
  "settings.sidebar.logout": "Logout",
  "settings.profile.title": "Profile Settings",
  "settings.profile.personalInfo": "Personal Information",
  "settings.profile.emergencyContact": "Emergency Contact",
  "settings.profile.name": "Name",
  "settings.profile.contactNumber": "Contact Number",
  "settings.profile.personalEmail": "Personal Email",
  "settings.profile.relationship": "Relationship",
  "settings.profile.phone": "Phone",
  "settings.profile.uploadPhoto": "Upload Photo",
  "settings.profile.saveChanges": "Save Changes",
  "settings.security.title": "Security",
  "settings.security.changePassword": "Change Password",
  "settings.security.comingSoon": "Coming Soon",
  "settings.security.comingSoonDesc": "Password changes are managed through your SSO provider",
  "settings.security.currentPassword": "Current Password",
  "settings.security.newPassword": "New Password",
  "settings.security.confirmPassword": "Confirm Password",
  "settings.security.passwordStrength": "Password Strength",
  "settings.security.sessionInfo": "Session Info",
  "settings.security.lastLogin": "Last Login",
  "settings.security.loginMethod": "Login Method",
  "settings.notifications.title": "Notifications",
  "settings.notifications.push": "Push Notifications",
  "settings.notifications.email": "Email Notifications",
  "settings.notifications.dnd": "Do Not Disturb",
  "settings.notifications.salaryCredit": "Salary Credit",
  "settings.notifications.leaveApproval": "Leave Approval",
  "settings.notifications.generalAnnouncements": "General Announcements",
  "settings.notifications.holidayAlerts": "Holiday Alerts",
  "settings.notifications.appraisalUpdates": "Appraisal Updates",
  "settings.notifications.payslipAvailable": "Payslip Available",
  "settings.notifications.policyUpdates": "Policy Updates",
  "settings.notifications.expenseApproval": "Expense Approval",
  "settings.notifications.projectAssignments": "Project Assignments",
  "settings.notifications.dndStartTime": "Start Time",
  "settings.notifications.dndEndTime": "End Time",
  "settings.notifications.savePreferences": "Save Preferences",
  "settings.preferences.title": "Preferences",
  "settings.preferences.language": "Language",
  "settings.preferences.calendarSync": "Calendar Sync",
  "settings.preferences.calendarComingSoon": "Integration coming soon",
  "settings.preferences.theme": "Theme",
  "settings.preferences.darkMode": "Dark Mode",
  "settings.preferences.googleCalendar": "Google Calendar",
  "settings.preferences.outlookCalendar": "Outlook Calendar",
  "settings.support.title": "Help & Support",
  "settings.support.submitTicket": "Submit a Ticket",
  "settings.support.myTickets": "My Tickets",
  "settings.support.quickLinks": "Quick Links",
  "settings.support.subject": "Subject",
  "settings.support.category": "Category",
  "settings.support.description": "Description",
  "settings.support.priority": "Priority",
  "settings.support.submit": "Submit Ticket",
  "settings.support.privacyPolicy": "Privacy Policy",
  "settings.support.termsOfService": "Terms of Service",
  "settings.support.noTickets": "No tickets submitted yet",
  "settings.logout.confirm": "Are you sure you want to logout?",
  "settings.logout.title": "Logout",
  "nav.sidebar.dashboard": "Dashboard",
  "nav.sidebar.employees": "Employees",
  "nav.sidebar.administration": "Administration",
  "nav.sidebar.selfService": "Self-Service",
  "nav.sidebar.financePolicy": "Finance & Policy",
  "nav.sidebar.operations": "Operations",
  "nav.sidebar.settings": "Settings",
  "nav.sidebar.notifications": "Notifications",
  "nav.app.organization": "Organization Setup",
  "nav.app.userMaintenance": "User Maintenance",
  "nav.app.userGroup": "User Group",
  "nav.app.accessControl": "Access Control",
  "nav.app.userCredentials": "User Credentials",
  "nav.app.activityMaintenance": "Activity Maintenance",
  "nav.app.activityGroup": "Activity Group",
  "nav.app.leave": "Leave Management",
  "nav.app.travel": "Travel Request",
  "nav.app.expense": "Expense Report",
  "nav.app.payslip": "Payslip",
  "nav.app.appraisal": "Performance Appraisal",
  "nav.app.timesheet": "Timesheet",
  "nav.app.payroll": "Payroll Processing",
  "nav.app.compensation": "Compensation Master",
  "nav.app.policies": "HR Policies",
  "nav.app.announcements": "Announcements",
  "nav.app.projects": "Projects & Resources",
  "nav.app.assets": "Asset Management",
  "nav.app.holidays": "Holidays Calendar",
  "dashboard.sublabel.organization": "Manage structure",
  "dashboard.sublabel.userMaintenance": "Manage users",
  "dashboard.sublabel.userGroup": "Group permissions",
  "dashboard.sublabel.accessControl": "RBAC roles",
  "dashboard.sublabel.userCredentials": "Manage credentials",
  "dashboard.sublabel.activityMaintenance": "Manage activities",
  "dashboard.sublabel.activityGroup": "Group activities",
  "dashboard.sublabel.leave": "Apply & track leaves",
  "dashboard.sublabel.travel": "Request trips",
  "dashboard.sublabel.expense": "Submit claims",
  "dashboard.sublabel.payslip": "View salary slips",
  "dashboard.sublabel.appraisal": "Performance review",
  "dashboard.sublabel.timesheet": "Log work hours",
  "dashboard.sublabel.payroll": "Process payroll",
  "dashboard.sublabel.compensation": "Salary master",
  "dashboard.sublabel.policies": "Company policies",
  "dashboard.sublabel.announcements": "Company updates",
  "dashboard.sublabel.projects": "Manage projects",
  "dashboard.sublabel.assets": "Track assets",
  "dashboard.sublabel.holidays": "Holiday calendar",
  "dashboard.task.applyLeave": "Apply Leave",
  "dashboard.task.submitExpense": "Submit Expense",
  "dashboard.task.viewPayslip": "View Payslip",
  "dashboard.task.logTimesheet": "Log Timesheet",
  "dashboard.task.requestTravel": "Request Travel",
  "dashboard.task.viewAppraisal": "View Appraisal",
  "dashboard.quickTasks": "Quick Tasks",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.viewAll": "View All",
  "dashboard.search.placeholder": "Search apps and tasks...",
  "dashboard.activity.leaveApproved": "Leave approved",
  "dashboard.activity.expenseSubmitted": "Expense submitted",
  "dashboard.activity.timesheetSaved": "Timesheet saved",
  "nav.breadcrumb.home": "Home",
  "nav.footer.version": "v1.0.0",
  "nav.footer.copyright": "© 2026 RITS Consulting",
  "nav.footer.helpCenter": "Help Center"
}