export const tamilLanguage = {
  "schedulerMaintenance": "அட்டவணை பராமரிப்பு",
  "documentType": "ஆவண வகை",
  "requestType": "கோரிக்கை வகை",
  "phaseDefinition": "அடுக்கு வரையறை",
  "search phase": "தேடல் கட்டம்",
  "allStatus": "அனைத்து நிலைகள்",
  "all types": "அனைத்து வகைகள்",
  "createNew": "புதியதை உருவாக்கு",
  "max": "அதிகபட்சம்",
  "min": "குறைந்தது",
  "tolerance": "மடங்குதல்",
  "actualValue": "உண்மையான மதிப்பு",
  "actionsOnFailure": "சேதமாவது நடவடிக்கைகள்",
  "monitoringFrequency": "கண்காணிப்பு அடிக்கை",
  "expectedValue": "எதிர்பார்க்கப்படும் மதிப்பு",
  "qcId": "கோலை ஐடி",
  "expectedValueRange_ta": "எதிர்பார்க்கப்படும் மதிப்பு அளவுக்கு",
  "frequency": "அடிக்கை",
  "dataPointID": "தரவுத்தட்டு ஐடி",
  "productionVersion": "பிரோட்குத்தல் வர்ஜன",  
  "pressure": "அழுத்தம்",
  "duration": "கால அளவு",
  "rpm": "எரிபொருள் நெஞ்சு",
  "workCenterId": "வேலை மைய ஐடி",
  "resourceId": "மூலதனம் ஐடி",
  "adjustments": "செயல்முறை மாற்றங்கள்",
  "qualityControlParameters": "முதல் தரக் கட்டுப்பாட்டு அளவுகோல்கள்",
  "dataCollection": "தரவுகள் சேகரிப்பு",
  "monthlyPlan": "மாதாந்திர திட்டம்",
  "resources": "மூலதனம்",
  "defaultPhaseId": "முதன்மை கட்டம் ஐடி",
  "unsavedChangesMessage": "அப்புறம் மாற்றுகள் இருக்கும். இந்த பக்கத்தை விட்டுவிடுவது நீங்கள் மறுப்பதாக உறுதி செய்கிறீர்களா?",
  "unsavedChangesMessages": "அப்புறம் மாற்றுகள் இருக்கும். இந்த பக்கத்தை விட்டுவிடுவது நீங்கள் மறுப்பதாக உறுதி செய்கிறீர்களா?",
  "tools": "கருவிகள்",
  "safetyProcedures": "பாதுகாப்பு நடைமுறைகள்",
  "yieldWasteTracking": "விளை, கழிவுகள் கண்காணிப்பு",
  "triggerPoints": "தொடர்பான இடங்கள்",
  "packagingLabeling": "பேக்கேஜிங் லேபிளிங்",
  "recipeName": "சேதுபடுத்தல்",
  "ccp": "சிசிபி",
  "stepName": "படி பெயர்",
  "instruction": "வழிமுறைகள்",
  "steps": "படி",
  "id": "ஐடி",
  "associatedStep": "சேர்க்கப்பட்ட படி",
  "expectedCycleTime": "எதிர்பார்க்கப்படும் சுழற்சித் நேரம்",
  "ingredients": "உபகரணங்கள்",
  "phases": "படிகள்",
  "phaseId": "படியின் ஐடி",
  "phaseName": "படியின் பெயர்",
  "inactive": "செயலில் இல்லை",
  "recipeId": "செய்முறை ஐடி",
  "batchSize": "தொகுப்பு அளவு",
  "batchUom": "தொகுப்பு அலகு",
  "totalExpectedCycleTime": "மொத்த எதிர்பார்க்கப்படும் சுழற்சி நேரம்",
  "totalActualCycleTime": "மொத்த உண்மையான சுழற்சி நேரம்",
  "active": "செயலில்",
  "recipeStepDetails": "சமையல் வழிமுறை விவரங்கள்",
  "workInstructions": "வேலைக்குறிப்புகள்",
  "dataCollections": "தரவுகள் சேகரிப்பு",
  "parameterLists": "அளவீட்டு பட்டியல்",
  "recipeType": "செய்முறை வகை",
  "stageType": "மேடை வகை",
  "recipe": "செய்முறை",
  "stage": "மேடை",
  "validateRange": "வரம்பை சரிபார்க்கவும்",
  "processOrderRelease": "செயல்முறை விடுதலை",
  releaseProcessOrde: "விடுதலை செயல்முறை ஆணை",
  processOrder: "செயல்முறை ஆணை",
  appTitle: "பொருள் பராமரிப்பு",
  item: "பொருள்",
  description: "விளக்கம்",
  recipeDescription: "விளக்கம்",
  shiftType: "அமர்வு வகை",
  searchActivities: "செயல்களை தேடு",
  logout: "வெளியேறு",
  revision: "திருத்தம்",
  "qtyConsumed": "வாங்கிய அளவு",
  status: "நிலை",
  procurementType: "கொள்முதல் வகை",
  "consumptionAndPackingAppTitle": "நுகர்வு மற்றும் ப கிங்",
  lotSize: "நிறைய அளவு",
  createShift: "அமர்வை உருவாக்கு",
  workCenter: "வேலை மையம்",
  resource: "மூலநிலை",
  add: "சேர்க்கு",
  main: "முக்கிய",
  alternateComponent: "மாற்று கூறு",
  printDocument: "அச்சு ஆவணம்",
  customData: "விருப்ப தரவு",
  itemGroup: "பொருள் குழு",
  qtyRestriction: "அளவு கட்டுப்பாடு",
  "data": "தரவு",
  routing: "ரூட்டிங்",
  routingVersion: "ரூட்டிங் பதிப்பு",
  bom: "பிஓஎம்",
  bomVersion: "பிஓஎம் பதிப்பு",
  assemblyDataType: "சேர்க்கை தரவுத்தொகுப்பு",
  "multiDataCollectionList": "பல தரவு சேகரிப்பு பட்டியல்",
"totalRecords": "மொத்த பதிவுகள்",
"collect": "சேகரிக்க",
  removalDataType: "அகற்றல் தரவுத்தொகுப்பு",
  receiptDataType: "ரசீது தரவுத்தொகுப்பு",
  currentVersion: "நிகழ் பதிப்பு",
  itemType: "பொருள் வகை",
  create: "உருவாக்க",
  save: "சேமிக்க",
  cancel: "ரத்து செய்",
  "sequence": "வரிசை",
  "version": "பதிப்பு",
  "versions": "பதிப்பு: ",
  "parentMaterial": "பெற்றோர் பொருள்",
  "validFrom": "இருந்து செல்லுபடியாகும்",
  "validTo": "வரை செல்லுபடியாகும்",
  "createdDate": "உருவாக்கப்பட்ட தேதி: ",
  "modifiedTime": "மாற்றிய தேதி: ",
  "availableDocuments": "கிடைக்கும் ஆவணங்கள்",
  "assignedDocuments": "ஒதுக்கப்பட்ட ஆவணங்கள்",
  "document": "ஆவணம்",
  "createItem": "பொருளை உருவாக்கு",
  "value": "மதிப்பு",
  "go": "செல்",
  copy: "நகல்",
  confirmCopy: "நகல் உறுதிசெய்",
  delete: "அழி",
  confirmDelete: "அழிப்பதை உறுதிசெய்",
  deleteMessage: "இந்த உருப்படியை நீக்க விரும்புகிறீர்களா?",
  "insert": "உள்ளிடு",
  "removeSelected": "தேர்ந்தெடுத்தவற்றை நீக்கு",
  removeAll: "அனைத்தையும் நீக்கு",
  "classification": "வகைப்படுத்தல்",
  "relaxedRecipeFlow": "இயல்பான ஓட்ட செய்முறை",
  "scan": "ஸ்கேன்",
  "shipmentOrderNumber": "அனுப்புதல் எண்",
  "dispatchDetails": "வினியோக விவரங்கள்",
  "dispatchDateTime": "வினியோக தேதி மற்றும் நேரம்",
  "recipientInfo": "பெறுநர் தகவல்",
  "dispatchInfo": "வினியோக தகவல்",
  "recipeSteps": "வகைபடுத்தல் படிகள்",
  "boxNumber": "பட்டகம் எண���",
  "boxCapacity": "ப்டகத்தின் திறன்",
  "packetId": "பேக்கெட் ஐடி",
  "packetDescription": "பேக்கெட் விவரம்",
  "remainingCapacity": "எழு���ப்படும் திறன்",
  "totalPacketsInBox": "பட்டகத்தில் மொத்த பேக்கெட்கள்",

  // ===================================================

  "reasonCodeAppTitle": "காரணக் குறியீட்டு பராமரிப்பு",
  "reasonCode": "காரணக் குறியீடு",
  "category": "வகை",
  "messageType": "செய்தி வகை",
  "createReasonCode": "காரணக் குறியீடு உருவாக்கவும்",
  "prelautid": "முன்னணி",
  "materialName": "பொருள் பெயர்",
  "uom": "அளவீட்டு அலகு",
  "expectedQty": "எதிர்பார்க்கப்படும் அளவு",
  "unit": "அலகு",
  "receivedQty": "பெறப்பட்ட அளவு",
  "actions": "செயல்கள்",
  "hold": "நிறுத்து",
  "receive": "பெறு",
  "reject": "அனுமதிக்கவில்லை",
  "remove": "அழிக்கவும்",

  //=============================================================


  "routingTitle": "ரூட்டிங் பராமரிப்பு",
  "routingType": "ரூட்டிங் வகை",
  "routingSteps": "ரூட்டிங் படிகள்",
  "subType": "உப வகை",
  "dispositionGroup": "கைவிடும் குழு",
  "relaxedRoutingFlow": "சலுகை ரூட்டிங்",
  "replicationToErp": "ஈஆர்பி க்கு நகலெடுப்பு",
  "details": "விவரங்கள்",
  "nextStepId": "அடுத்த படி ஐடி",
  "stepId": "படி ஐடி",
  "stepType": "படி வகை",
  "selectContainer": "கண்டெய்னரை தேர்ந்தெடுக்கவும்",
  "stepDescription": "படி விளக்கம்",
  "previousStepId": "முந்தைய படி ஐடி",
  "maximumLoopCount": "அதிகபட்ச மடங்கு எண்ணிக்கை",
  "queueDecision": "பொதுவான முடிவு",
  "erpControlKey": "ஈஆர்பி கட்டுப்பாட்டு விசை",
  "erpOperation": "ஈஆர்பி செயல்பாடு",
  "erpWorkCenter": "ஈஆர்பி வேலை மையம்",
  "requiredTimeInProcess": "செயல்முறையில் தேவைப்படும் நேரம்",
  "sl_no": "வரிசை எண்",
  "packet_id": "பொதி ஐடி",
  "packet_description": "பொதி விளக்கம்",
  "qty_consumed": "பயன்படுத்திய அளவு",
  "total_packets": "மொத்த பொதிகள்",
  "remaining_capacity": "மீதமுள்ள கொள்ளவு",
  "specialInstruction": "சிறப்பு அறிவுரை",
  "erpSequence": "ஈஆர்பி தொடர்",
  "blockPcusUntilInspectionFinished": "பரிசோதனை முடிந்த வரை PCUs ஐ தடை செய்க",
  "entryStep": "நுழைவு படி",
  "isLastReportingStep": "இது இறுதி அறிக்கையிடும் படி",
  "reworkStep": "மீண்டும் செயல்படுத்துதல் படி",
  "routingStepDetails": "ரூட்டிங் படி விவரங்கள்",
  "routingDescription": "ரூட்டர் விவரணம்",
  "insertBefore": "முன் செருகு",
  "insertAfter": "பின் செருகு",
  "createRouting": "வழிமுறையை உருவாக்கு",
  "operation": "ஆப்பரேஷன்",
  "operationId": "ஆப்பரேஷன் ஐடி",
  "operationVersion": "செயல்பாட்டு பதிப்பு",
  "container": "கண்டெய்னர்",
  "workListPanel": "வேலை பட்டியல் பானல்",
  "trackOee": "ஓஇஇ கண்காணிப்பு",




  // ================================ Activity =================

  "activityAppTitle": "செயல்பாட்டு பராமரிப்பு",
  "activity": "செயல்பாடு",
  "activityIds": "செயல்பாட்டு ஐடி",
  "activityGroup": "செயல்பாட்டு குழு",
  "enabled": "இயக்கப்பட்டது",
  "visibleInActivityManager": "செயல்பாட்டு மேலாளர் காட்சியளிக்கின்றது",
  "type": "வகை",
  "classOrProgram": "வகுப்பு / நிகழ்ச்சி",
  "listOfMethod": "முறை பட்டியல்",
  "createActivity": "செயல்பாட்டை உருவாக்கவும்",
  "activityRules": "செயல்பாட்டு விதிகள்",
  "activityHooks": "செயல்பாட்டு ஹூக்குகள்",
  "userArgument": "பயனர் வாதம்",
  "sites": "தளங்கள்",
  "hookableMethod": "ஹூக்கபிள் முறை",
  "hookPoint": "ஹூக் பாயிண்ட்",
  "rules": "விதிகள்",
  "setting": "அமைப்பு",
  "addRules": "விதிகளை சேர்க்கவும்",
  "addRule": "ஒரு விதியைச் சேர்க்கவும்",
  "restoreDefault": "இயல்புகளை மீட்டமைக்கவும்",
  "selectActivity": "செயல்பாட்டை தேர்ந்தெடுக்கவும்",
  "selectMessageType": "செய்தி வகையைத் தேர்ந்தெடுக்கவும்",
  "selectResource": "வழங்கலைத் தேர்ந்தெடுக்கவும்",
  "selectWorkCenter": "பணி மையத்தைத் தேர்ந்தெடுக்கவும்",
  "rowSelectionMsg": "நீங்கள் வரிசை தேர்வை தொடர விரும்புகிறீர்களா?",

  // ============================== WORK CENTER =================

  "workCenterAppTitle": "வேலை மைய பராமரிப்பு",
  "workCenterCategory": "வேலை மைய வகை",
  "defaultParentWorkCenter": "இயல்புநிலை பெற்றோர் வேலை மையம்",
  "createWorkCenter": "வேலை மையத்தை உருவாக்கு",
  "defaultWorkCenter": "இயல்புநிலை பணி மையம்",
  "association": "சங்கம்",
  "associateId": "இணை ஐடி",
  "defaultResource": "இயல்புநிலை வளம்",
  "deleteWCMessage": "இந்த வேலை மையத்தை நீக்க விரும்புகிறீர்களா?",
  "disabled": "நீக்கப்பட்டது",
  "closeMsg": "நீங்கள் பக்கத்தை விட்டு செல்வது உறுதியாக இருக்கிறதா?",
  "yes": "ஆமாம்",
  "no": "இல்லை",
  "ok": "சரி",
  "select": "தேர்வு செய்க",
  "confirmation": "உறுதிப்படுத்தல்",
  "selectAssociateId": "தொடர்புடைய ஐடியைத் தேர்ந்தெடுக்கவும்",
  "recipientName": "பெறுநர் பெயர்",
  "recipientId": "பெறுநர் ஐடி",
  "closePageMsg": "நீங்கள் நிச்சயமாக வெளியேற?",
  "leavePage": "பக்கத்தை விட்டு செல்லவும்",
  "router": "ரூட்டர்",
  "generalInfo": "எண்ணெய் தகவல்",
  "materialCode": "பொருள் குறியீடு",
  "materialDescription": "பொருள் விளக்கம்",
  "purchaseOrderNumber": "கையொப்பம் எண்ணிக்கை",
  "grnNumber": "GRN எண்",
  "supplierInfo": "சந்தையாளர் தகவல்",
  "supplierName": "சந்தையாளர் பெயர்",
  "supplierId": "சந்தையாளர் ஐடி",
  "invoiceNumber": "அணிகருத்து எண்",
  "storageLocation": "சேமிப்பு இடம்",
  "warehouseCode": "கொள்முதல் குறியீடு",
  "storageBin": "சேமிப்பு பின்",
  "deliveryInfo": "வழங்கல் தகவல்",
  "deliveryNumber": "வழங்கல் எண்",
  "deliveryType": "வழங்கல் வகை",
  "vehicleNumber": "வாகன எண்",
  "inwardDetails": "உள்ளூர் விவரங்கள்",
  "receiptDateTime": "செலுத்துதல் தேதி மற்றும் நேரம்",
  "gateDockNumber": "கேட் டாக் எண்",
  "attachmentDocument": "உரிமை ஆவணம்",
  "attachment": "உரிமை",

  "headerTitle": "ஷிப்ட் பராமரிப்பு",
  "siteMaintenance": "தளம் பராமரிப்பு",
  "batchNo": "பேச்சு எண்",
  "pod": "பாட்",
  "site": "தளம்",
  "shift": "ஷிப்ட்",
  "shopOrder": "அரசு ஆணை",
  "serialNumber": "சீரியல் எண்",
  "pcuNumber": "பிசி யூ எண்",
  "pcu": "பிசியு",
  "materialInwardManagement": "பொருள் உள்ளே செலுத்துதல் மேலாண்மை",
  "itemBO": "இருப்பு ",
  "routerBO": "ராட்டர் ",
  "qty": "எண்",
  "shopOrderBO": "அடைவுக் கையொப்பம் ",
  "pcuQuantity": "பிசி யூ அளவு",
  "unlimited_over_delivery": "அனலிமிடெட் ஓவர் டெலிவரி",
  "doneQty": "செய்யப்பட்ட அளவு",
  "timeZone": "நேர மண்டலம்",
  "local": "உள்ளூர்",
  "releasedQty": "விடப்பட்ட அளவு",
  "qtyInQueueOrWork": "விசாரணையிலோ அல்லது பணியிலோ உள்ள அளவு",
  "scrappedQty": "வழக்கப்பட்ட அளவு",
  "unreleasedQty": "விடப்படாத அளவ",
  "buildQty": "செயலாக்கப்பட வேண்டிய அளவு",
  "recommendedBuildQtyToReachOrderedQty": "ஆர்டர்செய்த அளவை அடைய பரிந்துரைக்கப்பட்ட அளவு",
  "recommendedBuildQtyToReachMinimumDeliveryQty": "குறைந்தபட்ச டெலிவரி அளவை அடைய பரிந்துரைக்கப்பட்ட அளவு",
  "temperature": "வெப்பநிலை",
  "state": "நிலை",
  "userHeaderTitle": "பயனர் பராமரிப்பு",
  "underDeliveryTolerance": "குறைந்த அளவிலான விநியோக தாங்கல்",
  "overDeliveryTolerance": "அதிகமான விநியோக தாங்கல்",
  "maximumDeliveryQty": "அதிகபட்ச விநியோக அளவு",
  "minimumDeliveryQty": "குறைந்தபட்ச விநியோக அளவு",
  "user": "பயனர்",
  "noOfCount": "முறை",
  "shiftName": "ஓட்டம் பெயர்",
  "defineDeliveryToleranceIn": "டெலிவரி பொறுமை உள்ள",
  "material": "பொருள்",
  "cycleTime": "சுழற்சி நேரம்",
  "manufacturedTime": "தயாரிக்கப்பட்ட நேரம்",
  "createCycleTime": "சுழற்சி நேரத்தை உருவாக்கவும்",
  "materialVersion": "பொருள் பதிப்பு",
  "update": "புதுப்பிக்க",
  "shiftInterval": "ஓட்ட இடைவெளி",
  "calendarRules": "காலண்டர் விதிகள்",
  "calendarOverride": "காலண்டர் மேற்பராமரிப்பு",
  "createdOn": "உருவாக்கப்பட்டது",
  "modifiedOn": "திருத்தப்பட்டது",
  "erpShift": "எர்பி ஓட்டம்",
  "confirm": "உறுதிப்படுத்தவும்",
  "alertRow": "நீங்கள் தேர்ந்தெடுத்த வரிசையுடன் தொடர விரும்புகிறீர்களா?",
  "areYouSure": "இதை நீக்க விரும்புகிறீர்களா",
  "addBreak": "மெடக்கு சேர்க்கவும்",
  "Status": "நிலை",
  "comment": "மூலம்",
  "newStatus": "புதிய நிலை",
  "selectBy": "தேர்வுசெய்து",
  "validityShiftInfo": "செல்லுபடியாகும்/ஓட்டம் தகவல்",
  "clockInOutInfo": "கிளாக்-இன்/வெளியேறும் தகவல்",
  "labourInfo": "தொழிலாளர் தகவல்",
  "action": "செயல்",
  "day": "நாள்",
  "productionDay": "உற்பத்தி நாள்",
  "dayClass": "நாள் வகுப்பு",
  "search": "தேடுங்கள்",
  "maintenance": "பராமரிப்பு",
  "certification": "சர்டிபிகேஷன்",
  "subStep": "உப-நடவடிக்கை",
  "activityHook": "செயற்பாடு ஹுக்",
  "operationType": "செயல் வகை",
  "resourceType": "வசதி வகை",
  "defaultOperation": "மூல செயல்முறை",
  "addAsErpOperation": "எர்பி செயல்முறையாகச் சேர்க்கவும்",
  "maxLoopCount": "அதிகரித்த எண்ணிக்கையிலான முறை",
  "enter": "நுழைய",
  "employeeNumber": "நிறுவன எண்",
  "hireDate": "வேலைக்கு எடுத்த நாள்",
  "erpUser": "எர்பி பயனர்",
  "firstName": "முதல் பெயர்",
  "lastName": "கடைசி பெயர்",
  "emailAddress": "மின்னஞ்சல் முகவரி",
  "erpPersonnelNumber": "எர்பி பணியாளர் எண்",
  "userGroup": "பயனர் குழு",
  "labourTracking": "தொழிலாளர் கண்காணிப்பு",
  "supervisor": "மேற்பார்வையாளர்",
  "labourRule": "தொழிலாளர் விதி",
  "bomType": "ப���ம்���ு வகை",
  "plannedBom": "அதிகரிக்கப்பட்ட பொம்மு",
  "plannedRouting": "அதிகரிக்கப்பட்ட வழிமுறைகள்",
  "lcc": "எல்.சி.சி",
  "plannedWorkCenter": "அதிகரிக்கப்பட்ட வேலை மையம்",
  "orderedQty": "ஆர்டர் அளவு",
  "priority": "முதன்மை",
  "erpUom": "எர்பி யு.ஓ.எம்",
  "plannedStart": "அதிகரிக்கப்பட்ட ஆரம்பம்",
  "plannedCompletion": "அதிகரிக்கப்பட்ட முடிவு",
  "scheduledStart": "அட்டவணை ஆரம்பம்",
  "scheduledEnd": "அட்டவணை முடிவு",
  "customerOrder": "வாடிக்கையாளர் ஆர்டர்",
  "customer": "வாடிக்கையாளர்",
  "orderType": "ஆர்டர் வகை",
  "plannedMaterial": "அதிகரிக்கப்பட்ட பொருள்",
  "productionQuantities": "உற்பத்தி அளவுகள்",
  "serialPCU": "சீரியல் பிசி.யு",
  "enable": "தொடங்க",
  "bomMaintenance": "பொம்மு பராமரிப்பு",
  "bomTemplate": "பொம்மு மடல்",
  "component": "அங்கம்",
  "assemblyOperation": "அஸபிளி செயல்முறை",
  "assemblyQuantity": "அஸ்பிளி அளவு",
  "copyBom": "நகல் பொம்மு",
  "updateBom": "பொம்மு புதுப்பிக்கவும்",
  "assemblySequence": "அஸ்பிளி குரூப்",
  "componentType": "அங்க வகை",
  "maxNc": "அதிகரித்த எண்",
  "maxUsage": "அதிகரிக்கப்பட்ட பயன்பாடு",
  "createBomComponent": "பொம்மு அங்கத்தை உருவாக்கவும்",
  "createNewBom": "புதிய பொம்மு உருவாக்கவும்",
  "alternateComponentVersion": "மாற்று அங்கம் பதிப்பு",
  "designCost": "டிசைன் செலவு",
  "assySequence": "அசம்ப்ளி வரிசை",
  "componentVersion": "சொத்து பதிப்பு",
  "componentDescription": "சொத்து விளக்கம்",
  "assyQty": "அசம்ப்ளி அளவு",
  "assyOperation": "அசம்ப்ளி செயல்முறை",
  "assemblyDataTypeBo": "அசம்ப்ளி தரவுப் போக்கு ",
  "storageLocationBo": "சேமிப்பு இடம் ",
  "close": "மூடு",
  "availableActivities": "கிடைக்கும் செயலிகள்",
  "assignedActivities": "ஒப்படைக்கப்பட்ட செயலிகள்",
  "activities": "செயலிகள்",
  "activityGroupName": "செயலி குழு பெயர்",
  "activityGroupMaintenance": "செயலி குழு பராமரிப்பு",
  "createActivityGroup": "செயலி குழு உருவாக்கவும்",
  "activityGroupDescription": "செயலி குழு விளக்கம்",
  "copyActivityGroup": "நகல் செயல்பாடு குழு",
  "numbeType": "எண் வகை",
  "definedBy": "வரையறுக்கப்பட்ட",
  "objectVersion": "வஸ்து பதிப்பு",
  "containerInput": "குடிசை உள்ளீடு",
  "prefix": "ஆரம்பம்",
  "suffix": "இணை",
  "numberBase": "எண் அடிப்படை",
  "sequenceLength": "தொடர்பு நீளம்",
  "minSequence": "குறைந்தபட்ச வரிசை",
  "maxSequence": "அதிகபட்ச வரிசை",
  "warningThreshold": "எச்சரிக்கை தளம்",
  "incrementBy": "அதிகரிக்கப்படுவது",
  "currentSequence": "நடப்பு வரிசை",
  "resetSequenceNumber": "வரிசை எண்ணை மீட்டமைக்கவும்",
  "nextNumberActivity": "அடுத்த எண்ணின் செயற்பாடு",
  "createContinuousSfc": "இருக்கையில் தொடர்ச்சியான எஸ்.எப்.சி உருவாக்கு",
  "commitNextNumberChangesImmediately": "அடுத்த எண்ணிற்கான மாற்றங்களை உடனே உறுதிப்படுத்தவும்",
  "sampleNextNumber": "உதாரணமாக அடுத்த எண்",
  "nextNumberAppTitle": "அடுத்த எண் பராமரிப்பு",
  "parametersAndDescription": "அளவுருக்கள் மற்றும் விளக்கம்",
  "selectItemGroup": "உருப்படி குழுவைத் தேர்வுசெய்க",
  "selectDataType": "தரவுத் வகையைத் தேர்வுசெய்க",
  "selectBOM": "பிஓஎம்ஐ தேர்வுசெய்க",
  "selectItem": "உருப்படியைத் தேர்வுசெய்க",
  "retrieve": "மீட்டெடுக்க",
  "clear": "அழிக்க",
  "selectRouting": "மார்க்கத்தை தேர்வு செய்க",
  "createNextNumber": "அடுத்த எண்ணை உருவாக்கவும்",
  // ===============================   Next Number     ==============================
  "podMaintenance": "பாட் பராமரிப்பு",
  "podName": "பாட் பெயர்",
  "createPodName": "பாட் பெயரை உருவாக்கு",
  "podLayout": "பாட் அமைப்பு",
  "kafkaIntegration": "காஃப்கா ஒருங்கிணைப்பு",
  "kafkaId": "காஃப்கா ஐடி",
  "operationCanBeChanged": "செயல்பாடை மாற்றலாம்",
  "resourceCanBeChanged": "வளங்களை மாற்றலாம்",
  "showQuantity": "அளவைக் காட்டு",
  "documentName": "ஆவணத்தின் பெயர்",
  "sessionTimeout": "அமைப்புக் காலம்",
  "refreshRate": "புதுப்பிப்பு வீதம்",
  "podType": "பாட் வகை",
  "copyPod": "பாட்டைப் பிரதியாக்கு",
  "updatePod": "பாட் புதுப்பி",
  "buttonId": "அந்தர்க் ஐடி",
  "buttonLabel": "அந்தர்க் சொட்டை",
  "buttonType": "அந்தர்க் வகை",
  "buttons": "அந்தர்க்கள்",
  "listOptions": "பட்டியல் விருப்பங்கள்",
  "podSelections": "பாட் தேர்வுகள்",
  "printers": "முதிரகர்கள்",
  "home": "முகப்பு",
  "buttonSize": "அந்தர்க் அளவு",
  "imageIcon": "பட ஐகான்",
  "hotKey": "தெரிந்த விசை",
  "buttonLocation": "அந்தர்க் இடம்",
  "podSelection": "பாட் தேர்வு",
  "activitySequence": "செயல்பாடு வரிசை",
  "pluginLocation": "பிளக் இடம்",
  "clearsPcu": "பிசியூவைச் சுத்தம் செய்",
  "fixed": "நிறுத்தப்பட்டது",

  "createNewPod": "புதிய பொட் உருவாக்கவும்",
  "panelLayout": "பெயர்ப்பை அமைக்கவும்",
  "selectDefaultOperation": "மூல செயல்பாட்டை தேர்வுசெய்க",
  "selectDefaultResource": "மூல வளத்தை தேர்வுசெய்க",
  "selectDocumentName": "ஆவணத்தின் பெயரை தேர்வுசெய்க",
  "browseWorkList": "வேலைப் பட்டியலைப் பார்க்கவும்",
  "podWorkList": "பாட் வேலை பட்டியல்",
  "assembleList": "அமைக்கப்பட்ட பட்டியல்",
  "dcCollectList": "டி.சி. சேகரிப்பு பட்டியல்",
  "toolList": "கருவிகள் பட்டியல்",
  "workInstructionList": "வேலை வழிமுறைகள் பட்டியல்",
  "dcEntryList": "டி.சி. நுழைவுப் பட்டியல்",
  "subStepList": "உப படி பட்டியல்",
  "mainInput": "முக்கிய உள்ளீடு",
  "mainInputHotKey": "முக்கிய உள்ளீட்டு ஹாட் கீ",
  "infoLine1": "தகவல் வரி 1",
  "infoLine2": "தகவல் வரி 2",
  "documentPrinter": "ஆவண அச்சுப்பொருள்",
  "labelPrinter": "லேபல் அச்சுப்பொருள்",
  "travelerPrinter": "பயணி அச்சுப்பொருள்",
  "users": "பயனர்கள்",
  "userGroupMaintenance": "பயனர் குழு பராமரிப்பு",
  "selectPod": "பாட் தேர்வு செய்யவும்",
  "availableUsers": "கிடைக்கும் பயனர்கள்",
  "assignedUsers": "அனுப்பிய பயனர்கள்",
  "availableActivityGroups": "கிடைக்கும் செயல்பாட்டு குழுக்கள்",
  "assignedActivityGroups": "அனுப்பிய செயல்பாட்டு குழுக்கள்",




  "pickListManagement": "எடுத்து அட்டவணை மேலாண்மை",
  "pickListNo": "எடுத்து அட்டவணை எண்",
  "orderNo": "உத்தி எண்",
  "generate": "உற்பத்தி",
  "itemCode": "பொருள் குறியீடு",
  "itemDescription": "பொருள் விளக்கம்",
  "qtyOrdered": "உத்தி அளவு",
  "qtyPicked": "எடுத்து அளவு",
  "location": "இடம்",
  "warehouse": "கோப்பிடம்",
  "pick": "எடுக்க",
  "updatePick": "எடுக்கவும் புதுப்பிக்கவும்",
  "print": "அச்சிடவும்",
  "selectOrder": "உத்தியை தேர்வு செய்க",
  "resourceMaintenance": "மூலங்கள் பராமரிப்பு",
  "createResource": "மூலங்களை உருவாக்கு",
  "opcTag": "ஓபிசி குறியீடு",
  "processResource": "மூலத்தை செயலாக்கு",
  "erpEquipmentNumber": "ஈஆர்‌பி சாதன எண்",
  "erpPlantNumber": "ஈஆர்‌பி செயற்கை எண்",
  "availableResource": "கிடைக்கக்கூடிய மூலங்கள்",
  "assignedResource": "ஒதுக்கப்பட்ட மூலங்கள்",
  "tagName": "குறியீட்டு பெயர்",
  "tagUrl": "குறியீட்டு URL",
  "identity": "அடையாளம்",
  "selectCertification": "சான்றிதழ் தேர்வு செய்க",
  "cycleTimeMaintenance": "சுழற்போது பராமரிப்பு",
  "dataType": "தரவுத் தன்மை",
  "manageAlternateComponents": "மாற்று கூறுகளை நிர��வகிக்கவும்",
  "manageParentComponents": "மூல கூறுகளை நிர்வகிக்கவும்",
  "selectComponent": "கூறுகளைத் தேர்ந்தெடுக்கவும்",
  "selectAssemblyOperation": "அமைப்பு செயல்பாட்டைப் தேர்ந்தெடுக்கவும்",
  "selectAssemblyDataType": "அமைப்பு தரவுப் வகையைத் தேர்ந்தெடுக்கவும்",
  "selectAlternateComponent": "மாறுபட்ட கூறுகளைத் தேர்ந்தெடுக்கவும்",
  "selectOperation": "செயல்பாட்டை தேர்வுசெய்க",
  "selectMaterial": "பொருளை தேர்வுசெய்க",
  "name": "பெயர்",
  "operationalSettingAppTitle": "செயல்முறை அமைப்பு",
  "reset": "மீட்டமை",
  "uomCode": "லகு குியீடு",
  "selectList": "பட்டியல் தேர்ந்தெடு",
  "list": "பட்டியல்",
  "selectPrinters": "முதிர்க்கங்களை தேர்ந்தெடு",
  "deleteMsg": "இந்த அடுத்த எண்ணை நீக்க விரும்புகிறீர்களா?",
  "parameter": "அளவுரு",
  "enterFullScreen": "முழு திரைக்கு செல்லவும்",
  "exitFullScreen": "முழு திரையிலிருந்து வெளியேறு",
  "release": "விடுவிப்பு",
  "shopOrderRelease": "கடையின் ஆர்டர் விடுவிப்பு",
  "qtyToRelease": "விடுவிக்க வேண்டிய அளவு",
  "addToNewProcessLot": "புதிய செயல்தொகுதிக்கு சேர்க்கவும்",
  "availableQtyToRelease": "விடுவதற்கான கிடைக்கும் அளவு",
  "flowChart": "படிவம் வரைபடம்",
  "serialBatchNumber": "சீரியல் பாட்சி எண்",
  "bnoQuantity": "பிபி எண்",
  "bno": "பிபி",

  // ================================= ITEM GROUP ===================================
  "itemGroupAppTitle": "பொருள் குழு பராமரிப்பு",
  "groupDescription": "குழு விவரம்",
  "unitPrice": "அலகு விலை",
  "groupMember": "குழு உறுப்பினர்",
  "createItemGroup": "பொருள் குழுவை உருவாக்கு",
  "itemGroupDeleteMessage": "இந்த பொருள் குழுவை நீக்க விரும்புகிறீர்களா",
  "erpPlantMaintenanceOrder": "ஈஆர்பி தொழிற்சாலை பராமரிப்பு ஆணை",
  "availableResourceTypes": "எல்லை வடிவங்கள்",
  "assignedResourceTypes": "ஒதுக்கப்பட்ட வள வகைகள்",
  "copyResource": "பிரதி வளம்",

  "selectMethod": "முறையைத் தேர்ந்தெடுக்கவும்",
  "method": "முறை",

  "resourceTypeMaintenance": "வள வகை பராமரிப்பு",
  "resourceTypeDescription": "வள வகை விளக்கம்",
  "resourceMemberList": "வள உறுப்பினர் பட்டியல்",
  "createResourceType": "வள வகை உருவாக்கு",

  // ==========================LIST APP=========================================
  "allowOperatorToChangeColumnSequence": "இயக்குபவருக்கு நெடுவரிசை வரிசையை மாற்ற அனுமதி",
  "allowOperatorToSortRows": "இயக்குபவருக்கு வரிசைகளை வரிசைப்படுத்த அனுமதி",
  "allowMultipleSelection": "ப தேர்வுகளை அனுமதி",
  "showAllActiveSfcsToOperator": "இயக்குபவருக்கு அனைத்து செயலில் உள்ள SFC களையும் காட்டு",
  "maximumNumberOfRow": "அதிகபட்ச வரிசைகளின் எண்ணிக்கை",
  "columnSequence": "வரிசை",
  "columnName": "நெடுவரிச பெயர்",
  "rowSortOrder": "வரிசை வரிசைப்படுத்தல்",
  "ShowDetails": "விவரங்களைக் காட்டு",
  "width": "அகலம்",
  "ascending": "ஏறுவரிசை",
  "descending": "இறங்குவரிசை",
  "copyList": "பிரதி பட்டியல்",
  "deleteConfirmation": "நீக்குதல் முறைமை",
  "ListMaintenance": "பட்டியல் நிர்வகிப்பு",
  "createUserGroup": "பயனர் குழுவை உருவாக்கவும்",

  "customdataMaintenance": "தனியுரிமை தரவு மேலாண்மை",
  "data field": "தரவு பெயர்",
  "field label": "பெயர்",
  "required": "தேவையான",
  "selectdataField": "தரவு பெயர் தேர்ந்தெடுக்கவும்",

  // ============================================== DATA FIELD ===========================================

  "dataField": "தரவு புலம்",
  "fieldLabel": "புல லேபிள்",
  "dataFieldAppTitle": "தரவு புல பராமரிப்பு",
  "maskGroup": "மாஸ்க் குழு",
  "preSaveActivity": "சேமிப்பதற்கு முந்தைய செயல்பாடு",
  "isTrackable": "கண்காணிக்கக்கூடியது",
  "qmSelectedSet": "QM தேர்ந்தெடுக்கப்பட்ட தொகுப்பு",
  "isMrfRef": "MRF குறிப்பா",
  "browseIcon": "உலாவல் ஐகான்",
  "defaultLabel": "இயல்புநிலை லேபிள்",
  "fieldValue": "புல மதிப்பு",
  "labelValue": "லேபிள் மதிப்பு",
  "api": "ஏபிஐ",
  "parameters": "அளவுருக்கள்",
  "title": "தலைப்பு",
  "editValues": "மதிப்புகளைத் திருத்து",
  "createDataField": "தரவு புலத்தை உருவாக்கு",

  // ============================================== DATA TYPE ===========================================

  "dataTypeAppTitle": "தரவு வகை பராமரிப்பு",
  "createDataType": "தரவு வகையை உருவாக்கவும்",
  "selectDataField": "தரவு புலத்தைத் தேர்ந்தெடுக்கவும்",
  "listDetails": "பட்டியல் விவரங்கள்",

  "order": "ஆர்டர்",
  "componentToScan": "அளவீடு செய்ய அங்கம்",
  "assembled": "கூட்டிய",
  "assemble": "சேர்",
  "remaining": "மீதமுள்ள",
  "dataAttribute": "தரவியல்",
  "returnToPod": "POD க்கு திரும்பவும்",
  "confirmCreateDataField": "தரவியல் புலம் காணப்படவில்லை, நீங்கள் இந்த தரவியல் புலத்தை உருவாக்க விரும்புகிறீர்களா",
  "attachmentList": "அடிப்படை பட்டியல்",

  // ============================================= DC PLUGIN ===========================================
  "parameterList": "பராமெட்டர் பட்டியல்",
  "showDetails": "விவரங்களை காட்டு",
  "collectData": "தரவை சேகரிக்கவும்",
  "saveDraft": "மசோதாவை சேமிக்கவும்",
  "submit": "சமர்ப்பிக்கவும்",
  "dataFieldList": "தரவுப் புலம் பட்டியல்",
  "collectedDCParameterList": "சேகரிக்கப்பட்ட டிசி பராமெட்டர் பட்டியல்",
  "returnToDCList": "டிசி பட்டியலுக்கு திரும்பவும்",
  "range": "அளவுக்கோல்",
  "dateTime": "தேதி மற்றும் நேரம்",
  "collectionMethod": "சேரிப்பு முறை",
  "parameterName": "பரிமாணத்தின் பெயர்",
  "collectDataAt": "தரவை சேகரிக்க",
  "entityName": "நிறுவனத்தின் பெயர்",

  // =============================================== WORK INSTRUCTION ======================================
  "textInstruction": "உரை வழிமுறை", // Tamil
  "urlInstruction": "யூஆர்.எல் வழிமுறை",
  "instructionType": "குறிப்பு வகை",
  "WorkInstruction_Description": "விவரம்",
  "WorkInstructionID_Revision": "வேலைக் குறிப்புகள் / திருத்தம்",
  "Operation_StepId": "செயல்பாடு படி ஐடி",
  "StepId": "படி ஐடி",


  "workInstructionMaintenance": "பணி வழிமுறைகள் பராமரிப்பு",
  "workInstruction": "பணி வழிமுறைகள்",
  "createWorkInstruction": "பணி வழிமுறைகளை உருவாக்கு",
  "alwaysShowInNewWindow": "எப்போதும் புதிய சாளரத்தில் காட்டு",
  "logViewing": "பதிவு பார்வை",
  "changeAlert": "மாற்றம் எச்சரிக்கை",
  "erpWi": "ERP பணி வழிமுறைகள்",
  "text": "உரை",
  "url": "யு.ஆர்.எல்",
  "file": "கோப்பு",

  // ================================== SCRAP AND USER =======================
  "pcu/shopOrder/processLot": "பிசியு / ஷாப் ஆர்டர் / பிராசஸ் லாட்",
  "comments": "கருத்துகள்",
  "scrap": "கழிவு",
  "unscrap": "கழிவு ரத்து",
  "Scrap": "கழிவு",
  "Unscrap": "கழிவு ரத்து",
  "scrapUnscrapTitle": "கழிவு மேலாண்மை",
  "confirmPassword": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
  "password": "கடவுச்சொல்",
  "selectSites": "தளங்களைத் தேர்ந்தெடுக்கவும்",
  "PCU": "பிசியு",
  "Shop Order": "ஷாப் ஆர்டர்",
  "Process Lot": "பிராசஸ் லாட்",
  "workflowIntegrationMaintenance": "வேலைப்பதிவு ஒருங்கிணைப்பு பராமரிப்பு",
  "workflowIntegration": "வேலைப்பதிவு ஒருங்கிணைப்பு",
  "createWorkflowIntegration": "வேலைப்பதிவு ஒருங்கிணைப்பை உருவாக்கவும்",
  "identifier": "அடையாளம்",
  "messageId": "செய்தி ஐடி",
  "processBy": "இதனால் செயலாக்கவும்",
  "transformationType": "மாற்ற வகை",
  "preprocessJolt": "முந்தைய செயலாக்க ஜோல்ட்",
  "preprocessApi": "முந்தைய செயலாக்க API",
  "serviceApi": "சேவை API",
  "expectedSplits": "எதிர்பார்க்கப்படும் பிரிவுகள்",
  "postProcessJolt": "பிந்தைய செயலாக்க ஜோல்ட்",
  "postProcessApi": "பிந்தைய செயலாக்க API",
  "passHandler": "கைவிடு கையாளல்",
  "failHandler": "தோல்வி கையாளல்",
  "processTransformation": "செயலாக்க மாற்றம்",

  // ============================================== Jolt Spec ===========================================

  "specName": "ஸ்பெக் பெயர்",
  "specNamePlaceholder": "ஸ்பெக் பெயரை உள்ளிடவும்",
  "specNameRequired": "ஸ்பெக் பெயரை உள்ளிடவும்!",
  "typePlaceholder": "வகையைத் தேர்ந்தெடுக்கவும்",
  "typeRequired": "வகையைத் தேர்ந்தெடுக்கவும்!",
  "joltSpec": "ஜோல்ட் ஸ்பெக்",
  "joltSpecPlaceholder": "ஜோல்ட் விவரக்குறிப்பை உள்ளிடவும்",
  "xsltSpec": "XSLT ஸ்பெக்",
  "xsltSpecPlaceholder": "XSLT விவரக்குறிப்பை உள்ளிடவும்",
  "encodeXsltSpec": "என்கோட் XSLT ஸ்பெக்",
  "encodeXsltSpecPlaceholder": "என்கோட் செய்யப்பட்ட XSLT விவரக்குறிப்பை உள்ளிடவும்",
  "jsonAta": "JsonAta ஸ்பெக்",
  "jsonAtaPlaceholder": "JsonAta விவரக்குறிப்பை உள்ளிடவும்",
  "encodedJsonAtaSpec": "என்கோட் செய்யப்பட்ட JsonAta ஸ்பெக்",
  "encodedJsonAtaSpecPlaceholder": "என்கோட் செய்யப்பட்ட JsonAta விவரக்குறிப்பை உள்ளிடவும்",

  "joltAppTitle": "ஜோல்ட் ஸ்பெக் பராமரிப்பு",
  "createSpec": "ஸ்பெக் உருவாக்கு",
  "encode": "என்கோட்",
  "decode": "டீகோட்",
  "spec": "ஸ்பெக்",
  "decodeXsltSpec": "டீகோட் செய்யப்பட்ட XSLT விவரக்குறிப்பு",
  "decodeJsonAtaSpec": "டீகோட் செய்யப்பட்ட JsonAta விவரக்குறிப்பு",

  "entityType": "நிறுவன வகை",
  "eventIntervalSeconds": "நிகழ்வு இடைவெளி வினாடிகள்",
  "cronExpression": "கிரான் வெளிப்பாடு",

  "edit": "திருத்து",
  "runJob": "வேலையை இயக்கு",
  "stopScheduler": "திட்டமிடலை நிறுத்து",
  "machineStatusChange": "இயந்திர நிலை மாற்றம்",

  "apiToProcess": "API செயலாக்கம்",
  "selectPreProcessJolt": "முன் செயலாக்க ஜோல்ட் தேர்வு செய்க",
  "selectPostProcessJolt": "பிந்தைய செயலாக்க ஜோல்ட் தேர்வு செய்க",
  "selectPreProcessXSLT": "முன் செயலாக்க XSLT தேர்வு செய்க",
  "processJoltXslt": "ஜோல்ட் XSLT செயலாக்கம்",
  "splitConfigurations": "பகிர்வு அமைப்புகள்",
  "splitIdentifier": "பகிர்வு அடையாளம்",
  "phasesName": "கட்டங்களின் பெயர்",

  // Adding new translations
  "conditional": "நிபந்தனை",
  "parallel": "இணையான",
  "anyOrder": "எந்த வரிசையும்",

  "orderNumber": "ஆர்டர் எண்",
  "recipeVersion": "செய்முறை பதிப்பு",
  "recipeNo": "செய்முறை எண்",
  "targetQuantity": "இலக்கு அளவு",
  "startDate": "தொடக்க தேதி",
  "finishDate": "முடிவு தேதி",
  "schedFinTime": "திட்டமிடப்பட்ட நிறைவு நேரம்",
  "schedStartTime": "திட்டமிடப்பட்ட தொடக்க நேரம்",
  "selectRecipeNo": "செய்முறை எண்ணை தேர்வுசெய்க",
  "batchNumber": "தொகுப்பு எண்",
  "batchNumberQuantity": "தொகுப்பு எண்ணின் அளவு",

  // ============================================== Process Order Plugin ===========================================
  "complete": "முடிவு",
  "start": "தொடக்கம்",

  // ============================================== NC Group ===========================================
  "ncGroup": "என்சி குழு",
  "ncCode": "என்சி குறியீடு",
  "ncGroups": "என்சி குழுக்கள்",
  "ncGroupAppTitle": "என்சி குழு நிர்வாகம்",
  "ncGroupFilterPriority": "நிக்ஷ���ப்பு குழு விருப்ப முன்னுதிர்வு",
  "validAtAllOperations": "அனைத்து செயல்களிலும் உண்மையானது",

  "parameterBo": "பரிமாண ",
  "operationBO": "செயல்பாடு ",
  "dcGroupBO": "டிசி குழு ",
  "pcuBO": "பிசியு ",
  "testDateTime": "சோதனை தேதி மற்றும் நேரம்",
  "dcGroupDescription": "டிசி குழு விளக்கம்",
  "subStepID": "துணை படி ஐடி",
  "measureStatus": "அளவீட்டு நிலை",
  "measureType": "அளவீட்டு வகை",
  "unitOfMeasure": "அளவீட்டு அலகு",
  "highLimit": "உயர் வரம்பு",
  "lowLimit": "குறைந்த வரம்பு",
  "expected": "எதிர்பார்க்கப்படும்",
  "actualNum": "உண்மையான எண்",
  "dcComment": "டிசி கருத்து",
  "usedLimitSeq": "பயன்படுத்தப்பட்ட வரம்பு வரிசை",
  "elapsedTime": "கடந்த நேரம்",
  "originalActual": "அசல் உண்மை",
  "originalDcComment": "அசல் டிசி கருத்து",
  "originalTestDateTime": "அசல் சோதனை தேதி மற்றும் நேரம்",
  "edited": "திருத்தப்பட்டது",
  "editedUserBO": "திருத்தப்பட்ட பயனர் ",
  "editedDateTime": "திருத்தப்பட்ட தேதி மற்றும் நேரம்",
  "internalMeasureID": "உள் அளவீட்டு ஐடி",
  "routingBO": "வழித்தட ",
  "stepID": "படி ஐடி",
  "userBO": "பயனர் ",
  "overrideUserBO": "மேலெழுதும் பயனர் ",
  "dcGroupVersion": "டிசி குழு பதிப்பு",
  "dcGroup": "டிசி குழு",
  "detail": "விவரம்",
  "viewPdf": "பிடிஎஃப் பார்வை",
  "ncGroupDeleteMessage": "நீங்கள் இந்த என்சி குழுவை நீக்க விரும்புகிறீர்களா?",
  "availableNCCodes": "உபயோகப்படுத்தக்க என்சி குறியீடுகள்",
  "assignNCCodes": "என்சி குறியீட்டை ஒப்புக்கொள்க",
  "createNCGroup": "என்சி குழுவை உருவாக்கு",
  "ncCodeDPMOCategory": "என்சி குறியீட்டு டிபிஎம்ஓ வகை",
  "operationList": "செயல்பாடு பட்டி",
  "assignedNC": "அஸ்ட்டையில் என்சி",
  "availableNC": "மேல்நிலையான என்சி",
  "logNc": "லோக் என்சி",
  "done": "முடிந்தது",
  "NcCodeMaintenance": "என்சி குறியீட்டு பராமரிப்பு",
  "NC Code": "என்சி குறியீடு",
  "operationGroups": "செயல்பாட்டு குழுக்கள்",
  "dispositionRoutings": "கைவிடும் வழிமுறைகள்",
  "NC Groups": "என்சி குழுக்கள்",
  "secondaries": "இரண்டாம் நிலைகள்",
  "createNcCode": "என்சி குறியீட்டை உருவாக்கு",
  "assignNCtoComponent": "குறுக்கு என்சி ஒதுக்கவும்",
  "ncCategory": "என்சி வகை",
  "dpmoCategory": "டிபிஎம்ஓ வகை",
  "ncDatatype": "என்சி தரவுத் தன்மை",
  "collectRequiredNCDataonNC": "என்சியில் தேவைப்படும் என்சி தரவை சேகரிக்கவும்",
  "ncPriority": "என்சி முன்னுரிமை",
  "maximumNCLimit": "அதிகபட்ச என்சி வரம்பு",
  "ncSeverity": "என்சி தீவிரம்",
  "secondaryCodeSpecialInstruction": "இரண்டாம் நிலை குறியீட்டு சிறப்பு அறிவுரை",
  "canBePrimaryCode": "முதன்மை குறியீடாக இருக்க முடியும்",
  "closureRequired": "மூடல் தேவை",
  "autoClosePrimaryNC": "முதன்மை என்சியை தானாக மூடு",
  "autoCloseIncident": "சம்பவத்தை தானாக மூடு",
  "secondaryRequiredForClosure": "மூடலுக்கு இரண்டாம் நிலை தேவை",
  "erpQNCode": "ஈஆர்பி க்யூஎன் குறியீடு",
  "erpCatalog": "ஈஆர்பி பட்டியல்",
  "erpCodeGroup": "ஈஆர்பி குறியீட்டு குழு",
  "erpCode": "ஈஆர்பி குறியீடு",
  "oeeQualityKPIRelevant": "OEE தரம் KPI தொடர்புடையது",
  "selectNcDatatype": "என்சி தரவுத் தன்மையைத் தேர்வுசெய்க",
  "validOperations": "செல்லுபடியாகும் செயல்பாடுகள்",
  "dispositionGroups": "கைவிடும் குழுக்கள்",
  "availableRouting": "கிடைக்கும் வழிமுறைகள்",
  "assignedRouting": "ஒதுக்கப்பட்ட வழிமுறைகள்",
  "availableSecondaries": "கிடைக்கும் இரண்டாம் நிலைகள்",
  "assignedSecondaries": "ஒதுக்கப்பட்ட இரண்டாம் நிலைகள்",
  "availableNcGroups": "கிடைக்கக்கூடிய என்சி குழுக்கள்",
  "assignedNcGroups": "ஒதுக்கப்பட்ட என்சி குழுக்கள்",
  "copyNcCode": "என்சி குறியீட்டை நகல் செய்க",
  "toolNumberMaintenance": "கருவி எண் பராமரிப்பு",
  "toolNumber": "கருவி எண்",
  "toolGroup": "கருவி குழு",
  "qtyAvailable": "கிடைக்கும் அளவு",
  "erpPlanMaintenanceOrder": "ERP திட்ட பராமரிப்பு ஒழுங்கு",
  "toolQty": "கருவி அளவு",
  "createToolNumber": "கருவி எண்ணை உருவாக்கவும்",
  "calibration": "அளவிடுதல்",
  "measurementPoints": "அளவீட்டு புள்ளிகள்",
  "measurementPoint": "அளவீட்டு புள்ளி",
  "calibrationType": "அளவீட்டு வகை",
  "calibrationPeriod": "அளவீட்டு காலம்",
  "calibrationCount": "அளவீட்டு எண்ணிக்கை",
  "maximumCalibrationCount": "அதிகபட்ச அளவீட்டு எண்ணிக்கை",
  "expirationDate": "காலாவதி தேதி",
  "displayClosedNc": "மூடப்பட்ட என்சியை காட்டு",
  "selectRoute": "வழிமுறையை தேர்ந்தெடுக்கவும்",
  "customOrder": "விருப்ப ஒழுங்கு",
  "createToolGroup": "கருவி குழுவை உருவாக்கவும்",
  "timeBased": "நேர அடிப்படையிலான",
  "quantityRequired": "தேவையான அளவு",
  "erpGroup": "ERP குழு",
  "itemVersion": "பொருள் பதிப்பு",
  "trackingControl": "ட்ரைக்கிங் கண்ட்ரோல்",
  "toolGroupMaintenance": "கருவி குழு பராமரிப்பு",
  "listConfiguration": "பட்டி அமைப்பு",
  "multiProcessOrderRelease": "ஏகான பணி வரிசை வெளியுறுத்தல்",
  "multiProcessOrder": "ஏகான பணி வரிசை",
  "phase": "படிகள்",
  "mrpController": "MRP நியமனம்",
  "productionScheduler": "உத்பாட்டு நிர்வாகி",
  "reservationNumber": "பணி எண்",
  "productionStartDate": "உத்பாட்டு தொடக்க தேதி",
  "productionFinishDate": "உத்பாட்டு முடிவு தேதி",
  "actualStartDate": "உண்மை தொடக்க தேதி",
  "actualFinishDate": "உண்மை முடிவு தேதி",
  "inUse": "பயன்படுத்தப்பட்டது",
  "measuredUom": "அளவீட்டு அலகு",
  // ======================================= Certification Maintenance ===========================================
  "certificationmaintenance": "சான்றிதழ் பராமரிப்பு",
  "certifications": "சான்றிதழ்கள்",
  "createCertification": "சான்றிதழ் உருவாக்கு",
  "durationType": "கால வகை",
  "maxNumberOfExtensions": "அதிகபட்ச விரிவாக்கம்",
  "maxExtensionDuration": "அதிகபட்ச நீட்டிப்பு காலம்",
  "assignment": "பணி ஒதுக்கீடு",
  "availableUserGroups": "கிடைக்கும் பயனர் குழுக்கள்",
  "assignedUserGroups": "ஒதுக்கப்பட்ட பயனர் குழுக்கள்",
  "measurementpoints": "அளவீட்டு புள்ளிகள்",
  "copyCertification": "சான்றிதழ் நகல் செய்க",
  "entryPhase": "நுழைவு கட்டம்",
  "exitPhase": "வெளியேறும் கட்டம்",
  "entryOperation": "நுழைவு செயல்பாடு",
  "lastOperationAtPhase": "கட்டத்தில் கடைசி செயல்பாடு",
  "nextPhase": "அடுத்த கட்டம்",

  "accept": "ஏற்றும்",
  "partial": "பகுதி",
  "skip": "நிர்஗மிப்பு",
  "buyOff": "குரியாக்கு",
  "username": "பயனர் பெயர்",
  "userAuthentication": "பயனர் பராமரிப்பு",
  "login": "புதுப்பிக்கும்",
  "activityId": "செயல்பாடு ஐடி",
  "selectPcu": "பொருள் பதிப்பு தேர்ந்தெடுக்கவும்",
  "selectBatchNo": "பெச்செட் எண் தேர்ந்தெடுக்கவும்",
  "createPodMaintenance": "பொருள் பதிப்பு பராமரிப்பு உருவாக்கு",
  "reloadWorkList": "வேலை பட்டியலை மீள்விசை",
  "reloadResource": "மேலதிக வரையறை",
  "settings": "அமைப்புகள்",
  "layout": "வரிசை",
  "PCUOrBatchNumberBrowseActivity": "பொருள் பதிப்பு அல்லது பெச்செட் எண் பராமரிப்பு",
  "PodWorkListActivity": "பொருள் பதிப்பு வேலை பட்டியல்",
  "ButtonActivityInWork": "வேலை பராமரிப்பு",
  "ButtonActivityInQueue": "வரிசை பராமரிப்பு",
  "OnTabOutOfOperation": "செயல்பாட்டில் வெளியேறு",
  "OnTabOutOfWorkcenter": "வேலைமுறையில் வெளியேறு",
  "OnTabOutOfResource": "மேலதிக வரையறை",
  "UpdateFieldsToSession": "நேரத்தில் புலங்களை மேம்படுத்து",
  "scrapQuantity": "சுருள் அளவு",
  "subPod": "உப பொருள் பதிப்பு",
  "podCategory": "பொருள் பதிப்பு வகை",
  "buttonActivityInQueue": "க்ரம சட்டிக்கை",
  "buttonActivityInWork": "கார்ய சட்டிக்கை",
  "activityDescription": "செயல்பாட்டு விவரம்",
  "otherPlugin": "இன்னொரு பிளக்கின்",
  "defaultPlugin": "மூலம் பிளக்கின்",
  "panel": "பேனல்",
  // ============================================== Line Clearance ===========================================
  "lineClearanceMaintenance": "வரி அனுமதி பராமரிப்பு",
  "lineClearance": "வரி அனுமதி",
  "templateName": "வார்ப்புரு பெயர்",
  "clearanceTimeLimit": "அனுமதி நேர வரம்பு",
  "maxPendingTasks": "நிலுவை பணிகள்",
  "clearanceReminderInterval": "நினைவூட்டல் நேரம்",
  "notifyOnCompletion": "முடிவடைந்ததும் அறிவிக்கவும்",
  "enablePhotoEvidence": "புகைப்பட ஆதாரத்தை இயக்கு",
  "associated": "தொடர்புடைய",
  "workcenterId": "பணி மைய ஐடி",
  "resourceName": "வள பெயர்",
  "createLineClearance": "வரி அனுமதி உருவாக்கு",
  "taskid": "பணி ஐடி",
  "taskname": "பணி பெயர்",
  "mandatory": "கட்டாயம்",
  "evidencerequired": "ஆதாரம் தேவை",
  "userRoles": "பயனர் பாத்திரங்கள்",
  "userid": "பயனர் ஐடி",
  "permissions": "அனுமதிகள்",
  "selectUser": "பயனரைத் தேர்ந்தெடுக்கவும்",
  "tasks": "பணிகள்",
  "uomConversion": "யூஓஎம் மாற்றம்",
  "conversion": "மாற்றம்",
  "materialCountConversion": "பொருள் எண் மாற்றம்",
  "convertUom": "யூஓஎம் மாற்றம்",
  "count": "எண்",
  "conversionDeleteMessage": "இந்த மாற்றத்தை நீக்க விரும்புகிறீர்களா?",
  "baseAmt": "ஆதார தொகை",
  "conversionItem": "மாற்றத்தை பொருத்தமான பொருள்",
  "areYouSureDeleteThisSplit": "இந்த விரிவாக்கத்தை நீக்க விரும்புகிறீர்களா?",
  "attach": "இணைக்கவும்",
  "filePreview": "படத்தை முன்னோட்டம்",
  "change": "மாற்றம்",
  "preview": "முன்னோட்டம்",
  "reloadSiteConfirmation": "இந்த வரிசையை மீள்விசை செய்ய உறுதியாக இருக்கிறீர்களா?",
  "phaseCanBeChanged": "கட்டம் மாற்றம்",
  "showResource": "வள காட்டு",
  "showOperation": "செயல் காட்டு",
  "showPhase": "கட்டம் காட்டு",
  "auditLogReport": "அலாப்பட்டு பதிவு பட்டியல்",
  "dataCollectionReport": "தரவு கலைப்பு பட்டியல்",
  "dataCollectionGraph": "தரவு கலைப்பு வரைப்படம்",
  "selectCategory": "வகையை தேர்ந்தெடுக்கவும்",
  "currentSetting": "தற்போதைய அமைப்பு",
  "date/time": "தேதி/நேரம்",
  "changeType": "மாற்ற வகை",
  "dateRange": "தேதி வரையாடை",
  "time": "நேரம்",
  "topicConfiguration": "டோபிக் கொந்திக்கரைவு",
  "createTopicConfiguration": "டோபிக் கொந்திக்கரைவு உருவாக்கு",
  "topicName": "டோபிக் பெயர்",
  "apiUrl": "ஏபிஐ யுஆர்ல்",

  "taskDescription": "பணி விவரம்",
  "evidence": "பிரமாணம்",
  "startedDateTime": "ப்ராரஂ஭ிக்கப்பட்ட தேதி",
  "completedDateTime": "முடிவுறுத்தப்பட்ட தேதி",
  "reason": "காரணம்",
  "approved": "ஏற்றும்",
  "approvedDateTime": "ஏற்றும் தேதி",
  "approvedBy": "ஏற்றும் பயனர்",
  "rejectedDateTime": "ரத்துப்படுத்தப்பட்ட தேதி",
  "rejectedBy": "ரத்துப்படுத்தப்பட்ட பயனர்",
  "updatedDateTime": "மேம்படுத்தப்பட்ட தேதி",
  "updatedBy": "மேம்படுத்தப்பட்ட பயனர்",
  "startedBy": "ப்ராரஂ஭ிக்கப்பட்ட பயனர்",
  "completedBy": "முடிவுறுத்தப்பட்ட பயனர்",
  "taskName": "பணி பெயர்",
  "isMandatory": "அவசியம்",
  "evidenceRequired": "பிரமாணம் தேவை",
  "theme": "தேம்",
  "cycleTime(sec)": "சுழற்சி நேரம் (நொடி)",

  "shiftStart": "மாற்றம் ப்ராரஂ஭ம்",
  "shiftEnd": "மாற்றம் முடிவு",
  "shiftAvailableTime": "மாற்றம் உபயோகப்படுத்தப்படும் நேரம்",
  "totalBreakHours": "மொத்த பருமன் நேரம்",
  "createdDatetime": "உருவாக்கப்பட்ட நேரம்",
  "updatedDatetime": "மேம்படுத்தப்பட்ட நேரம்",
  "createdBy": "உருவாக்கப்பட்ட பயனர்",
  "eventData": "நிகழ்வு தரவு",
  "plant": "பாலம்",
  "eventType": "நிகழ்வு வகை",
  "buyOffAction": "குரியாக்கு செயல்",
  "history": "வரலாறு",
  "endDate": "முடிவு தேதி",
  "selectSite": "தேர்ந்தெடுக்கவும் இடம்",
  "downtimeType": "மாற்றம் வகை",
  "selectStatus": "நிலையை தேர்ந்தெடுக்கவும்",
  "selectNewStatus": "புதிய நிலையை தேர்ந்தெடுக்கவும்",
  "selectBatchNumber": "தொகுப்பு எண் தேர்ந்தெடுக்கவும்",
  "selectOrderNumber": "வரிசை எண் தேர்ந்தெடுக்கவும்",
  "batchStepStatus": "தொகுப்பு பட்டியல் நிலை",
  "PhaseId": "கட்டம் ஐடி",
  "InQueueQty": "க்ரம அளவு",
  "InWorkQty": "வேலை அளவு",
  "CompleteQty": "முடிவுறுத்தப்பட்ட அளவு",
  "batchStartedTime": "தொகுப்பு தொடங்கப்பட்ட நேரம்",
  "batchCompletedTime": "தொகுப்பு முடிவுறுத்தப்பட்ட நேரம்",
  "approval": "ஏற்றும்",
  "ScrapQty": "சுருள் அளவு",
  "level": "மட்டம்",
  "message": "செய்தி",


  "activityHookId": "செயல்பாட்டு ஹூக் ஐடி",
  "targetClass": "இலக்கு வகுப்பு",
  "targetMethod": "இலக்கு முறை",
  "hookType": "ஹூக் வகை",
  "hookClass": "ஹூக் வகுப்பு",
  "hookMethod": "ஹூக் முறை",
  "executionMode": "செயல்படுத்தும் முறை",
  "logo": "லோகோ",
  "background": "பாதிப்பு",
  "color": "நிறம்",
  "lineColor": "வரி நிறம்",

  "plannedCycleTime": "நிர்வாகிக்கப்பட்ட சுழற்சி நேரம்",
  "actualCycleTime": "உண்மையான சுழற்சி நேரம்",
  "totalBreakInMinutes": "மொத்த பருமன் நேரம் (நிமிடங்கள்)",

  "serviceExtensionAppTitle": "சேவை விரிவாக்க பராமரிப்பு",
  "serviceExtension": "சேவை விஸ்தரண்",
  "createServiceExtension": "சேவை விஸ்தரண் உருவாக்கு",
  "createExtension": "விஸ்தரண் உருவாக்கு",
  "selectResourceType": "ஸ்ரோத்தவக்கு வகை தேர்ந்தெடு",
  "executionPointId": "செயல்படுத்தல் புள்ளி ஐடி",
  "extensionDeleteMessage": "இந்த நீட்டிப்பை நீக்க விரும்புகிறீர்களா?",
  "executionPoint": "செயல்படுத்தல் புள்ளி",
  "extensionActivity": "நீட்டிப்பு செயல்பாடு",
  "MaterialDescription": "பொருள் விவரம்",
  "releaseTime": "வெளியேறும் நேரம்",
  "unitOfMeasurement": "அளவீட்டு முறை",
  "releaseOrder": "ஆணை விடுவிப்பு",
  "createdDateTime": "உருவாக்கப்பட்ட நேரம்",
  "releaseQty": "வெளியேறும் அளவு",
  "productionTime": "உத்பாதிப்பு நேரம்",
  'productCode': 'பொருள் குறியீடு',
  'productName': 'பொருள் பெயர்',
  'downloadDate': 'பதிவிறக்கம் தேதி',
  'batchStatus': 'தொகுப்பு நிலை',

  "createConfiguration": "கான்பிகரேஷன் உருவாக்கு",
  "apiConfiguration": "ஏபிஐ கான்பிகரேஷன்",
  "storedProcedure": "சேமிக்கப்பட்ட நடவடிக்கை",
  "httpMethod": "எச்டிடிபி முறை",
  "inputParameters": "உள்ளீடு பராமெட்டர்கள்",
  "outputStructure": "வெளியீடு கட்டமைப்பு",
  "apiName": "ஏபிஐ பெயர்",
  "deleteApiConfigMessage": "இந்த கான்பிகரேஷனை நீக்க விரும்புகிறீர்களா?",
  "apiConfigMaintenance": "ஏபிஐ கான்பிகரேஷன் பராமரிப்பு",
  "configuration": "கான்பிகரேஷன்",
  "phaseType": "திரும்பு வகை",

  "shiftId": "திரும்பு ஐடி",
  "selectShift": "திரும்பு தேர்ந்தெடுக்கவும்",

  "productGroup": "பொருள் குழு",
  "selectProductGroup": "பொருள் குழு தேர்ந்தெடுக்கவும்",

  "attachmentType": "இணைப்பு வகை",
  "attachedTo": "இணைக்கப்பட்டது",
  "attachedStatus": "இணைப்பு நிலை",
  "default": "இயல்புநிலை",
  "userRoleConfiguration": "பயனர் பாத்திர அமைப்பு",
  "workflowId": "வேலைப்பாடு ஐடி",
  "workflowName": "வேலைப்பாடு பெயர்",
  "entityValue": "அலகு மதிப்பு",
  "appliesTo": "விண்ணப்பிக்கிறது",
  "reference": "குறிப்பு",
  "mainForm": "முதன்மை படிவம்",
  "generalInstructions": "பொது வழிமுறைகள்",
  "ccps": "முக்கிய கட்டுப்பாட்டு புள்ளிகள்",
  "stageInstructions": "கட்டம் வழிமுறைகள்",

  "baseQty": "அடிப்படை அளவு",

  "documentLinkPlugin": "ஆவண இணைப்பு செருகுநிரல்",
  "documentLinks ": "ஆவண இணைப்புகள் ",
  "docType": "ஆவண வகை",
  "annexureCount": "ஆவண பெறுகள் ஐம்புகள்",
  "basicInformation": "புரட்சியில் கீழ்கண்டவை",
  "mainDocument": "முதன்மை ஆவண",
  "annexures": "ஆவண பெறுகள்",
  "selectWorkflowReference": "வேலைப்பாடு உல்லேಖ ஆய்கெமாட்டு",
  "templateReference": "டெம்ப்ளேட் குறிப்பு",
  "selectTemplateReference": "டெம்ப்ளேட் குறிப்பைத் தேர்ந்தெடுக்கவும்",
  "annexure": "இணைப்பு",
  "workflowReference": "வேலைப்பாடு உல்லேಖ",
  "addAnnexure": "இணைப்பு கைப்பறை",
  "copyDocumentLink": "ஆவண இணைப்பை நகலெடுக்கவும்",
  "Annexure Count": "இணைப்பு எண்ணிக்கை",
  "Doc Type": "ஆவண பெயர்",
  "Item Group": "வேலைப்பாடு குழு",
  "Template Name": "டெம்ப்ளேட் பெயர்",
  "Workflow ID": "வேலைப்பாடு ஐடி",
  "Workflow Name": "வேலைப்பாடு பெயர்",
  "noDocumentsFound": "ஆவணங்கள் எதுவும் கிடைக்கவில்லை",
  "pleaseSelectTheDocumentType": "ஆவண வகை தேர்ந்தெடுக்கவும்",
  "annexureCountIsRequired": "இணைப்பு எண்ணிக்கை தேவை",
  "pleaseFillInTheFollowingRequiredFields": "பின்வரும் தேவையான புலங்களை நிரப்பவும்",
  "createDocumentLink": "ஆவண இணைப்பை உருவாக்கு",
  "documentLinkCopiedSuccessfully": "ஆவண இணைப்பை நகலெடுக்கப்பட்டது",
  "documentLinkApp": "ஆவண இணைப்பை செயல்படுத்தவும்",
  "documentLinkDeletedSuccessfully": "ஆவண இணைப்பை நீக்கப்பட்டது",
  "deleteFailed": "நீக்கவு தோல்வி",
  "createNewPhase": "புதிய கட்டத்தை உருவாக்கவும்",
  "phaseConfiguration": "கட்ட அமைப்பு",
  "operations": "செயல்பாடுகள்",
  "triggeredPhase": "தொடங்கப்பட்ட கட்டம்",
  "searchOperations": "செயல்பாடுகளைத் தேடவும்",
  "back": "பின் செல்ல",
  "validate": "சரிபார்க்கவும்",
  "relayout": "மீளமைக்கவும்",
  "createPhase": "கட்ட உருவாக்கவும்",
  "editPhaseId": "கட்ட ஐடி திருத்தவும்",
  "savePhase": "கட்டத்தைச் சேமிக்கவும்",
  "clone": "நகலெடுக்கவும்",
  "procedureMaintenance": "செயல்முறை பராமரிப்பு",
  "searchProcedureId": "செயல்முறை ஐடி தேடவும்",
  "procedureId": "செயல்முறை ஐடி",
  "procedureName": "செயல்முறை பெயர்",
  "procedureConfiguration": "செயல்முறை அமைப்பு",
  "effectiveFrom": "செயலில் இருந்து",
  "effectiveTo": "செயலில் வரை",
  "nodeDetails": "நோட் விவரங்கள்",
  "operationDetails": "செயல்பாட்டு விவரங்கள்",
  "basicDetails": "அடிப்படை விவரங்கள்",
  "sequenceNumber": "வரிசை எண்",
  "operationName": "செயல்பாட்டு பெயர்",
  "timing": "நேரம்",
  "expectedDurationMin": "எதிர்பார்க்கப்படும் காலம் (நிமிடங்கள்)",
  "durationMin": "கால அளவு (நிமிடங்கள்)",
  "actualDurationMin": "உண்மையான காலம் (நிமிடங்கள்)",
  "flags": "கொடி",
  "critical": "முக்கியமானது",
  "optional": "விருப்பமானது",
  "finalOperation": "இறுதி செயல்பாடு",
  "operationConnections": "செயல்பாட்டு இணைப்புகள்",
  "previousOperation": "முந்தைய செயல்பாடு",
  "nextOperation": "அடுத்த செயல்பாடு",
  "completionCriteria": "முடிவு அளவுகோல்",
  "dcVersion": "டிசி பதிப்பு",
  "wiVersion": "டபிள்யூஐ பதிப்பு",
  "procedureVersion": "செயல்முறை பதிப்பு",
  "wfVersion": "டபிள்யூஎப் பதிப்பு",
  "previousNodes": "முந்தைய நோட்கள்",
  "nextNodes": "அடுத்த நோட்கள்",
  "entryNode": "நுழைவு நோட்",
  "finalNode": "இறுதி நோட்",
  "multiDimensionalDataCollection": "பன்முக தரவு சேகரிப்பு",
  "dataCollectionName": "தரவு சேகரிப்பு பெயர்",
  "createDataCollection": "தரவு சேகரிப்பை உருவாக்கவும்",
  "editDataCollection": "தரவு சேகரிப்பை திருத்தவும்",
  "attachmentPoint": "இணைப்பு புள்ளி",
  "dataCollectionGroups": "தரவு சேகரிப்பு குழுக்கள்",
  "basicConfiguration": "அடிப்படை அமைப்பு",
  "groupName": "குழு பெயர்",
  "collectionType": "சேகரிப்பு வகை",
  "layoutType": "அமைப்பு வகை",
  "requiredGroup": "தேவையான குழு",
  "repeatableRows": "மீண்டும் வரக்கூடிய வரிசைகள்",
  "tableRowNumber": "அட்டவணை வரிசை எண்",
  "tablePreview": "அட்டவணை முன்னோட்டம்",
  "addColumn": "நெடுவரிசை சேர்க்கவும்",
  "fieldConfiguration": "புல அமைப்பு",
  "label": "லேபல்",
  "defaultValue": "இயல்புநிலை மதிப்பு",
  "readOnly": "வாசிக்க மட்டும்",
  "prefillingRows": "முன்னிருப்பு வரிசைகள்",
  "validationRules": "சரிபார்ப்பு விதிகள்",
  "saveGroup": "குழுவைச் சேமிக்கவும்",
  "phaseAttachments": "அடுக்கின் இணைப்புகள்",
  "createProcedure": "செயல்முறையை உருவாக்கு",
  "saveProcedure": "செயல்முறையை சேமி",
  "createNewProcedure": "புதிய செயல்முறை உருவாக்கு",
  "editProcedure": "செயல்முறையை திருத்து",
  "materialConsumption": "பொருள் நுகர்வு",
  "attachmentPoints": "இணைப்பு புள்ளிகள்",
  "cloneDataCollection": "தரவு சேகரிப்பை நகலெடு",
  "deleteDataCollection": "தரவு சேகரிப்பை நீக்கு",
  "areYouSureYouWantToDeleteThisDataCollection": "இந்த தரவு சேகரிப்பை நீக்க விரும்புகிறீர்களா?",
  "column": "நெடுவரிசை",
  "field": "புலம்",
  "table": "அட்டவணை",
  "form": "படிவம்",
  "unitofMeasure": "அளவீட்டு அலகு",
  "targetValue": "இலக்கு மதிப்பு",
  "targetBand": "இலக்கு வரம்பு",
  "options": "விருப்பங்கள்",
  "trueValue": "உண்மை மதிப்பு",
  "falseValue": "பொய் மதிப்பு",
  "attachments": "இணைப்புகள்",
  "editPhase": "அடுக்கு திருத்து",
  "dataCollectionReferences": "தரவு சேகரிப்பு குறிப்புகள்",
  "workInstructionReferences": "பணி உத்தரவு குறிப்புகள்",
  "toolGroupReferences": "குவி குழு குறிப்புகள்",
  "procedureReferences": "செயல்முறை குறிப்புகள்",
  "dataCollectionId": "தரவு சேகரிப்பு ஐடி",
  "dataCollectionVersion": "தரவு சேகரிப்பு பதிப்பு",
  "workInstructionId": "பணி உத்தரவு ஐடி",
  "workInstructionVersion": "பணி உத்தரவு பதிப்பு",
  "toolGroupId": "குவி குழு ஐடி",
  "toolGroupVersion": "குவி குழு பதிப்பு",
  "addRow": "வரிசை சேர்க்கவும்",
  "noReferencesAdded": "குறிப்புகள் இன்னும் சேர்க்கப்படவில்லை",
  "yieldPercentage": "உற்பத்தி (%)",
  "expectedYield": "எதிர்பார்க்கப்பட்ட உற்பத்தி",
  "minimumYield": "குறைந்தபட்ச உற்பத்தி",
  "maximumYield": "அதிகபட்ச உற்பத்தி",

  // Recipe Enhancements

  "product": "தயாரிப்பு",
  "usageCount": "பயன்பாடு எண்ணிக்கை",
  "lastUsedDate": "இறுதியாக பயன்படுத்திய தேதி",
  "duplicate": "நகல்",
  "import": "இறக்குமதி",
  "export": "ஏற்றுமதி",
  "searchRecipes": "சமையல் குறிப்புகளைத் தேடுங்கள்...",
  "statusFilter": "நிலை வடிகட்டி",
  "draft": "வரைவு",
  "total": "மொத்தம்",
  "recipes": "சமையல் குறிப்புகள்",
  "newRecipe": "புதிய சமையல் குறிப்பு",
  "headerTab": "தலைப்பு",
  "ingredientsTab": "பொருட்கள்",
  "phasesAndOperations": "அடுக்கு மற்றும் செயல்பாடுகள்",
  "yieldAndProducts": "உற்பத்தி மற்றும் தயாரிப்புகள்",
  "referenceLinks": "குறிப்பு இணைப்புகள்",
  "yieldAndProductsComingSoon": "உற்பத்தி மற்றும் தயாரிப்புகள் - விரைவில்",
  "referenceLinksComingSoon": "குறிப்பு இணைப்புகள் - விரைவில்",
  "productionParameters": "உற்பத்தி அளவுருக்கள்",
  "bmrHeaders": "BMR தலைப்புகள்",
  "recipeNameLabel": "சமையல் குறிப்பு பெயர்",
  "versionLabel": "பதிப்பு",
  "currentVersionLabel": "தற்போதைய பதிப்பு",
  "statusLabel": "நிலை",
  "workCenterIdLabel": "பணியகம் ஐடி",
  "processTypeLabel": "செயல்முறை வகை",
  "activeStatusLabel": "செயலில் உள்ள நிலை",
  "recipeDescriptionLabel": "சமையல் குறிப்பு விளக்கம்",
  "batchSizeLabel": "தொகுதி அளவு",
  "batchUomLabel": "தொகுதி அளவீட்டு அலகு",
  "expectedCycleTimeLabel": "எதிர்பார்க்கப்பட்ட சுழற்சி நேரம்",
  "actualCycleTimeLabel": "உண்மையான சுழற்சி நேரம்",
  "scalingTypeLabel": "அளவாக்க வகை",
  "minBatchSizeLabel": "குறைந்தபட்ச தொகுதி அளவு",
  "maxBatchSizeLabel": "அதிகபட்ச தொகுதி அளவு",
  "scalingFactorLabel": "அளவாக்க காரணி",
  "companyNameLabel": "நிறுவனத்தின் பெயர்",
  "documentTitleLabel": "ஆவணத்தின் தலைப்பு",
  "documentNoLabel": "ஆவண எண்",
  "marketLabel": "சந்தை",
  "standardBatchSizeLabel": "நியமித்த தொகுதி அளவு",
  "productNameLabel": "தயாரிப்பு பெயர்",
  "effectiveDateLabel": "செயல்படும் தேதி",
  "expiryDateLabel": "காலாவதி தேதி",
  "shelfLifeLabel": "சேமிப்பு ஆயுள்",
  "manufacturingLicenseLabel": "உற்பத்தி உரிமம்",
  "recipeNamePlaceholder": "சமையல் குறிப்பு பெயரை உள்ளிடவும்",
  "versionPlaceholder": "1.0",
  "statusPlaceholder": "நிலையைத் தேர்ந்தெடுக்கவும்",
  "workCenterIdPlaceholder": "பணியகம் ஐடியை உள்ளிடவும்",
  "processTypePlaceholder": "செயல்முறை வகையைத் தேர்ந்தெடுக்கவும்",
  "recipeDescriptionPlaceholder": "சமையல் குறிப்பு விளக்கத்தை உள்ளிடவும்",
  "workCenterIdRequired": "தயவுசெய்து பணியகம் ஐடியை உள்ளிடவும்",
  "recipeDescriptionRequired": "தயவுசெய்து சமையல் குறிப்பு விளக்கத்தை உள்ளிடவும்",
  "batchSizePlaceholder": "தொகுதி அளவை உள்ளிடவும்",
  "batchUomPlaceholder": "அளவீட்டு அலகைத் தேர்ந்தெடுக்கவும்",
  "expectedCycleTimePlaceholder": "எ.கா., 48h",
  "actualCycleTimePlaceholder": "எ.கா., 45h",
  "scalingTypePlaceholder": "அளவாக்க வகையைத் தேர்ந்தெடுக்கவும்",
  "minBatchSizePlaceholder": "குறைந்தபட்ச அளவு",
  "maxBatchSizePlaceholder": "அதிகபட்ச அளவு",
  "scalingFactorPlaceholder": "1.0",
  "companyNamePlaceholder": "நிறுவனத்தின் பெயரை உள்ளிடவும்",
  "documentTitlePlaceholder": "தொகுதி உற்பத்தி பதிவேடு",
  "documentNoPlaceholder": "ஆவண எண்ணை உள்ளிடவும்",
  "marketPlaceholder": "சந்தையை உள்ளிடவும்",
  "standardBatchSizePlaceholder": "நியமித்த தொகுதி அளவை உள்ளிடவும்",
  "productNamePlaceholder": "தயாரிப்பு பெயரை உள்ளிடவும்",
  "shelfLifePlaceholder": "எ.கா., 3 வருடங்கள்",
  "manufacturingLicensePlaceholder": "உரிம எண்னை உள்ளிடவும்",
  "recipeNameRequired": "சமையல் குறிப்பு பெயரை உள்ளிடவும்",
  "versionRequired": "பதிப்பை உள்ளிடவும்",
  "statusRequired": "நிலையைத் தேர்ந்தெடுக்கவும்",
  "processTypeRequired": "செயல்முறை வகையைத் தேர்ந்தெடுக்கவும்",
  "batchSizeRequired": "தொகுதி அளவை உள்ளிடவும்",
  "batchUomRequired": "அளவீட்டு அலகைத் தேர்ந்தெடுக்கவும்",
  "expectedCycleTimeRequired": "எதிர்பார்க்கப்பட்ட சுழற்சி நேரத்தை உள்ளிடவும்",
  "scalingTypeRequired": "அளவாக்க வகையைத் தேர்ந்தெடுக்கவும்",
  "minBatchSizeRequired": "குறைந்தபட்ச தொகுதி அளவை உள்ளிடவும்",
  "maxBatchSizeRequired": "அதிகபட்ச தொகுதி அளவை உள்ளிடவும்",
  "scalingFactorRequired": "அளவாக்க காரணியை உள்ளிடவும்",
  "companyNameRequired": "நிறுவனத்தின் பெயரை உள்ளிடவும்",
  "documentTitleRequired": "ஆவணத்தின் தலைப்பை உள்ளிடவும்",
  "documentNoRequired": "ஆவண எண்ணை உள்ளிடவும்",
  "marketRequired": "சந்தையை உள்ளிடவும்",
  "standardBatchSizeRequired": "நியமித்த தொகுதி அளவை உள்ளிடவும்",
  "productNameRequired": "தயாரிப்பு பெயரை உள்ளிடவும்",
  "effectiveDateRequired": "செயல்படும் தேதியைத் தேர்ந்தெடுக்கவும்",
  "expiryDateRequired": "காலாவதி தேதியைத் தேர்ந்தெடுக்கவும்",
  "shelfLifeRequired": "சேமிப்பு ஆயுளை உள்ளிடவும்",
  "manufacturingLicenseRequired": "உரிம எண்னை உள்ளிடவும்",
  "batchOption": "தொகுதி",
  "continuousOption": "தொடர்ச்சியான",
  "semiContinuousOption": "அரை தொடர்ச்சியான",
  "underReview": "மதிப்பாய்வில் உள்ளது",
  "linearOption": "நேரியல்",
  "nonLinearOption": "அநேரியல்",
  "ingredientRemovedSuccess": "பொருள் வெற்றிகரமாக நீக்கப்பட்டது",
  "ingredientAddedSuccess": "பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது",
  "ingredientUpdatedSuccess": "பொருள் வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
  "codeLabel": "குறியீடு",
  "deleteIngredientTitle": "பொருளை நீக்கவா?",
  "deleteIngredientDescription": "இந்த பொருளை நிச்சயமாக நீக்க விரும்புகிறீர்களா?",
  "subtotal": "கூட்டுத்தொகை",
  "itemsLabel": "உருப்படிகள்",
  "totalQuantity": "மொத்த அளவு",
  "quantityUnit": "கிலோ",
  "totalPercentage": "மொத்த %",
  "totalIngredients": "மொத்த பொருட்கள்",
  "overallTotal": "மொத்த தொகை",
  "addNonBom": "Non-BOM ஐச் சேர்க்கவும்",
  "sequenceShort": "வரிசை",
  "ingredientNameColumn": "பொருள் பெயர்",
  "percentageColumn": "பிளவுகள்",
  "quantityColumn": "பெயர்",
  "uomColumn": "அளவீட்டு அலகு",

  "companyDocumentInfo": "நிறுவனம் & ஆவண தகவல்",
  "productManufacturingInfo": "தயாரிப்பு & உற்பத்தி தகவல்",
  "actualBatchSizeLabel": "உண்மையான பேட்ச் அளவு",
  "actualBatchSizeRequired": "உண்மையான பேட்ச் அளவை உள்ளிடவும்",
  "actualBatchSizePlaceholder": "உண்மையான பேட்ச் அளவை உள்ளிடவும்",
  "supersedesDocumentNoAndDateLabel": "முந்தைய ஆவண எண் & தேதி",
  "supersedesDocumentNoAndDateRequired": "முந்தைய ஆவண எண் மற்றும் தேதியை உள்ளிடவும்",
  "supersedesDocumentNoAndDatePlaceholder": "உதா., BMR/3003687/1157/01-00 & 07/08/2020",
  "cmlLabel": "CML",
  "cmlRequired": "CML ஐ உள்ளிடவும்",
  "cmlPlaceholder": "உதா., All Kind",
  "batchNoLabel": "பேட்ச் எண்",
  "batchNoRequired": "பேட்ச் எண்ணை உள்ளிடவும்",
  "batchNoPlaceholder": "ஒவ்வொரு பேட்ச்-க்கும் ஒதுக்கப்படும்",
  "semiFinishedProductCodeLabel": "அரை முடிக்கப்பட்ட தயாரிப்பு குறியீடு",
  "semiFinishedProductCodeRequired": "அரை முடிக்கப்பட்ட தயாரிப்பு குறியீட்டை உள்ளிடவும்",
  "semiFinishedProductCodePlaceholder": "உதா., 3003687/01",
  "mfrRefLabel": "MFR குறிப்பு",
  "mfrRefRequired": "MFR குறிப்பை உள்ளிடவும்",
  "mfrRefPlaceholder": "உதா., MFR/PH/19/0039/00",
  "manufacturingDateLabel": "உற்பத்தி தேதி",
  "manufacturingDateRequired": "உற்பத்தி தேதியைத் தேர்ந்தெடுக்கவும்",
  "manufacturingDatePlaceholder": "தேதியைத் தேர்ந்தெடுக்கவும்",
  "batchCommencedOnLabel": "பேட்ச் தொடங்கிய தேதி",
  "batchCommencedOnRequired": "பேட்ச் தொடங்கிய தேதியைத் தேர்ந்தெடுக்கவும்",
  "batchCommencedOnPlaceholder": "தேதியைத் தேர்ந்தெடுக்கவும்",
  "batchCompletedOnLabel": "பேட்ச் முடிந்த தேதி",
  "batchCompletedOnRequired": "பேட்ச் முடிந்த தேதியைத் தேர்ந்தெடுக்கவும்",
  "batchCompletedOnPlaceholder": "தேதியைத் தேர்ந்தெடுக்கவும்",
  "totalQuantityLabel": "மொத்த அளவு",
  "totalQuantityRequired": "மொத்த அளவை உள்ளிடவும்",
  "totalQuantityPlaceholder": "உதா., ___ Kg",
  "manufacturingYieldLabel": "உற்பத்தி விளைவு (%)",
  "manufacturingYieldRequired": "உற்பத்தி விளைவை உள்ளிடவும்",
  "manufacturingYieldPlaceholder": "உதா., ___ %",
  "breakdownOrDeviationLabel": "கேடு / சாய்வு",
  "breakdownOrDeviationRequired": "கேடு அல்லது சாய்வு விவரங்களை உள்ளிடவும்",
  "breakdownOrDeviationPlaceholder": "ஆம்/இல்லை + குறிப்புகள் இருந்தால்",
  "reviewedByProductionLabel": "மதிப்பாய்வு செய்தவர் (Production)",
  "reviewedByProductionRequired": "Production மதிப்பாய்வாளரை உள்ளிடவும்",
  "reviewedByProductionPlaceholder": "கையொப்பம் / தேதி",
  "reviewedByQALabel": "மதிப்பாய்வு செய்தவர் (QA)",
  "reviewedByQARequired": "QA மதிப்பாய்வாளரை உள்ளிடவும்",
  "reviewedByQAPlaceholder": "கையொப்பம் / தேதி",
  "addAttachment": "இணைப்பு சேர்க்கவும்",

  "searchDataCollectionName": "தரவுகளை தேடவும்",
  "numberOfColumns": "கோலோமுகள் எண்ணிக்கு",
  "procedureType": "தொழுதி வகை",
  "addNewToolGroup": "புதிய கருவி குழு",

  // ============================================== Historical Filter Table / OEE Tabs ===========================================
  "oeeBack": "பின்",
  "overallOee": "முழு OEE:",
  "oeeAvailability": "கிடைக்கும் தன்மை",
  "oeePerformance": "செயல்திறன்",
  "oeeQuality": "தரம்",
  "oeeExpand": "விரிவாக்கு",
  "oeeCollapse": "சுருக்கு",
  "expandToFullWidth": "முழு அகலத்திற்கு விரிவாக்கு",
  "machineTimeline": "இயந்திர நேரக்கோடு",
  "oeeResource": "வளம்",
  "oeeDate": "தேதி",
  "oeeAvailable": "கிடைக்கும்",
  "oeePlannedDowntime": "திட்டமிடப்பட்ட இறங்கு நேரம்",
  "oeeUnplannedDowntime": "திட்டமிடாத இறங்கு நேரம்",
  "batchwiseData": "தொகுதிவார தரவு",
  "oeeTotal": "முழு",
  "oeeRecords": "பதிவுகள்",
  "oeeFrom": "இலிருந்து",
  "oeeResources": "வளங்கள்",
  "clickOnChartBarToLoadBatchDetails": "தொகுதி விவரங்களை ஏற்ற வரைபடத்தில் கிளிக் செய்யவும்",
  "downloadAsExcel": "எக்ஸலாக பதிவிறக்கு",
  "oeeExport": "ஏற்றுமதி",
  "exitFullscreen": "முழுத்திரையிலிருந்து வெளியேறு",
  "fullscreenView": "முழுத்திரை காட்சி",
  "exitTableView": "அட்டவணை காட்சியிலிருந்து வெளியேறு",
  "oeeFilters": "வடிகட்டிகள்:",
  "placeholderResource": "வளம்",
  "placeholderDate": "தேதி",
  "placeholderBatchNo": "தொகுதி எண்",
  "oeeSelected": "தேர்ந்தெடுக்கப்பட்டது:",
  "oeeClearSelection": "தேர்வை நீக்கு",
  "selectionCleared": "தேர்வு நீக்கப்பட்டது",
  "allSelectionsCleared": "அனைத்து தேர்வுகளும் நீக்கப்பட்டன",
  "updatedBatchData": "தொகுதி தரவு புதுப்பிக்கப்பட்டது",
  "failedToRefreshBatchData": "தொகுதி தரவை புதுப்பிக்க முடியவில்லை",
  "oeeOrderNo": "ஆணை எண்",
  "oeeItemCode": "உருப்படி கோட்",
  "oeeProduct": "தயாரிப்பு",
  "oeePlanQty": "திட்ட அளவு",
  "oeeActualQty": "உண்மை அளவு",
  "oeePlanDT": "திட்ட DT",
  "oeeActualPT": "உண்மை PT",
  "oeePlanPT": "திட்ட PT",
  "oeeUnplanDT": "திட்டமிடாத DT",
  "oeeGoodQty": "நல்ல அளவு",
  "oeeBadQty": "கெட்ட அளவு",
  "oeeCycleTime": "சுழற்சி நேரம்",
  "oeeActualCycleTime": "உண்மை சுழற்சி நேரம்",
  "oeeOee": "OEE",
  "downtimeDetails": "இறங்கு நேர விவரங்கள்",
  "oeeDetails": "விவரங்கள்",
  "viewDowntimeDetails": "இறங்கு நேர விவரங்களை பார்க்கவும்",
  "downtimeAnalysisReport": "இறங்கு நேர பகுப்பாய்வு அறிக்கை",
  "oeeUnplannedDowntimes": "திட்டமிடாத இறங்கு நேரங்கள்",
  "oeePlannedDowntimes": "திட்டமிடப்பட்ட இறங்கு நேரங்கள்",
  "lineClearanceActivities": "வரிசை அகற்றும் செயல்கள்",
  "oeeReasonCode": "காரண கோட்",
  "oeeReasonDescription": "காரண விவரம்",
  "oeeDowntime": "இறங்கு நேரம்",
  "downtimeMinutes": "இறங்கு நேரம் (நிமிடங்கள்)",
  "oeeNA": "கிடைக்கவில்லை",
  "oeeTargetQuantity": "இலக்கு அளவு",
  "oeeUom": "அளவீட்டு அலகு",
  "oeeProductName": "தயாரிப்பு பெயர்",
  "excellentNoDowntimeEvents": "சிறப்பானது! இறங்கு நேர நிகழ்வுகள் எதுவும் பதிவு செய்யப்படவில்லை",
  "batchCompletedWithoutInterruptions": "திட்டமிடப்பட்ட அல்லது திட்டமிடாத தடைகள் இல்லாமல் இந்த தொகுதி முடிந்தது.",
  "noMessageFound": "{{message}} எதுவும் கிடைக்கவில்லை",
  "noMessageDuringPeriod": "தேர்ந்தெடுக்கப்பட்ட காலத்தில் இந்த தொகுதியில் {{message}} எதுவும் இல்லை.",
  "errorLoadingData": "தரவை ஏற்றுவதில் பிழை",
  "oeeReason": "காரணம்",
  "oeeRootCause": "மூல காரணம்",
  "oeeDuration": "கால அளவு",
  "oeeStartTime": "தொடக்க நேரம்",
  "oeeEndTime": "முடிவு நேரம்",
  "oeeComment": "கருத்து",
  "oeeCreatedBy": "உருவாக்கியவர்",
  "oeeObjectType": "பொருள் வகை",
  "machine": "இயந்திரம்",
  "manual": "கையேடு",
  "historicalReport": "வரலாற்று அறிக்கை",
  "pleaseSelectWorkCenter": "வேலை மையத்தைத் தேர்ந்தெடுக்கவும்",
  "pleaseSelectResource": "மூலதனத்தைத் தேர்ந்தெடுக்கவும்",
  "Work Center": "வேலை மையம்",
  "Resource": "மூலநிலை",
  "Select Shift": "அமர்வைத் தேர்ந்தெடு",
  "Event Type": "நிகழ்வு வகை",
  "Date Range": "தேதி வரம்பு",
  "filterby": "филь",
  "historicalTable": "வரலாற்று தொலைவரை",
  "selectAll": "அனைத்தை தேர்ந்தெடு",
  "clearSelection": "தேரவை நீக்கு",
  "availabilityAgainstResource": "மூலதனத்திற்கு எதிராக கிடைக்கும்",
  "availabilityAgainstShift": "அமர்வுக்கு எதிராக கிடைக்கும்",
  "confirmLayoutChange": "வடிவமைப்பை மாற்றியமைக்கவும்",
  "layoutChangeWarning": "வடிவமைப்பை மாற்றியமைக்கவும் அனைத்து நீட்டிப்புகளை நீக்கிறது. உறுதியாக இருக்கிறீர்களா?",
  "editAttachment": "இணைப்பு திருத்து",
  "attachmentUpdated": "இணைப்பு வெற்றிகரமாக புதுப்பிக்கப்பட்டது",
  "attachmentAdded": "இணைப்பு வெற்றிகரமாக சேர்க்கப்பட்டது",
  "optionalEntries": "விருப்பமான புள்ளிகள்",
  "requiredEntries": "தேவைப்படுமான புள்ளிகள்",
  "relesable": "ரேலேஸேபல",
  "new": "புதியா",
  "fieldType": "பிளைட் டைப்",
  "customDataFields": "தனிப்பயன் தரவு புலங்கள்",
  "editAttachmentPoint": "புதிய புள்ளி தொகுக்கவும்",
  "mandatoryStep": "கருத்து",
  "canSkip": "செலுதல்",
  "requiresSignOff": "சுற்றுகோளம்",
  "autoProgressOnComplete": "நிரூபித்து",
  "procedureSteps": "பிளைட் டைப்",
  "phaseVersion": "நிலை பதிப்பு",
  "mfr": "எம்.எப்.ஆர்",
  "mfrVersion": "எம்.எப்.ஆர் பதிப்பு",
  "bmr": "பி.எம்.ஆர்",
  "bmrVersion": "பி.எம்.ஆர் பதிப்பு",
  "PleaseSelectAttachmentsToRemove": "நீக்க இணைப்புகளைத் தேர்ந்தெடுக்கவும்",
  "RemoveSelectedAttachments": "தேர்ந்தெடுத்த இணைப்புகளை நீக்கவும்",
  "NoAttachmentsToRemove": "நீக்க இணைப்புகள் எதுவும் இல்லை",
  "RemoveAllAttachments": "அனைத்து இணைப்புகளையும் நீக்கவும்",
  "AreYouSureYouWantToRemoveAllAttachments": "அனைத்து இணைப்புகளையும் நீக்க வேண்டுமா?",
  "AllAttachmentsRemoved": "அனைத்து இணைப்புகளும் நீக்கப்பட்டன",
  "allowMultipleDc": "மேற்கூறுகள் மேலும்",
  "allowPartialSave": "எழுத்தும் சேமிப்பை",
  "allowSaveOnValidateFail": "செலுத்தும் பாதுபோற்றுதல் தோல்வில்",
  "optionalAndRequiredEntries": "விருப்பமான புள்ளிகள்",
  "allowAddRow": "பாடு புள்ளிகளையும் சேர்க்கவும்",
  "overRideRangeValue": "ரேங்கு மூலக மானவிடு",
  "selectNcCode": "NC கோடு தேர்ந்தெடுக்கவும்",
  "ncLog": "NC லோக",
  "hideColumn": "நிரலை மறைக்கவும்",

  // HRM Settings
  "settings.sidebar.profile": "Profile",
  "settings.sidebar.security": "Security",
  "settings.sidebar.notifications": "Notifications",
  "settings.sidebar.preferences": "Preferences",
  "settings.sidebar.support": "Help & Support",
  "settings.sidebar.logout": "Logout",
  "settings.profile.title": "Profile Settings",
  "settings.profile.personalInfo": "Personal Information",
  "settings.profile.emergencyContact": "Emergency Contact",
  "settings.profile.name": "Name",
  "settings.profile.contactNumber": "Contact Number",
  "settings.profile.personalEmail": "Personal Email",
  "settings.profile.relationship": "Relationship",
  "settings.profile.phone": "Phone",
  "settings.profile.uploadPhoto": "Upload Photo",
  "settings.profile.saveChanges": "Save Changes",
  "settings.security.title": "Security",
  "settings.security.changePassword": "Change Password",
  "settings.security.comingSoon": "Coming Soon",
  "settings.security.comingSoonDesc": "Password changes are managed through your SSO provider",
  "settings.security.currentPassword": "Current Password",
  "settings.security.newPassword": "New Password",
  "settings.security.confirmPassword": "Confirm Password",
  "settings.security.passwordStrength": "Password Strength",
  "settings.security.sessionInfo": "Session Info",
  "settings.security.lastLogin": "Last Login",
  "settings.security.loginMethod": "Login Method",
  "settings.notifications.title": "Notifications",
  "settings.notifications.push": "Push Notifications",
  "settings.notifications.email": "Email Notifications",
  "settings.notifications.dnd": "Do Not Disturb",
  "settings.notifications.salaryCredit": "Salary Credit",
  "settings.notifications.leaveApproval": "Leave Approval",
  "settings.notifications.generalAnnouncements": "General Announcements",
  "settings.notifications.holidayAlerts": "Holiday Alerts",
  "settings.notifications.appraisalUpdates": "Appraisal Updates",
  "settings.notifications.payslipAvailable": "Payslip Available",
  "settings.notifications.policyUpdates": "Policy Updates",
  "settings.notifications.expenseApproval": "Expense Approval",
  "settings.notifications.projectAssignments": "Project Assignments",
  "settings.notifications.dndStartTime": "Start Time",
  "settings.notifications.dndEndTime": "End Time",
  "settings.notifications.savePreferences": "Save Preferences",
  "settings.preferences.title": "Preferences",
  "settings.preferences.language": "Language",
  "settings.preferences.calendarSync": "Calendar Sync",
  "settings.preferences.calendarComingSoon": "Integration coming soon",
  "settings.preferences.theme": "Theme",
  "settings.preferences.darkMode": "Dark Mode",
  "settings.preferences.googleCalendar": "Google Calendar",
  "settings.preferences.outlookCalendar": "Outlook Calendar",
  "settings.support.title": "Help & Support",
  "settings.support.submitTicket": "Submit a Ticket",
  "settings.support.myTickets": "My Tickets",
  "settings.support.quickLinks": "Quick Links",
  "settings.support.subject": "Subject",
  "settings.support.category": "Category",
  "settings.support.description": "Description",
  "settings.support.priority": "Priority",
  "settings.support.submit": "Submit Ticket",
  "settings.support.privacyPolicy": "Privacy Policy",
  "settings.support.termsOfService": "Terms of Service",
  "settings.support.noTickets": "No tickets submitted yet",
  "settings.logout.confirm": "Are you sure you want to logout?",
  "settings.logout.title": "Logout",
  "nav.sidebar.dashboard": "Dashboard",
  "nav.sidebar.employees": "Employees",
  "nav.sidebar.administration": "Administration",
  "nav.sidebar.selfService": "Self-Service",
  "nav.sidebar.financePolicy": "Finance & Policy",
  "nav.sidebar.operations": "Operations",
  "nav.sidebar.settings": "Settings",
  "nav.sidebar.notifications": "Notifications",
  "nav.app.organization": "Organization Setup",
  "nav.app.userMaintenance": "User Maintenance",
  "nav.app.userGroup": "User Group",
  "nav.app.accessControl": "Access Control",
  "nav.app.userCredentials": "User Credentials",
  "nav.app.activityMaintenance": "Activity Maintenance",
  "nav.app.activityGroup": "Activity Group",
  "nav.app.leave": "Leave Management",
  "nav.app.travel": "Travel Request",
  "nav.app.expense": "Expense Report",
  "nav.app.payslip": "Payslip",
  "nav.app.appraisal": "Performance Appraisal",
  "nav.app.timesheet": "Timesheet",
  "nav.app.payroll": "Payroll Processing",
  "nav.app.compensation": "Compensation Master",
  "nav.app.policies": "HR Policies",
  "nav.app.announcements": "Announcements",
  "nav.app.projects": "Projects & Resources",
  "nav.app.assets": "Asset Management",
  "nav.app.holidays": "Holidays Calendar",
  "dashboard.sublabel.organization": "Manage structure",
  "dashboard.sublabel.userMaintenance": "Manage users",
  "dashboard.sublabel.userGroup": "Group permissions",
  "dashboard.sublabel.accessControl": "RBAC roles",
  "dashboard.sublabel.userCredentials": "Manage credentials",
  "dashboard.sublabel.activityMaintenance": "Manage activities",
  "dashboard.sublabel.activityGroup": "Group activities",
  "dashboard.sublabel.leave": "Apply & track leaves",
  "dashboard.sublabel.travel": "Request trips",
  "dashboard.sublabel.expense": "Submit claims",
  "dashboard.sublabel.payslip": "View salary slips",
  "dashboard.sublabel.appraisal": "Performance review",
  "dashboard.sublabel.timesheet": "Log work hours",
  "dashboard.sublabel.payroll": "Process payroll",
  "dashboard.sublabel.compensation": "Salary master",
  "dashboard.sublabel.policies": "Company policies",
  "dashboard.sublabel.announcements": "Company updates",
  "dashboard.sublabel.projects": "Manage projects",
  "dashboard.sublabel.assets": "Track assets",
  "dashboard.sublabel.holidays": "Holiday calendar",
  "dashboard.task.applyLeave": "Apply Leave",
  "dashboard.task.submitExpense": "Submit Expense",
  "dashboard.task.viewPayslip": "View Payslip",
  "dashboard.task.logTimesheet": "Log Timesheet",
  "dashboard.task.requestTravel": "Request Travel",
  "dashboard.task.viewAppraisal": "View Appraisal",
  "dashboard.quickTasks": "Quick Tasks",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.viewAll": "View All",
  "dashboard.search.placeholder": "Search apps and tasks...",
  "dashboard.activity.leaveApproved": "Leave approved",
  "dashboard.activity.expenseSubmitted": "Expense submitted",
  "dashboard.activity.timesheetSaved": "Timesheet saved",
  "nav.breadcrumb.home": "Home",
  "nav.footer.version": "v1.0.0",
  "nav.footer.copyright": "© 2026 RITS Consulting",
  "nav.footer.helpCenter": "Help Center"
}
