export type ViewerRole = "EMPLOYEE" | "SUPERVISOR" | "HR_ADMIN" | "SUPER_ADMIN" | "HR_MANAGER";
export type DashboardRole = "EMPLOYEE" | "MANAGER" | "HR" | "HR_MANAGER" | "ADMIN" | "SUPERADMIN";
export type WidgetType = "KPI" | "TABLE" | "LIST" | "CALENDAR" | "BAR_CHART" | "LINE_CHART" | "PIE_CHART" | "ERROR";
export type AlertSeverity = "INFO" | "WARNING" | "CRITICAL";
export type AlertStatus = "ACTIVE" | "DISMISSED";
export type SnapshotType = "HR_OVERVIEW" | "DEPARTMENT" | "WORKFORCE";

// --- Widget Data Shapes (matching backend response) ---

export interface KpiData {
  label: string;
  value: string | number;
  unit?: string;
  trend?: "UP" | "DOWN" | "STABLE" | null;
  trendPercentage?: number | null;
  trendPeriod?: string | null;
  colorIndicator?: "GREEN" | "YELLOW" | "RED" | null;
}

export interface TableData {
  columns: string[];
  rows: Record<string, unknown>[];
  totalRows?: number;
  currentPage?: number | null;
}

export interface ChartData {
  chartType: string;
  title: string;
  labels: string[];
  datasets: ChartDataset[];
  options?: unknown;
}

export interface ChartDataset {
  label: string;
  data: number[];
  backgroundColor?: string[];
  borderColor?: string | null;
}

// --- Dashboard Widget (from backend response) ---

export interface DashboardWidget {
  widgetDefinitionHandle?: string | null;
  widgetCode: string;
  widgetName: string;
  widgetType: WidgetType;
  data: KpiData | TableData | ChartData | Record<string, unknown>;
  dataAsOf?: string;
  fromCache?: boolean;
}

// --- Dashboard Alert (from backend response) ---

export interface DashboardAlert {
  handle: string;
  alertType: string;
  severity: AlertSeverity;
  title: string;
  message: string;
  entityType?: string | null;
  entityHandle?: string | null;
  actionUrl?: string | null;
  status: AlertStatus;
  createdDateTime: string;
  autoGenerated: boolean;
}

// --- Dashboard Response (from role-specific endpoints) ---

export interface DashboardResponse {
  site: string;
  viewerRole: string;
  viewerId: string;
  layout: DashboardLayoutResponse;
  widgets: DashboardWidget[];
  alerts?: DashboardAlert[];
  dataAsOf?: string;
  messageDetails?: unknown;
}

// --- Layout (from backend response) ---

export interface DashboardLayoutResponse {
  handle?: string | null;
  dashboardName: string;
  theme: string;
  panels: DashboardPanel[];
  allowCustomization: boolean;
  messageDetails?: unknown;
}

export interface DashboardPanel {
  panelId: string;
  panelTitle: string;
  column: number;
  row: number;
  columnSpan: number;
  rowSpan: number;
  widgets: WidgetPlacement[];
  collapsed: boolean;
}

export interface WidgetPlacement {
  widgetDefinitionHandle: string;
  widgetName?: string | null;
  displayOrder: number;
  visible: boolean;
  customSettings?: Record<string, unknown> | null;
}

// --- Widget Definition (from catalog) ---

export interface WidgetDefinition {
  handle: string;
  site: string;
  widgetCode: string;
  widgetName: string;
  description?: string;
  category: string;
  widgetType: WidgetType;
  dataSourceMethod?: string | null;
  defaultSettings?: Record<string, unknown> | null;
  iconName?: string | null;
  colorScheme?: string | null;
  minColumnSpan?: number | null;
  minRowSpan?: number | null;
  resizable?: boolean | null;
  applicableRoles: string[];
  systemWidget: boolean;
  active: number;
  createdDateTime: string;
  createdBy: string;
  modifiedDateTime?: string | null;
  modifiedBy?: string | null;
}

// --- Snapshot (from backend response) ---

export interface DashboardSnapshot {
  handle: string;
  site: string;
  snapshotType: string;
  scopeId: string;
  workforceSummary?: WorkforceSummary;
  attendanceSummary?: AttendanceSummary;
  payrollSummary?: PayrollSummary;
  performanceSummary?: PerformanceSummary;
  policyComplianceSummary?: PolicyComplianceSummary;
  quickMetrics?: unknown;
  computedAt: string;
  nextRefreshAt?: string;
  computedBy: string;
  active: number;
  createdDateTime: string;
  modifiedDateTime: string;
}

export interface WorkforceSummary {
  totalEmployees: number;
  activeEmployees: number;
  inactiveEmployees: number;
  newJoineesThisMonth: number;
  resignationsThisMonth: number;
  onProbation: number;
  byDepartment: Record<string, number>;
  byLocation: Record<string, number>;
  byGender: Record<string, number>;
  byEmploymentType: Record<string, number>;
  averageTenureYears: number;
  openPositions: number;
  asOf: string;
}

export interface AttendanceSummary {
  presentToday: number;
  absentToday: number;
  onLeaveToday: number;
  wfhToday: number;
  pendingLeaveRequests: number;
  leaveRequestsApprovedThisMonth: number;
  averageAttendanceRate: number;
  leaveTypeBreakdown: Record<string, number>;
  asOf: string;
}

export interface PayrollSummary {
  lastPayrollMonth: string;
  totalGrossPay: number;
  totalNetPay: number;
  totalDeductions: number;
  totalEmployerContributions: number;
  payrollStatus: string;
  processedEmployees: number;
  pendingApprovals: number;
  asOf: string;
}

export interface PerformanceSummary {
  activeCycle: string;
  activeCycleStatus: string;
  totalReviewsInitiated: number;
  selfAssessmentsCompleted: number;
  managerAssessmentsCompleted: number;
  calibrationsPending: number;
  reviewsCompleted: number;
  averageRating: number;
  ratingDistribution: Record<string, number>;
  activePips: number;
  asOf: string;
}

export interface PolicyComplianceSummary {
  totalPublishedPolicies: number;
  policiesRequiringAck: number;
  employeesWithPendingAck: number;
  overallAcknowledgmentRate: number;
  overdueAcknowledgments: number;
  policiesDueForReview: number;
  asOf: string;
}

export interface SnapshotScheduleResponse {
  site: string;
  cronExpression: string;
  enabled: boolean;
  updatedBy: string;
  updatedAt: string;
  message: string;
}

// --- Legacy types kept for backward compatibility with existing store/components ---

export interface EmployeeProfile {
  id: string;
  name: string;
  designation: string;
  department: string;
  reportingTo?: string;
  employeeCode: string;
  joinedDate: string;
  photoUrl?: string;
  status: string;
  tenure?: string;
}

export interface LeaveBalance {
  leaveType: string;
  leaveTypeCode: string;
  total: number;
  used: number;
  available: number;
  color?: string;
}

export interface PendingRequest {
  id: string;
  type: "LEAVE" | "EXPENSE" | "ASSET" | "TRAVEL" | "TIMESHEET";
  title: string;
  status: string;
  submittedAt: string;
  module: string;
}

export interface PayslipSummary {
  month: string;
  year: number;
  netPay: number;
  currency: string;
  downloadUrl?: string;
  note?: string;
}

export interface GoalProgress {
  id: string;
  title: string;
  progress: number;
  weight?: number;
}

export interface HolidayItem {
  date: string;
  name: string;
  type?: string;
  daysFrom?: number;
}

export interface AnnouncementAlert {
  id: string;
  title: string;
  priority: string;
  category: string;
  publishedAt: string;
  isRead?: boolean;
}

export interface TeamMember {
  id: string;
  name: string;
  designation: string;
  status: "PRESENT" | "ON_LEAVE" | "REMOTE" | "ABSENT";
  avatarUrl?: string;
}

export interface TeamOverviewStats {
  present: number;
  onLeave: number;
  remote: number;
  total: number;
}

export interface ApprovalCount {
  module: string;
  count: number;
  route: string;
}

export interface HeadcountTrendData {
  month: string;
  headcount: number;
  newHires: number;
  separations: number;
}

export interface DeptDistributionItem {
  department: string;
  count: number;
  percentage: number;
  color?: string;
}

export interface AttritionData {
  currentRate: number;
  targetRate: number;
  ytdSeparations: number;
  lastYearSeparations: number;
  status: "healthy" | "warning" | "critical";
}

export interface LeaveUtilizationItem {
  leaveType: string;
  daysUsed: number;
  percentage: number;
  color?: string;
}

export interface HrAlert {
  handle: string;
  alertType: string;
  severity: AlertSeverity;
  title: string;
  message: string;
  entityType?: string | null;
  entityHandle?: string | null;
  actionUrl?: string | null;
  status: AlertStatus;
  createdDateTime: string;
  autoGenerated: boolean;
}

export type SystemStatus = "OK" | "WARNING" | "ERROR";

export interface SystemHealthData {
  servicesHealthy: number;
  totalServices: number;
  dbStatus: SystemStatus;
  apiResponseMs: number;
  activeUsers: number;
}

export interface ModuleUsageItem {
  module: string;
  usagePercent: number;
  activeUsers: number;
}

export interface AuditActivityItem {
  time: string;
  user: string;
  module: string;
  action: string;
  details: string;
}

export interface WidgetLayout {
  i: string;
  x: number;
  y: number;
  w: number;
  h: number;
  minW?: number;
  minH?: number;
}

export interface DashboardLayout {
  role: DashboardRole;
  widgets: string[];
  layout: WidgetLayout[];
}
